### PR TITLE
Update QHexEdit library to version 0.7.7

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by justinclift** [comment]
Hmmm, the Travis failure is a bit cryptic to me:

```
Linking CXX executable sqlitebrowser
libs/qhexedit/libqhexedit.a(commands.cpp.o): In function `UndoStack::UndoStack(Chunks*, QObject*)':
/home/travis/build/sqlitebrowser/sqlitebrowser/libs/qhexedit/src/commands.cpp:(.text+0x179): undefined reference to `vtable for UndoStack'
libs/qhexedit/libqhexedit.a(commands.cpp.o): In function `UndoStack::insert(long long, QByteArray const&)':
/home/travis/build/sqlitebrowser/sqlitebrowser/libs/qhexedit/src/commands.cpp:(.text+0x25a): undefined reference to `UndoStack::staticMetaObject'
libs/qhexedit/libqhexedit.a(commands.cpp.o): In function `UndoStack::removeAt(long long, long long)':
/home/travis/build/sqlitebrowser/sqlitebrowser/libs/qhexedit/src/commands.cpp:(.text+0x465): undefined reference to `UndoStack::staticMetaObject'
libs/qhexedit/libqhexedit.a(commands.cpp.o): In function `UndoStack::overwrite(long long, int, QByteArray const&)':
/home/travis/build/sqlitebrowser/sqlitebrowser/libs/qhexedit/src/commands.cpp:(.text+0x69a): undefined reference to `UndoStack::staticMetaObject'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by justinclift** [comment]
Lots of the things here seem relevant to the vtable error:

&nbsp; &nbsp; https://stackoverflow.com/questions/1095298/gcc-c-linker-errors-undefined-reference-to-vtable-for-xxx-undefined-refere

That might be a side effect of the later `undefined reference` ones though (not sure).

**Comment by revolter** [comment]
Maybe [this one](http://stackoverflow.com/a/4995907/865175)?

**Comment by justinclift** [comment]
I really don't know. :wink:

**Comment by revolter** [comment]
Sorry, I saw that I mistyped the branch name (__again__) and tried to rename it :( Opened #692.

**Pull request closed without merging**
