### PR TITLE
Fix incorrect version in Finder's Info view

### PR DESCRIPTION
**Pull request by revolter**
Related to #551.

Fix similar to QupZilla/qupzilla#1486.

### CODE REVIEW

**Comment by justinclift** [comment]
Awesome. :smile:

**Comment by justinclift** [comment]
Note - Just waiting for the Travis CI build to ok this, Just In Case. :wink:

(and no, not expecting it to fail)

**Comment by innermous** [comment]
Why don't just push it, since diff is straightforward and not ambiguous(thus no discussion needed) :smile:

**Comment by justinclift** [comment]
Yeah, ok.  You convinced me. 😀

**Comment by revolter** [comment]
Because I don't trust myself yet to directly push changes without PR. Don't want to make mistakes like #655 x_x

**Comment by justinclift** [comment]
Absolutely nothing wrong in being cautious when you feel like it. 😄

**Comment by innermous** [comment]
Yet, just IMO huge amount of merge commits pollute the log.
Good work on issues btw :+1:

**Comment by justinclift** [comment]
Lots of merge commits do look pretty nifty in the Network graph though. 😁

**Comment by revolter** [comment]
@innermous, Ok, I'll push trivial changes directly. And, thanks 😄

**Comment by innermous** [comment]
It's so miserable glitch, that I won't even open another issue for that.
In this about dialog in version label you can put cursor blink in any random position. It feels a bit awkward.
@justinclift should this be left just as is?

**Comment by justinclift** [comment]
Up to you.  If you want to adjust it, go for it. :smile:

**Comment by revolter** [comment]
@innermous, I don't think it's a good idea. It actually was intentional as seen in #222. Apple does that too:

screen shot 2016-07-16 at 19 55 26

so you can easily copy and paste the version when asked for. I agree it should leave the cursor there, blinking, but disabling selecting is not a good idea.

Also, being able to select the text "Version" is not great also, but it can't be easily done in the current state, as it's just a big string.

**Comment by justinclift** [comment]
Hmmm, yeah.  I'd completely forgotten about #222. 😵 

Just tried out https://github.com/sqlitebrowser/sqlitebrowser/commit/109ead98f2a83fa94e8f4f9ac963e3bba5423250 here, and the version text isn't selectable at all with that.

So, it sounds like the optimal approach would be to have the text be selectable, but without any kind of blinking cursor.  Is that achievable?

**Comment by revolter** [comment]
@justinclift, Done 😄

**Comment by justinclift** [comment]
Thanks @revolter, that's great!

Just tried it here, and yep it's selectable & no cursor seems present.  All good. :smile:

**Comment by revolter** [comment]
My first "direct" commit also 😄

**Comment by innermous** [comment]
@revolter alrighty then. I forgot about copy-paste use case.

**Comment by revolter** [comment]
No problem

**Pull request merged**
