### PR TITLE
fix release info in src/gen_version.h

### PR DESCRIPTION
**Pull request by mcprentiss**
minor fix of release version

### CODE REVIEW

**Comment by justinclift** [comment]
Ahhh, interesting.  Thanks for pointing this out.

I'd missed updating our master branch to 3.6.99 (not 3.6.0).  It's 3.6.99 to indicate "the development version of 3.6.x".  Want to update your commit with that, and then I'll merge it?

**Comment by mcprentiss** [comment]
Sure.  I think this is what you would like.  I am sure this info was was the least of your concerns.

**Comment by justinclift** [comment]
Thank you @mcprentiss, it's all good.  Every bit helps. :grin:

**Comment by mcprentiss** [comment]
Btw. The reason this was an issue for me was I had a few versions of sqlitebrowser installed and the help menu was how I choose to identify which is which. FYI.

**Pull request merged**
