### PR TITLE
I18N - Simplified Chinese

### PR DESCRIPTION
**Pull request by efreeking**

### CODE REVIEW

**Comment by justinclift** [comment]
@efreeking Would you be interested in updating the translation for our next release (in a few weeks)? :smile:

**Comment by efreeking** [comment]
2015-03-25 0:26 GMT+08:00 Justin Clift <notifications@github.com>:

**Comment by justinclift** [comment]
???

**Comment by justinclift** [comment]
@efreeking Would you have the time + interest to update this translation?

We have (mostly) frozen the strings for our upcoming 3.9.0 release, and
generated new .ts files using lupdate.  So... they are in a good state for
translating now, if you have the time. :smile:

**Pull request merged**
