### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by progh2**
My students use this application for android application. 
I love this project. =D

### CODE REVIEW

**Comment by justinclift** [comment]
Cool! :smile:

Would you be ok to squash both of those commits into a single one?  I can merge it after that. :grin:

**Comment by justinclift** [comment]
Note - If you're not sure how to combine/squash both of those commits into a single one, I can do it for you.  Just let me know. :grin:

**Comment by justinclift** [comment]
Heh Heh Heh.  It looks like you're still working on this.  Let me know when you feel it is ok to merge this, and I'll get it done.

**Comment by progh2** [comment]
Thank you, please merge~  :+1:

**Comment by justinclift** [comment]
Thank you @progh2. :smile:

It's now merged, with all of the commits combined into just one: https://github.com/sqlitebrowser/sqlitebrowser/commit/c2f78b682cdce01d70832d63f0bd5a4e3627ae4a

**Pull request closed without merging**
