### PR TITLE
Switch to using C++11 and Qt5

### PR DESCRIPTION
**Pull request by MKleusberg**
See issue #603. Putting this here for further discussion and tests, but should be merged as soon as #750 and #775 are done.

### CODE REVIEW

**Comment by justinclift** [comment]
Ahhh, that's weird.  Travis was saying your "Use Qt5" commit was failing, but now it's ok.

**Comment by MKleusberg** [comment]
@justinclift I was doing some tests with this branch and force pushing new versions to it, including multiple commits with the "Use Qt5" description. Might be because of that :innocent:

**Comment by justinclift** [comment]
No worries at all. :smile:

**Comment by justinclift** [comment]
Issue #750 and #775 are both closed now.

We can probably merge this now. :smile:

**Comment by MKleusberg** [comment]
Awesome :D Has someone warned Rene though? After all this will break the build process for the 'old' nightlies. So the script he is running could be disabled and maybe a redirection from the old URL to the new could be set up instead.

**Comment by justinclift** [comment]
Ahhh, good thinking.  I'll email him now to let him know. :smile:

**Comment by justinclift** [comment]
Rene emailed this morning.  The old MXE build script has been turned off, and he's put an automatic bounce in place from the old location to the new nightlies server.

I think we're good to get this done now. :smile:

**Comment by MKleusberg** [comment]
Ok, cool :) Let's give this a try then and see what happens.

**Comment by justinclift** [comment]
Ironically, I'd forgotten to update the OSX nightly build script to use Qt5.

Now fixed. :wink:

**Pull request merged**
