### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### sqlitebrowser/sqlitebrowser now has a Chat Room on Gitter

@innermous has just created a chat room. You can visit it here: [https://gitter.im/sqlitebrowser/sqlitebrowser](https://gitter.im/sqlitebrowser/sqlitebrowser?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/sqlitebrowser/sqlitebrowser?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by innermous** [comment]
Oh, should've make it manually. It adds badge on new row, which is awkward

**Comment by revolter** [comment]
I added it

**Comment by justinclift** [comment]
Excellent, good idea. 😎

**Comment by glawrence** [comment]
I have to admit, I knew it was added but could not see it for looking!

**Comment by SafaAlfulaij** [comment]
@glawrence ;-)
screenshot_ _

**Comment by glawrence** [comment]
Yes, thank you, I did find it but my point was if I knew it was there and could not see it, will anyone see it?

**Comment by revolter** [comment]
@glawrence, What do you mean? Was the badge image missing for you?

**Comment by justinclift** [comment]
Personally, I think it's just not a very "stand out visually" kind of button.  I had to hunt for it too.

But for me, that's because I'm used to seeing "a piece of green in the upper left" of our README. md.   Two pieces of green instead of one wasn't noticeable without looking. :wink:

**Comment by revolter** [comment]
Well, I think it's pretty "standard" to have the badges in a single line beneath the first header lime [this][1] and many others.

  [1]: https://github.com/zeit/hyperterm

**Comment by revolter** [comment]
Well, I think it's pretty "standard" to have the badges in a single line beneath the first header lime [this][1] and many others.

  [1]: https://github.com/zeit/hyperterm

**Pull request closed without merging**
