### PR TITLE
Application icon cleanup

### PR DESCRIPTION
**Pull request by scottfurry**
Ensure images used for application icon are a "best quality" image
with consistent square size. A sharp, square image is vital for downstream
usage/installation.

File `images/logo.svg` was taken as canonical source. File was edited in
inkscape. It's document properties were cleaned up(incl. image metadata).
Document viewport was made to be a large size and square(256px^2).
Image itself was resized to ensure an 8px margin.

File `images/logo.png` was created from svg (inkscape `export to png`
command). Image was generated with high compression as well as ensuring
an alpha layer and square sizing.

File `src/icons/sqlitebrowser.png` was copied from `images/logo.png`.

### CODE REVIEW

**Comment by scottfurry** [comment]
@justinclift  - recommend editing `src/tools/create_windows_icon.sh` changing line 7 from
```
	convert ../icons/sqlitebrowser.png -resize "$imgsize"x"$imgsize" -background transparent icon"$imgsize".png
```
...to:
```
	convert ../icons/sqlitebrowser.svg -resize "$imgsize"x"$imgsize" -background transparent icon"$imgsize".png
```

This should ensure the generated icon file has sharp and crisp images rather than scaled, fuzzy images derived from a lossy, binary source.

**Comment by justinclift** [comment]
Is `sqlitebrowser.svg` the correct filename for the `convert` argument?  I'm not seeing in the source tree, nor in this PR? :wink:

**Comment by scottfurry** [comment]
Suggestion was to use svg image in the `images` folder. My bad for not posting correct info. Updated command suggestion.

**Comment by justinclift** [comment]
No worries, wasn't 100% sure.  Came back from local Makerspace last night in brain-dead-tired-state. :smile:

**Comment by justinclift** [comment]
Just added that script tweak, and the newly generated windows icon from it in: https://github.com/sqlitebrowser/sqlitebrowser/commit/ba1c2a10ff2def8f42e49336fb7a2909a03caf46

Thanks heaps @scottfurry. :smile:

**Comment by justinclift** [comment]
Hmmm, something is wrong with the icon for the newly generated windows icon.  Seems like an alpha channel problem, but not sure.

DB4S-new_icon_alpha_is_wrong

Discovered when doing final verification of the new v3.12.0-rc1 binaries on Windows.  I'll back out the change there, and regenerate the binaries using the older icon.  That'll give us time to figure out what's wrong, and have it fixed in the .1 release. :smile:

**Comment by justinclift** [comment]
As a data point, this is how the icons used to look on Windows:

DB4S-new_icon_alpha-how_it_should_look

**Comment by scottfurry** [comment]
@justinclift - this looks like an `alpha` channel issue.
Looking into this.

**Comment by scottfurry** [comment]
Changes below. The extra "MAGICK_CMDS" are things that convert needs **BEFORE** identifying the image (and why everything went pear shape for us).
**_Bottom line_** Order of parameters to `convert` is vital!!! Previous version of convert script was overlooking that and somehow it all worked out anyway.
```
#!/usr/bin/env sh

# This script depends on ImageMagick being installed

MAGICK_CMDS="+antialias -units PixelsPerInch -alpha set -background transparent"
for imgsize in 16 32 64 128
do
    RESIZE="${imgsize}x${imgsize}"
    convert ${MAGICK_CMDS} ../../images/logo.svg -resize ${RESIZE} icon"${imgsize}".png
    files="$files icon$imgsize.png"
done
convert $files ../iconwin.ico
rm $files
```

**Comment by justinclift** [comment]
Thanks.  Would you be ok to chuck it in a PR so I can just hit the Merge button on it? :smile:

**Comment by scottfurry** [comment]
PR to follow

**Pull request merged**
