### PR TITLE
Fixed typos in RU translation

### PR DESCRIPTION
**Pull request by dragokas**

### CODE REVIEW

**Comment by scottfurry** [comment]
@justinclift, @chrisjlocke - Ping

**Comment by chrisjlocke** [comment]
Thanks @dragokas

**Comment by mgrojo** [comment]
Thanks, @dragokas.

We are in the process of releasing a new version and the translation process has been started. For the moment, nobody has volunteered to translate the application to Rusian, so DB4S v3.13 could be delivered with an incomplete translation, so I invite you to contribute to this translation. If you are willing, just announce it on https://github.com/sqlitebrowser/sqlitebrowser/issues/3452

**Comment by dragokas** [comment]
@mgrojo theoretically, yes, but not soon. I had experience in large translations. Practically, I need more information:
1) Is there fast way to estimate roughly how many characters require translation?
2) do you have a special convenient tool to work with *.ts as interpreter?
3) I have limited experience in collab, especially at GitHub, and I already see 3 more interpreters are listed (only 1 have an email specified). Since Github has no PM system, how can we coordinate with each other regarding to this project?

**Comment by mgrojo** [comment]
@dragokas:
1. In https://github.com/sqlitebrowser/sqlitebrowser/issues/3452 we have the pending strings, in the case of Russian there are 507.
2. I recommend Linguist, the official Qt tool for translation.
3. The other translators should have received a notification when they were mentioned in the issue, but haven't answered, so probably have no longer time or are not interested. In any case, you could coordinate with any collaborator using an issue or a [discussion](https://github.com/sqlitebrowser/sqlitebrowser/discussions). Maybe with someone volunteering, the others are encouraged to contribute again. It's easier to do when you can share the work.

**Pull request merged**
