### PR TITLE
Brazilian Portuguese translation updates for 3.12

### PR DESCRIPTION
**Pull request by bernardosulzbach**
I think this is complete.

### CODE REVIEW

**Comment by justinclift** [comment]
Awesome!  Thanks heaps @bernardosulzbach. :smile:

**Comment by justinclift** [comment]
Oops.  I should have squashed those to a single commit.  Oh well, next time. :wink:

**Comment by bernardosulzbach** [comment]
> Oops. I should have squashed those to a single commit. Oh well, next time.

I see. I am only around here when updating translations, so I am not really sure if I should push as-is for the review or squash them myself.

**Comment by justinclift** [comment]
Either way is fine.  Most of the time I'd squash them myself when merging, but forgot this time around.  It's not a big deal. :wink:

**Pull request merged**
