### PR TITLE
Upgrade project depedency nlohmann/JSON

### PR DESCRIPTION
**Pull request by scottfurry**
Previous usage, at revision 3.5.0, was a single header file
that appeared customized and contained contents of other
nlohmann/JSON header files.

This commit brings in nlohmann/JSON as a git submodule (at
reversion 3.6.1). Changes to project files made to
incorporate library structure.

NOTE: minimum CMAKE version moved up to 3.1 (from 2.8.12.2)
because of nlohmann library.

Commit is implementation stage for #1895 - BSON data.

### CODE REVIEW

**Comment by justinclift** [comment]
> NOTE: minimum CMAKE version moved up to 3.1 (from 2.8.12.2) because of nlohmann library.

That's a hard No.  We need to support older versions of CMake, for things like CentOS. :wink:

**Comment by justinclift** [comment]
It turns out there's a newer CMake available for CentOS in EPEL (semi-official extra repo for CentOS).  So, this will probably be workable after all. :smile:

**Comment by MKleusberg** [comment]
Three things here:
1) Could we just leave the cmake version at 2.8? Maybe the JSON library doesn't require 3.1 after all?
2) I'm not 100% sure about the sub module approach. I think we had a discussion about that a while ago and if I remember correctly the general tendency was to avoid them. It's especially worth keeping in mind here that this would change the build process because you need to clone with submodules and update them. That's of course not a good reason in itself but I wouldn't want to update all the documentation :wink:
3) The qmake build needs updating too to use the new path. But I could do that too if you want to :smile:

**Comment by justinclift** [comment]
Git submodules are a pain, from a practical perspective.

The concept of them is ok, but (so far) I've not seen any project implement them and have it go well.  It They seem to cause more issues than they solve. :frowning:

**Comment by scottfurry** [comment]
Intent was to pull in latest library. From the feedback, this may not be the best path to go forward.

**Pull request closed without merging**
