### PR TITLE
Create winget.yml

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
This action automatically generates manifests for WinGet Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

Before merging this:
1. Please add a GitHub token with `public_repo` and `workflow` scopes as a repository secret and rename the secret name in the workflow.
2. Fork [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) under @sqlitebrowser.

* Resolves https://github.com/sqlitebrowser/sqlitebrowser/issues/3138

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@chrisjlocke sorry for responding so late.

**Comment by justinclift** [comment]
Interesting idea.  @chrisjlocke You do Windows stuff... does this look good to you? :smile:

**Comment by chrisjlocke** [comment]
> add a token with public_repo and workflow stats

image

Did this, but clicking 'workflow' automatically ticked 'public_repo' (well, the whole section) .. assume that's OK?

**Comment by chrisjlocke** [comment]
> does this look good to you?

WinGet is great for installing stuff - the Windows version of appt ... so an easy way to get people to install, rather than give them a link, tell them to extract, blah blah ... the trouble is, WinGet is relatively new and fighting with chocolatey.  Netscape vs Explorer war! ;)  Guess WinGet will win as it'll come installed by default on Windows, unlike Chocolatey which has to be installed...defeating the purpose of making an app easy to install by having to install the installer.... ;)

Created a token, but as its my user, is that good enough?

**Comment by lucydodo** [comment]
@chrisjlocke It looks like we need to add the generated token to our repository Action Secrets. :)
[Settings -> Security -> Secrets -> Actions](https://github.com/sqlitebrowser/sqlitebrowser/settings/secrets/actions)

More information can be found [here](https://docs.github.com/en/actions/security-guides/encrypted-secrets). :)
>https://docs.github.com/en/actions/security-guides/encrypted-secrets

**Comment by chrisjlocke** [comment]
Thanks @lucydodo 👍

**Comment by vedantmgoyal2009** [comment]
Can this be merged now?

**Comment by chrisjlocke** [comment]
Merged. 😀

Thanks for your contribution. :)

**Pull request merged**
