### PR TITLE
Fix multiple commented out lines not being ignored

### PR DESCRIPTION
**Pull request by revolter**
This was supposed to be fixed by 842aec8, but it wasn't. It now removes
all the lines that optionally start with any number of spaces which are
followed by 2 consecutive dashes.

Could I get some help with intensive testing?

### CODE REVIEW

**Comment by revolter** [comment]
I got the commit message wrong, I'm tired. It actually removes anything starting with 2 consecutive dashes up to the end of the line.

**Comment by justinclift** [comment]
No worries.  I'll look at it properly tomorrow.  Tired here as well and finishing of some other stuff that doesn't need real thinking about. :smile:

**Comment by innermous** [comment]
All that's needed is just to remove everything after `--` dashes till the end of the lines, I am right?

**Comment by revolter** [comment]
@innermous, Yes, is there a simpler solution?

**Comment by innermous** [comment]
Sec, @revolter , I'll try to figure something out. If I get a better solution, I'll let you know.

**Comment by revolter** [comment]
Please wait for me to test this at home with a couple of queries that don't work know before merging.

**Comment by innermous** [comment]
Sure.

**Comment by revolter** [comment]
Here is a test of the used regex: https://regex101.com/r/O1PB9h/2

**Comment by justinclift** [comment]
For reference, that's:

```
SELECT * -- asd ffdsf
-- saf ewf sf
-- dsaf fd
FROM	-- sfsdf
table  -- asdasd
```

**Pull request merged**
