### PR TITLE
Fixing Issue #3312

### PR DESCRIPTION
**Pull request by scottfurry**
Bug: "Only display the icon" is not working after restart.

Resolved with change to MainWindow reload(). ToolBar Style not being applied properly.

### CODE REVIEW

**Comment by scottfurry** [comment]
Pulling out fix as a standalone pull request to address bug.

**Comment by mgrojo** [comment]
Seems good. But it's strange that the former code worked for the immediate application of the setting, but not after restart. Might be that a Qt bug?

**Comment by scottfurry** [comment]
Not sure if a QT thing. The change was made inside the `MainWindow::reload()` function. That gets called on startup and on return from `PreferencesDialog`. There was no "explicit" setting value for the QToolBar classes, just fallback values, when `PreferencesDialog` is invoked.

Change is to ensure the references to the `ui->[toolbar]->setToolBarStyle` function is invoked in `MainWindow`. And problem goes...away.

**Comment by scottfurry** [comment]
Finger issues. Need to wait for this to be pulled into main.

**Comment by scottfurry** [comment]
Can we get some movement on this one, please.

**Comment by justinclift** [comment]
No worries.  Is it ready for switching into a standard PR then merging? :smile:

**Comment by scottfurry** [comment]
The PR is ready but marked as a draft with request for review. Not sure if I did this or something else is at play here.

**Comment by justinclift** [comment]
No worries.  When making PR's the button for doing the PR creation is actually a drop down, and can be switched between making draft or standard ones.

I *think* I've seen it be sticky too, so if you do one "draft" PR then the next PR is automatically defaulted to the same choice until you switch back.  That's from rough memory anyway. :smile:

**Comment by scottfurry** [comment]
@justinclift - Thank you!

**Pull request merged**
