### PR TITLE
Enable HiDPI on Windows

### PR DESCRIPTION
**Pull request by sandman7920**
Enable HiDPI on Windows by default #2468

### CODE REVIEW

**Comment by MKleusberg** [comment]
Looks good to me but I can't really test it. Maybe @justinclift can make a build for @chrisjlocke to check this doesn't change anything for non-HiDPI monitors?

**Comment by justinclift** [comment]
Yep, I can make a special build that includes this, so we can make sure it doesn't break standard resolution displays too.

I'll get around it to after figuring out the macOS 3.12.1 release build problem, probably tonight some time. :smile:

**Comment by sandman7920** [comment]
Are [icons/resources](https://github.com/sqlitebrowser/sqlitebrowser/tree/master/src/icons) available in higher resolution?
Qt::AA_UseHighDpiPixmaps will try to load `@2x`,`@3x` etc.
With this PR everything is scaled properly, but icons are blurry.

**Comment by justinclift** [comment]
Good question.  I **think** we use one of the more common OSS icon sets that's around, I'm just not personally sure which one(s).  Someone will know though.

Hopefully that icon set has some SVG's too, which might be useful for solving that problem. :smile:

**Comment by chrisjlocke** [comment]
If you mean the button icons, then they're all derived from 16x16 PNGs.... so no high resolution variants are available.
http://www.famfamfam.com/lab/icons/silk/

**Comment by sandman7920** [comment]
https://codefisher.org/pastel-svg/

**Comment by justinclift** [comment]
@sandman7920 Oh cool, that looks promising. :smile:

**Comment by chrisjlocke** [comment]
Excellent, thanks @sandman7920 - useful link!  I use that icon set a lot in my own projects, so having larger versions is handy.

**Comment by justinclift** [comment]
This is a build of our latest `master` branch, with this PR applied on top:

* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-pr_2469_v1-win64.msi
* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-pr_2469_v1-win64.zip

No icon adjustments in it though. :wink:

@chrisjlocke Would you be ok to see how it looks on your (non HiDPI?) setup? :smile:

**Comment by chrisjlocke** [comment]
Runs without any issues at all. 👍

**Comment by justinclift** [comment]
Excellent, thanks @chrisjlocke! :smile:

**Comment by justinclift** [comment]
Ok, this is merged now.  We still need to figure out updated icons for HiDPI users though.

**Comment by chrisjlocke** [comment]
I assume you'd need some 'resources' directory where DB4S pulls the resources as necessary.  If it detects HiDPI (or command-switch?) it uses an alternative directory which contains SVGs or larger PNGs.

**Comment by sandman7920** [comment]
@chrisjlocke one could add `application_go.png` ,`application_go@2x.png`,`application_go@3x.png`,etc in icons.qrc  and then Qt will auto load necessary file depending on screen scale factor

**Comment by chrisjlocke** [comment]
For the avoidance of doubt (that and I'm a dummy) if the normal 16x16 icon is application_go.png, then application_go@2x.png would be 32x32, @3x.png would be 48x48, etc.
If I did that, threw it to Justin to lob in a build, etc, would you be OK to test it?  I don't have an HiDPI screen to verify it would work.

**Comment by sandman7920** [comment]
I think @3x.png will be enough.
I will try to add some resources form link above and compile with Qt 5.15.1 and post some screenshots here.

You can test for yourself (windows)
set QT_AUTO_SCREEN_SCALE_FACTOR=0
set QT_SCALE_FACTOR=2
DB Browser for SQLite.exe

**Comment by chrisjlocke** [comment]
Excellent, thanks!

**Comment by sandman7920** [comment]
I have made test with database_add.png (new database).
It turns out that all toolbars have icon size set to 30 which means currently all icons are almost 100% upscaled.
I think will be better icons to have 32px base.

Screenshots below are done with base 32 for database_add.png

Screenshot_2
Screenshot_3
Screenshot_1

**Comment by sandman7920** [comment]
Arggh not all icons exists in hi-res set
[found.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/5525999/found.txt)
[not_found.txt](https://github.com/sqlitebrowser/sqlitebrowser/files/5526000/not_found.txt)

**Comment by chrisjlocke** [comment]
Might be able to use variants and alternatives until they fill the gaps... there are also some ico to svg converters .... not perfect, but better than nothing.... maybe..... ;)

**Comment by sandman7920** [comment]
I don't think project is still alive.
Otherwise with 32 base everything look crisp.
The best solution will be SVG format (one set of files, works on all resolutions).

**Comment by sandman7920** [comment]
Digging into Qt documentation [iconSize-prop](https://doc.qt.io/qt-5/qtoolbar.html#iconSize-prop)

```
The default size is determined by the application's style and is derived from the QStyle::PM_ToolBarIconSize pixel metric.
It is the maximum size an icon can have. Icons of smaller size will not be scaled up.
```

This means iconSize it's a platform dependant, or the iconSize for all toolbars must be set manually.

**Comment by sandman7920** [comment]
I have made build with SVG resources and everything looks great on my side (4K display).
[icons.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/5532581/icons.zip)

@chrisjlocke may you test this build [sqlitebrowser.zip](http://office.astrapaging.com/sqlitebrowser.zip)

@justinclift maybe it's better HiDPI to be enabled on all platforms?

Some of UI files had to be changed, hard link to PNG files (not aliasing)

Replacements
view-refresh.png -> arrow_refresh_small.svg
comment_block.png -> text_padding_top.svg
database_link_broken.png -> link_break.svg
document-open.png -> folder_page.svg
internet-web-browser.png -> page_link.svg
document-link.png -> script_link.svg
page_foreign_key.png -> table_key.svg
save_all.png -> database_save.svg
style.png -> font.svg
style_add.png -> font_add.svg
style_delte.png -> font_delte.svg
style_edit.png -> font_edit.svg
text_indent.png -> text_padding_left.svg
text_underline.png -> text_underlined.svg

TODO 
clear_filters.png
clear_sorting.png
cut.png
filter.png
hourglass.png
package_rename.png
package_save.png
page_copy_sql.png
page_paintbrush.png
sqlitebrowser.png
text_paintbrush.png
text_replace.png

**Comment by sandman7920** [comment]
New vs Old

Screenshot_1

**Comment by justinclift** [comment]
This looks like it's going down a pretty awesome path. :smile:

> maybe it's better HiDPI to be enabled on all platforms?

No objection here.  Seems like we could drop the `#ifdef Q_OS_WIN` (and matching close) lines, which should stop it from being Windows-only.

That would at least let people on other platforms try it out, report problems, etc. :smile:

**Comment by sandman7920** [comment]
@justinclift could you try to build https://github.com/sandman7920/sqlitebrowser/tree/SVG on Mac OS

Replacement
```
view-refresh.png -> arrow_refresh_small.svg
comment_block.png -> text_padding_top.svg
database_link_broken.png -> link_break.svg
document-open.png -> folder_page.svg
internet-web-browser.png -> page_link.svg
document-link.png -> script_link.svg
page_foreign_key.png -> table_key.svg
save_all.png -> database_save.svg
style.png -> font.svg
style_add.png -> font_add.svg
style_delte.png -> font_delte.svg
style_edit.png -> font_edit.svg
text_indent.png -> text_padding_left.svg
text_underline.png -> text_underlined.svg
page_paintbrush.png -> color_hsl.svg
text_paintbrush.png -> color_wheel.svg
```

I couldn't find replacement for
```
clear_filters.png
clear_sorting.png
cut.png
filter.png
hourglass.png
package_rename.png
package_save.png
page_copy_sql.png
text_replace.png
```

Someone else should try to find replacement,  I am pretty bad with those kind of things.

**Comment by justinclift** [comment]
@sandman7920 In theory, these should be it: :smile:

* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite_pr_2469_v2.dmg (SQLite)
* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher_pr_2469_v2.dmg (SQLCipher)

**Comment by sandman7920** [comment]
@justinclift someone should test this, I don't have Mac at home and won't be going to the office for two weeks.

**Comment by justinclift** [comment]
@revolter Would you have time to test if the icons in either of those two builds looks better on Retina / HiDPI screens than the standard (eg 3.12.1) build?

**Comment by revolter** [comment]
Yes, they're sharp now, but too big:

image

image

In this case, the icons except the first one are still blurry:

image

**Comment by sandman7920** [comment]
Toolbar icons are platform dependent.

```
QToolbar::iconSize
The default size is determined by the application's style and is derived from the QStyle::PM_ToolBarIconSize pixel metric.
It is the maximum size an icon can have. Icons of smaller size will not be scaled up.
```

Which means it's tuned up to the platform Guidelines, from the screenshots above one could see that height of Toolbar is the same as before (only icons are scaled up), **Icons of smaller size will not be scaled up (before was 16px)**.

We could use something like this:
```cpp
class DB4SProxyStyle : public QProxyStyle {
public:
  int pixelMetric(QStyle::PixelMetric metric,
                  const QStyleOption *option = nullptr,
                  const QWidget *widget = nullptr) const override {

    if (metric == QStyle::PM_ToolBarIconSize) {
      return 16; // or maybe 22
    }

    return QProxyStyle::pixelMetric(metric, option, widget);
  }
};

...

int main( int argc, char ** argv )
{
// Create application object. All the initialisation stuff happens in there
    Application a(argc, argv);
    a.setStyle(new DB4SProxyStyle);

```

This will override default style with custom value.

@justinclift , @revolter what do you think

**Comment by revolter** [comment]
So we're not specifying their size at all, not directly nor indirectly? I suppose we're using the icons in `src/icons`, which looks like have a size of 16x16 pixels, while they are now displayed as 32x32 instead. So, are they really not scaled up?

**Comment by sandman7920** [comment]
Yes, default size is set by platform style. On Windows is 30 on Linux 22, but if supplied resource is less than theme (platform default style) value Qt doesn't perform upscaling.
Here SVG is scalable by definition and it's upscaled to the theme value.

**Comment by revolter** [comment]
I think that 16 would be perfect on macOS. For example, Safari uses 16pt icons too.

**Comment by sandman7920** [comment]
Screenshots with 16px on Windows, everything looks OK.
@justinclift could you rebuild package with latest changes (style proxy)

https://github.com/sandman7920/sqlitebrowser/tree/SVG

image

**Comment by justinclift** [comment]
@sandman7920 Yep, can do.  Are Windows or macOS or both needed? :smile:

**Comment by sandman7920** [comment]
On Windows everything looks OK.

@justinclift what is the next step, make new pull request?

**Comment by justinclift** [comment]
Meh, I'll do both.  macOS ones are building atm.  They should be online in about 45 mins or so...

**Comment by justinclift** [comment]
Ahhh.  Yeah, I'd say make a new PR.  Since the new macOS build is already running though, we might as well check that just to make sure too. :smile:

**Comment by sandman7920** [comment]
In master branch?

**Comment by justinclift** [comment]
Yep.  `master` is the right target branch to make the PR against. :smile:

**Comment by justinclift** [comment]
@revolter New macOS build to try, if you have the time. :smile:

* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher_pr_2469_v3.dmg

**Comment by revolter** [comment]
The buttons are also smaller now, but I personally actually like it more than before:

image

I don't know if it's related to this, but the text on these buttons gets truncated on hover:

image

**Comment by sandman7920** [comment]
@revolter before on Mac OS iconSize was set 22 (i think), which means height of the ToolBar was 22 and icons were drawn in the middle. Now height is 16, I also think it's looks better now.

>I don't know if it's related to this, but the text on these buttons gets truncated on hover

I don't think so, but you can try to start application with
env QT_AUTO_SCREEN_SCALE_FACTOR=0

**Comment by justinclift** [comment]
> The buttons are also smaller now, but I personally actually like it more than before

Awesome.  Seems like an all-around win then. :smile:

Thanks heaps for checking those builds @revolter. :smile:

@sandman7920 You up for creating an appropriate PR (against `master` branch)? :smile:

**Comment by revolter** [comment]
> I don't think so, but you can try to start application with
> env QT_AUTO_SCREEN_SCALE_FACTOR=0

Meaning

```sh
QT_AUTO_SCREEN_SCALE_FACTOR=0 open "~/Downloads/DB Browser for SQLite.app"
```

?

**Comment by sandman7920** [comment]
@revolter yes

**Comment by revolter** [comment]
Then it doesn't fix that issue.

**Comment by justinclift** [comment]
> QT_AUTO_SCREEN_SCALE_FACTOR=0 open "~/Downloads/DB Browser for SQLite.app"

I don't think that sets the environment properly.

Instead, run the executable in the `... .app/Contents/MacOS/` folder directly.  It'll be something like:

```
$ QT_AUTO_SCREEN_SCALE_FACTOR=0 "~/Downloads/DB Browser for SQLite.app/Contents/MacOS/DB Browser for SQLite"
```

**Comment by revolter** [comment]
Oh, true. But it still doesn't fix the issue.

**Comment by sandman7920** [comment]
@justinclift is this an Qt 5.15.x build

**Comment by justinclift** [comment]
@sandman7920 Yep.  Qt 5.15.1.

**Comment by justinclift** [comment]
As a data point, the test build has also been confirmed as working by someone on Twitter a few weeks ago:

https://twitter.com/hakanu_/status/1341405851677057025

(Just noticed now, as I haven't been keeping an eye on Twitter)

**Pull request merged**
