### PR TITLE
Fixes various small bugs with the quote and separator choices

### LINKED ISSUE #610: Third option in Quote character field of ExportCSV dialog isn't restored properly
Noticed another weird bug in the Export CSV dialog, while investigating a different one (#605).

The new weird bug is that the 3rd option for the Quote separator character is never selected correctly in the widget.  It may be something to do with string matching on the character, due to the way the compare in the function is run.

Need to look into it properly after a decent amount of sleep though. :smile:

### PR DESCRIPTION
**Pull request by justinclift**
Fixes #610.

Expanded out many of the functions so they can be single stepped
through easily by newbies (eg me), which allowed for identifying
(then fixing) a few minor bugs.

 * if setSeparatorChar() had an empty value passed to it the first
   time, then in subsequent calls it would silently use \0 instead,
   including using that in the output CSV data.  Likely not great. :wink:
 * the empty option for the quote separator is now correctly retained
   between runs of the dialog

### CODE REVIEW

**Comment by revolter** [comment]
A little off-topic regarding this PR, but, does this project have a coding style? I noticed that you put the brackets on the same line (I personally prefer this too), while in the rest of the project they are on a separate line. I think it would be a good idea to stick with a single coding style throughout the entire project. What do you think? Maybe we ca discuss this in more depth in #602.

**Comment by justinclift** [comment]
Hmmm, I've seen both styles of bracket placement in the code already.  (eg do a grep -r "else" from the main dir)

So, I just picked my preference. :smile:

**Comment by justinclift** [comment]
After sleeping on it, I kind of think the switch statement approach used in currentNewLineString() is super clear and without unwanted side effects:  https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/ExportCsvDialog.cpp#L322-L334

So, I might try redoing some of the methods in this PR using that, and see if it's an improvement. :smile:

**Comment by revolter** [comment]
I personally indent the `case`s :smile:

**Comment by revolter** [comment]
My question wasn't necessarily about this PR, it was about the whole project and the future PRs. But it was just an idea :smile:

**Comment by justinclift** [comment]
Yeah, its a good idea. :smile:

**Comment by justinclift** [comment]
With indenting the cases... I actually remember my decision here.  I went with the default that Qt Creator set them as when I first entered the switch keyword and hit return.

Personally, it's not something I care much about, so if we decide to have a defined coding style for them I'm happy to do whatever. :smile:

**Comment by justinclift** [comment]
Rewrote the functions using a switch statement.  Also fixed another minor-ish bug in the output, found when examining the csv output using hexedit.

Side note, that [hexedit](http://rigaux.org/hexedit.html) util is nifty.  Nicely, it's available via Homebrew (`brew install hexedit`).

**Pull request merged**
