### PR TITLE
set selected data type on Edit database cell dialog

### PR DESCRIPTION
**Pull request by gimKondo**
Data type isn't decided by column type, but user's decision on 'Edit database cell' dialog.
Note : This topic is discussed on issue #239.

### CODE REVIEW

**Comment by justinclift** [comment]
@rp- @MKleusberg Need reviewers for this.

@schdub What's your opinion on this too, in case Rene or Martin aren't around in the next few days? :smile:

**Comment by justinclift** [comment]
Guys?

**Comment by schdub** [comment]
@justinclift, its good solution imho. My first trying to fix #239 was something like this.
But also need to get rid dead code related to SqliteTableModel::m_vDataTypes

**Comment by justinclift** [comment]
So, merge this one now, and we can change SqliteTableModel::m_vDataTypes in a new PR?

**Comment by MKleusberg** [comment]
I see two problems here:
The minor one is in [EditTable.cpp](https://github.com/sqlitebrowser/sqlitebrowser/pull/286/files#diff-f307c53f8f195837664d83775f85c2a5R135) where the test for the Binary option should be language independent. The easiest way would be to put tr("...") around the 'Binary' string.

The major one is that it breaks the in-place editing in the Browse Data tab. If you don't open the Edit dialog for editing a cell content but just typing in the table view directly the changes aren't saved anymore. This is because in this case the SqliteTableModel::setData(const QModelIndex&, const QVariant&, int role) method is called which [in practice](https://github.com/sqlitebrowser/sqlitebrowser/pull/286/files#diff-1652727a9b5725cb5275a9270349896cR22) is just the parent implementation which does nothing. If there is any solution to this which doesn't require us to overload the setData method that would probably be the most elegant one. If there isn't any, the setData method with three arguments at least needs to be re-implemented to call the one with four.

**Comment by gimKondo** [comment]
I see. I missed such a case.
At any case, `using QAbstractTableModel::setData` is a bad solution.

`setData` mehod I modified should be implemented as another method (not as overload), I guess.
The another method is like following.

```cpp
bool setTypedData(const QModelIndex& index, bool isBlob, const QVariant& value, int role);
// or
bool setTypedData(const QModelIndex& index, int dataType, const QVariant& value, int role);
```

**Comment by justinclift** [comment]
Cool. Sounds like you guys are on it. :smile:

**Comment by justinclift** [comment]
@gimKondo Any interest in finishing this? :smile:

**Comment by gimKondo** [comment]
@justinclift Sorry to be late. Now, I don't find another issue about this.
I'll modify code based on current trunk soon.

**Comment by justinclift** [comment]
Thanks @gimKondo. :smile:

**Comment by gimKondo** [comment]
[progress report]
Now, I'm checking current branch for merging this feature.
Maybe, I'll finish all by next Sunday.

**Comment by justinclift** [comment]
That would be awesome. :smile:

**Comment by justinclift** [comment]
***reminder nudge*** :smiley_cat:

**Comment by gimKondo** [comment]
I fixed 2 bugs that pointed by @MKleusberg.

1. prevention of in-place editing
2. the lack of tr()

**Comment by justinclift** [comment]
Oh, that's excellent.  @rp- @MKleusberg ping! :grin:

**Comment by justinclift** [comment]
@gimKondo Hmmm, would you be ok to merge those 3 commits into a single one?  It's better for the git history when PR's are just one commit. :smile:

If you're not sure how to do it, I can give you the exact instructions. :grin:

**Comment by gimKondo** [comment]
@justinclift Sorry about dirty commit history.
I packed these commits to one.

**Comment by justinclift** [comment]
Perfect, thanks. :smile:

**Comment by justinclift** [comment]
Doesn't look like @rp- or @MKleusberg will have time to look at this in the near future, so I've proactively merged it.

If people could test the nightly builds and let us know if this code adds any problems, that would be great. :grin:

**Pull request merged**
