### PR TITLE
Update zh translation

### PR DESCRIPTION
**Pull request by mercury233**
All strings except the document of SqlLexer are done.

### CODE REVIEW

**Comment by justinclift** [comment]
Ok to merge this now? :smile:

I'm not personally sure about the SqlLexer pieces...

**Comment by mercury233** [comment]
Sure.

**Comment by mercury233** [comment]
https://github.com/sqlitebrowser/sqlitebrowser/blob/d522de70db1ee8662f9a2ea39fb7fd8c77f24a1a/src/SqlUiLexer.cpp#L66
I think it is the document of sql functions.

**Comment by justinclift** [comment]
Ahhh yeah.  Those are the in-built SQLite function names. :smile:

**Comment by justinclift** [comment]
Merged.  Thanks for this @mercury233. :smile:

**Pull request merged**
