### PR TITLE
Add build version to the nightly builds

### PR DESCRIPTION
**Pull request by karim**
Everyday the nightly version is built. Build version will be the day of the current year, and the full version format will be Major.Minor.Patch.Build

See #1346

### CODE REVIEW

**Comment by karim** [comment]
Please check developers discussion for more information about this.

**Comment by FriedrichFroebel** [comment]
You probably want to fix the number of days for a leap year [here](https://github.com/sqlitebrowser/sqlitebrowser/pull/1390/files#diff-af3b638bc2a3e6c650974192a53c7291R5) ;)

**Comment by karim** [comment]
@FriedrichFroebel Fixed now, thanks :smiley:

**Comment by karim** [comment]
@MKleusberg

I added `PRODUCT_VERSION` so that **ProductVersion** string can have a different value that **FileVersion**. But since it is okay for both to be the same, then I guess I should use `APP_VERSION` instead.

**Comment by karim** [comment]
Okay, I made the required changes. Now **FileVersion** and **ProductVersion** are the same. It is a Windows only thing so it shouldn't be a problem.

The commit messages have changed a lot since I started this PR, at first it was about adding the *day of the year* and now adding the full date. So hopefully when it is merged someone could change it to make it meaningful. :smiley:

**Comment by justinclift** [comment]
Heh Heh Heh.  Good point. :smile:

**Pull request merged**
