### PR TITLE
More Spanish translations for the master branch

### PR DESCRIPTION
**Pull request by lulol**
A few more terms translated to Spanish.

### CODE REVIEW

**Comment by justinclift** [comment]
It seems to be having a problem with `&oacute;`.  Is that a typo for `&acute;` ?

**Comment by justinclift** [comment]
To answer my own question... it's a real thing:

&nbsp; &nbsp; http://www.fileformat.info/format/w3c/htmlentity.htm

**Comment by lulol** [comment]
No. &oacute; is the html entity for 'ó'. Fixing now with the utf-8 character that worked perviously for other terms.

**Comment by justinclift** [comment]
Ahhh, good thinking. :smile:

**Comment by justinclift** [comment]
Thanks @lulol, that looks good. :smile:

**Comment by lulol** [comment]
You are welcome. Glad to help. :)

**Pull request merged**
