### PR TITLE
update zh trans

### PR DESCRIPTION
**Pull request by mercury233**

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @mercury233.  This is marked as "Draft", is that correct? :smile:

**Comment by mercury233** [comment]
There are much more strings to be translated

**Comment by justinclift** [comment]
No worries. :smile:

Let us know when it's ready to be merged, and we'll get it done.

**Comment by mercury233** [comment]
image
It is done now, except for the mass texts in SqlUiLexer. I'm not very good at SQL grammar so I won't translate them.

I need to wait the translations applied to the nightly build to do the reviews.

**Comment by justinclift** [comment]
Thanks heaps @mercury233, just merged them.  They'll be in tomorrow's nightly build, so you can review. :smile:

**Pull request merged**
