### PR TITLE
update German translation (Hotkeys)

### PR DESCRIPTION
**Pull request by horst-p-w-neubauer**
update German translation (Hotkeys)

some missing Ctrl to Strg and Shift to Umschalt
Trying to replace Return with Enter and Space with Leertaste.

### CODE REVIEW

**Comment by justinclift** [comment]
Awesome, thanks @horst-p-w-neubauer.

@FriedrichFroebel I'm merging this in now.  If something in it needs changing though, let us know. :smile:

**Comment by FriedrichFroebel** [comment]
As long as it works better with it (or just improves understandability without breaking anything), I am fine with it. From time to time I may miss some strings or parts of it (or mis-translate it) and I usually do not test the complete DB4S application with the translations - so some of the German translations may need fixes like in this PR.

**Comment by horst-p-w-neubauer** [comment]
@FriedrichFroebel , I'm preparing an update where I consequently translate 'record' to 'Datensatz'. Actually it switches between 'Zeile' and 'Eintrag'. That update would bring a lot of changes to the translation and I'd prefer to discuss it in advance. I absolutely vote for strict 1:1 transaltion for technical terms like record or row. But I swing between 'Datensatz' or 'Eintrag'. What would You prefer?

**Comment by FriedrichFroebel** [comment]
I would probably prefer the term "Datensatz" in this case. (As I did the translations across multiple days and for different releases, some other translations might be inconsistent as well.)

**Comment by horst-p-w-neubauer** [comment]
I agree. Is there a possibility to share a dictionary and other translation-decissions? That would help to work in teams and to be strict over time and releases.

**Comment by mgrojo** [comment]
For the Spanish translation, I like to take a look to the hints and glossary of the [KDE Spanish Translation Project](https://es.l10n.kde.org/). There is an equivalent [German project](https://community.kde.org/KDE_Localization/de) too, which seems very interesting and complete. It includes even a "visual dictionary". Of course, very specific terms used in DB4S should be agreed separately, because they might be missing in KDE.

**Comment by FriedrichFroebel** [comment]
As I do not have any overview about my decisions, I cannot share a dictionary for now. But feel free to create one if you have enough time - either as a working draft inside a dedicated issue, inside the wiki on a page regarding translations in general or by contacting me using e-mail to discuss it (my e-mail is should be available from my commits when viewed locally.)

**Pull request merged**
