### PR TITLE
Add Indonesian translation to V3.12.x

### PR DESCRIPTION
**Pull request by atriwidada**
Add Indonesian translation

### CODE REVIEW

**Comment by justinclift** [comment]
@atriwidada Thanks heaps, this looks really good.

Do you reckon it's ok for us to merge this now, or are you still working on it? :smile:

**Comment by atriwidada** [comment]
> Do you reckon it's ok for us to merge this now, or are you still working on it? smile

Hi,

I'm still working on it, hopefully can reach 95%+, but it will take around 1-2 months. Up to you to merge now or later :D

**Comment by justinclift** [comment]
No worries, lets leave it for you to complete and see how you go. :smile:

**Comment by justinclift** [comment]
@atriwidada How's this going? :smile:

**Comment by atriwidada** [comment]
> @atriwidada How's this going? smile

my latest translation is at 1271 strings out of 1354. haven't had time to reach 95% yet :(
would you like me to upload this one and make a new PR?

**Comment by justinclift** [comment]
Not sure of the "best" approach really.  I *think* you should be able to add the later version of the file to this PR as a new commit.

In theory... :grin:

**Comment by atriwidada** [comment]
update to 100%
[sqlb_id.20221121.zip](https://github.com/sqlitebrowser/sqlitebrowser/files/10051246/sqlb_id.20221121.zip)

**Comment by lucydodo** [comment]
Thank you for your contribution.
You can finalize the PR by adding a new commit to this PR,
Or I can commit the file that uploaded through your email address.

Personally, I recommend the former, but tell me what you want and I'll do it! 😄

**Comment by atriwidada** [comment]
replacing this with PR 3233 https://github.com/sqlitebrowser/sqlitebrowser/pull/3233

**Pull request closed without merging**
