### PR TITLE
Update Windows Installer to include SQLCipher

### PR DESCRIPTION
**Pull request by karim**

### CODE REVIEW

**Comment by justinclift** [comment]
Excellent.  I'll try this out later tonight most likely.  I'm doing some testing of `winbuild.bat` adjustments, for calling `build.cmd` automatically.  When they're working all right, these new SQLCipher enhancements should fit in neatly. :smile:

**Comment by karim** [comment]
Very nice. :smiley:

**Comment by justinclift** [comment]
Hmmm, hitting a weird problem with the `build.cmd` file added earlier today (not the updated one in this PR).

When `build.cmd` finishes, it seems to automatically terminate any batch file it's called from.

eg, lets say I have a simple batch file like this:

```
mkdir \foo
cd \foo
echo Building 32-bit executables
[do something here]
build.cmd Win32

echo Building 64-bit executables
[do more stuff here]
build.cmd Win64

echo Finished!
```

As soon as the first `build.cmd Win32` finishes, the whole batch file gets terminated.  No error code or anything, it just **stops** and returns control to the cmd.exe shell I called it from.

Any ideas?

**Comment by justinclift** [comment]
Ahhh.  I probably need to use `CALL build.cmd Win32` instead.

**Comment by karim** [comment]
Yeah, I done the exact same thing while testing and had to search to find out what is happening. :smiley:

**Comment by justinclift** [comment]
In theory, with the updated winbuild.bat I just pushed (also on the nightly server), we should have matching .msi files for all of the .exe's.

Once they've been working ok for a few weeks, we can think about which build(s) to keep making. :smile:

**Comment by justinclift** [comment]
On a side note, if anyone has the time/interest to add some lines to winbuild.bat for making a 32-bit Windows .zip version, there have been a few requests for that over the years too. :smile:

**Comment by karim** [comment]
> Once they've been working ok for a few weeks, we can think about which build(s) to keep making.

We should drop the .exe build with our next stable release if there were no issues with it till then.

> On a side note, if anyone has the time/interest to add some lines to winbuild.bat for making a 32-bit Windows .zip version

I was planning to make a portable version after we finish the installer. But it is not simple since Qt store its settings in Window registry. We need to change that to make it store its settings in its own folder instead. I will get that done at some point.

Right now we still need to do few more things with the installer. Add a custom dialog to disable version checking while installing. Maybe sign the .msi the same way we sign the stable build?

**Comment by justinclift** [comment]
Cool. :smile:

* Add a custom dialog to disable version checking while installing?

  Yep, that would help for the users which don't want automatic version checking for whatever reason.

* Maybe sign the .msi the same way we sign the stable build?

  Ahhh yeah.  Our signing process will probably need updating with our next stable build anyway.  The StartCom certifcate we currently use for .exe (+.msi) signing expires in a few months: #1229

**Pull request merged**
