### PR TITLE
fix Chinese translation

### PR DESCRIPTION
**Pull request by bssthu**
fix translations

### CODE REVIEW

**Comment by justinclift** [comment]
Awesome @bssthu, it's now perfect. :smile:

For reference, these are the changed strings in operation:

screen shot 2016-10-20 at 16 47 31
screen shot 2016-10-20 at 16 47 43
screen shot 2016-10-20 at 16 49 08
screen shot 2016-10-20 at 16 49 15

**Comment by justinclift** [comment]
Is it ok if we contact you when we are near to our next major release?

We will probably make a few string changes between now and then, and it would be great to have everything 100% translated at release time. :smile:

**Comment by bssthu** [comment]
Sure, I'm glad to help.

**Comment by justinclift** [comment]
Awesome. :smile:

**Pull request merged**
