### PR TITLE
korean translation

### PR DESCRIPTION
**Pull request by progh2**
Korean Traslation for 3.9.0 release.
Thank you!, @justinclift  =D

### CODE REVIEW

**Comment by progh2** [comment]
wow ^-^/

**Comment by justinclift** [comment]
Thanks @progh2, I will go through this soon. :smile:

**Comment by justinclift** [comment]
@progh2 Well done, this looks very good. :smile:

There is one small piece I'm not sure about.  In the "Edit Pragmas" tab in MainWindow.ui, some of the English strings seem to be untranslated.

If that's how they're supposed to be though, that's not a problem. :smile:

- [x] Menus

screen shot 2016-08-19 at 13 22 22
screen shot 2016-08-19 at 13 22 29
screen shot 2016-08-19 at 13 22 41
screen shot 2016-08-19 at 13 22 47
screen shot 2016-08-19 at 13 22 53
screen shot 2016-08-19 at 13 22 58
screen shot 2016-08-19 at 13 23 03
- [x] AboutDialog.ui
screen shot 2016-08-19 at 12 56 54
- [x] CipherDialog.ui
screen shot 2016-08-19 at 12 58 01
- [x] ColumnDisplayFormatDialog.ui

screen shot 2016-08-19 at 12 58 45
- [x] CreateIndexDialog.ui

screen shot 2016-08-19 at 12 59 20
- [x] EditDialog.ui

screen shot 2016-08-19 at 13 00 15
screen shot 2016-08-19 at 13 00 22
screen shot 2016-08-19 at 13 00 38
screen shot 2016-08-19 at 13 00 46

- [x] EditTableDialog.ui
screen shot 2016-08-19 at 13 02 21
- [x] ExportCsvDialog.ui
screen shot 2016-08-19 at 13 02 50
screen shot 2016-08-19 at 13 02 55
screen shot 2016-08-19 at 13 03 14
screen shot 2016-08-19 at 13 03 32

- [x] ExportSqlDialog.ui
screen shot 2016-08-19 at 13 04 20
screen shot 2016-08-19 at 13 04 25
- [x] ImportCsvDialog.ui

screen shot 2016-08-19 at 13 05 20
screen shot 2016-08-19 at 13 05 23
screen shot 2016-08-19 at 13 05 45
screen shot 2016-08-19 at 13 06 08
- [ ] MainWindow.ui
screen shot 2016-08-19 at 13 07 23
screen shot 2016-08-19 at 13 07 29
screen shot 2016-08-19 at 13 07 34
screen shot 2016-08-19 at 13 07 38
screen shot 2016-08-19 at 13 07 57
screen shot 2016-08-19 at 13 08 18
screen shot 2016-08-19 at 13 08 40
screen shot 2016-08-19 at 13 09 09
screen shot 2016-08-19 at 13 09 56

- [x] PreferencesDialog.ui
screen shot 2016-08-19 at 13 19 33
screen shot 2016-08-19 at 13 19 37
screen shot 2016-08-19 at 13 19 51
screen shot 2016-08-19 at 13 19 58
screen shot 2016-08-19 at 13 20 06
screen shot 2016-08-19 at 13 20 10
- [x] VacuumDialog.ui
screen shot 2016-08-19 at 13 21 06

**Comment by progh2** [comment]
oh... I'll edit strings and resend pull request soon~
your ui testing screenshot images are very usefull!!

2016. 8. 19. 오후 9:27에 "Justin Clift" <notifications@github.com>님이 작성:

@progh2 <https://github.com/progh2> Well done, this looks very good. 😄

There is one small piece I'm not sure about. In the "Edit Pragmas" tab in
MainWindow.ui, some of the English strings seem to be untranslated.

If that's how they're supposed to be though, that's not a problem. 😄

   - Menus

[image: screen shot 2016-08-19 at 13 22 22]
<https://cloud.githubusercontent.com/assets/406299/17809680/3c6d4f62-6610-11e6-9340-957661f4cc78.png>
[image: screen shot 2016-08-19 at 13 22 29]
<https://cloud.githubusercontent.com/assets/406299/17809677/3c697f54-6610-11e6-9d14-c0b62361d9a1.png>
[image: screen shot 2016-08-19 at 13 22 41]
<https://cloud.githubusercontent.com/assets/406299/17809679/3c6bd27c-6610-11e6-9de4-0e0252a682c4.png>
[image: screen shot 2016-08-19 at 13 22 47]
<https://cloud.githubusercontent.com/assets/406299/17809682/3c74e09c-6610-11e6-9902-fd005b215381.png>
[image: screen shot 2016-08-19 at 13 22 53]
<https://cloud.githubusercontent.com/assets/406299/17809678/3c6b3948-6610-11e6-9382-5710363b312f.png>
[image: screen shot 2016-08-19 at 13 22 58]
<https://cloud.githubusercontent.com/assets/406299/17809681/3c6ed576-6610-11e6-93c0-d795f1c86f5a.png>
[image: screen shot 2016-08-19 at 13 23 03]
<https://cloud.githubusercontent.com/assets/406299/17809683/3c842eee-6610-11e6-8f15-2731c6e5a940.png>

   - AboutDialog.ui [image: screen shot 2016-08-19 at 12 56 54]
   <https://cloud.githubusercontent.com/assets/406299/17809140/7c7fd8c6-660c-11e6-9c15-bacb0ec298f9.png>
   - CipherDialog.ui [image: screen shot 2016-08-19 at 12 58 01]
   <https://cloud.githubusercontent.com/assets/406299/17809154/951982ec-660c-11e6-90f4-532ed3c6277b.png>
   - ColumnDisplayFormatDialog.ui

[image: screen shot 2016-08-19 at 12 58 45]
<https://cloud.githubusercontent.com/assets/406299/17809182/b2c871fe-660c-11e6-8b0c-4fdad5d3de63.png>

   - CreateIndexDialog.ui

[image: screen shot 2016-08-19 at 12 59 20]
<https://cloud.githubusercontent.com/assets/406299/17809196/cf7d0666-660c-11e6-87a1-3e68515ae5ec.png>

   - EditDialog.ui

[image: screen shot 2016-08-19 at 13 00 15]
<https://cloud.githubusercontent.com/assets/406299/17809231/0d6463de-660d-11e6-947f-a373b2110d01.png>
[image: screen shot 2016-08-19 at 13 00 22]
<https://cloud.githubusercontent.com/assets/406299/17809234/0d6cccf4-660d-11e6-8911-9376e69c41f9.png>
[image: screen shot 2016-08-19 at 13 00 38]
<https://cloud.githubusercontent.com/assets/406299/17809232/0d68516a-660d-11e6-8abc-da83be750330.png>
[image: screen shot 2016-08-19 at 13 00 46]
<https://cloud.githubusercontent.com/assets/406299/17809233/0d6b1076-660d-11e6-8088-75ee4a9a872b.png>

   - EditTableDialog.ui [image: screen shot 2016-08-19 at 13 02 21]
   <https://cloud.githubusercontent.com/assets/406299/17809250/2bddcb0c-660d-11e6-99e6-5739dc10dac2.png>
   -

   ExportCsvDialog.ui
   [image: screen shot 2016-08-19 at 13 02 50]
   <https://cloud.githubusercontent.com/assets/406299/17809291/60c5e37c-660d-11e6-9fbf-258db2826cc6.png>
   [image: screen shot 2016-08-19 at 13 02 55]
   <https://cloud.githubusercontent.com/assets/406299/17809290/60c459ee-660d-11e6-88d7-4ed1ccca959c.png>
   [image: screen shot 2016-08-19 at 13 03 14]
   <https://cloud.githubusercontent.com/assets/406299/17809289/60c3eea0-660d-11e6-8be9-7ffe525da3b9.png>
   [image: screen shot 2016-08-19 at 13 03 32]
   <https://cloud.githubusercontent.com/assets/406299/17809288/60c37c36-660d-11e6-92bc-d7a201f7d604.png>
   -

   ExportSqlDialog.ui
   [image: screen shot 2016-08-19 at 13 04 20]
   <https://cloud.githubusercontent.com/assets/406299/17809301/8180cc8a-660d-11e6-9521-6518eb8ce34f.png>
   [image: screen shot 2016-08-19 at 13 04 25]
   <https://cloud.githubusercontent.com/assets/406299/17809302/81869048-660d-11e6-956b-57de35a0fb35.png>
   - ImportCsvDialog.ui

[image: screen shot 2016-08-19 at 13 05 20]
<https://cloud.githubusercontent.com/assets/406299/17809329/c41b1726-660d-11e6-9922-6901fb925fbe.png>
[image: screen shot 2016-08-19 at 13 05 23]
<https://cloud.githubusercontent.com/assets/406299/17809330/c41bf5b0-660d-11e6-9acf-a1343c106de9.png>
[image: screen shot 2016-08-19 at 13 05 45]
<https://cloud.githubusercontent.com/assets/406299/17809327/c419c024-660d-11e6-8214-68e764c8bfa5.png>
[image: screen shot 2016-08-19 at 13 06 08]
<https://cloud.githubusercontent.com/assets/406299/17809328/c41b2d2e-660d-11e6-9dea-611289878105.png>

   -

   MainWindow.ui
   [image: screen shot 2016-08-19 at 13 07 23]
   <https://cloud.githubusercontent.com/assets/406299/17809404/482ab328-660e-11e6-83ea-4eedae2ba2af.png>
   [image: screen shot 2016-08-19 at 13 07 29]
   <https://cloud.githubusercontent.com/assets/406299/17809405/482a8cd6-660e-11e6-89e8-69dbdfbe0614.png>
   [image: screen shot 2016-08-19 at 13 07 34]
   <https://cloud.githubusercontent.com/assets/406299/17809408/482fad60-660e-11e6-9201-3cc7430164f8.png>
   [image: screen shot 2016-08-19 at 13 07 38]
   <https://cloud.githubusercontent.com/assets/406299/17809403/482a99c4-660e-11e6-9bc4-45bb0c6d46f3.png>
   [image: screen shot 2016-08-19 at 13 07 57]
   <https://cloud.githubusercontent.com/assets/406299/17809406/482b6412-660e-11e6-8b73-68d911a9414b.png>
   [image: screen shot 2016-08-19 at 13 08 18]
   <https://cloud.githubusercontent.com/assets/406299/17809407/482cc6f4-660e-11e6-9a8b-ae61acffa811.png>
   [image: screen shot 2016-08-19 at 13 08 40]
   <https://cloud.githubusercontent.com/assets/406299/17809508/0801409a-660f-11e6-8a0a-bd0428651303.png>
   [image: screen shot 2016-08-19 at 13 09 09]
   <https://cloud.githubusercontent.com/assets/406299/17809514/1112a944-660f-11e6-8326-e2621b8a44a1.png>
   [image: screen shot 2016-08-19 at 13 09 56]
   <https://cloud.githubusercontent.com/assets/406299/17809513/1111dc80-660f-11e6-9315-06e64d4076f0.png>
   -

   PreferencesDialog.ui
   [image: screen shot 2016-08-19 at 13 19 33]
   <https://cloud.githubusercontent.com/assets/406299/17809612/b98d8e72-660f-11e6-8903-96acc4d5f85d.png>
   [image: screen shot 2016-08-19 at 13 19 37]
   <https://cloud.githubusercontent.com/assets/406299/17809616/b9958ea6-660f-11e6-89ae-3d074f1b9bd9.png>
   [image: screen shot 2016-08-19 at 13 19 51]
   <https://cloud.githubusercontent.com/assets/406299/17809614/b9907ad8-660f-11e6-856a-21317b04136c.png>
   [image: screen shot 2016-08-19 at 13 19 58]
   <https://cloud.githubusercontent.com/assets/406299/17809613/b98e9c36-660f-11e6-920b-94711c432f1d.png>
   [image: screen shot 2016-08-19 at 13 20 06]
   <https://cloud.githubusercontent.com/assets/406299/17809617/b99606d8-660f-11e6-95b6-b72e33149aea.png>
   [image: screen shot 2016-08-19 at 13 20 10]
   <https://cloud.githubusercontent.com/assets/406299/17809615/b99102fa-660f-11e6-8d21-50f16831de70.png>
   - VacuumDialog.ui [image: screen shot 2016-08-19 at 13 21 06]
   <https://cloud.githubusercontent.com/assets/406299/17809621/cc82a486-660f-11e6-91bc-774733a2ac6c.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sqlitebrowser/sqlitebrowser/pull/736#issuecomment-241005112>,
or mute the thread

**Comment by justinclift** [comment]
Excellent. 😁

**Comment by progh2** [comment]
:dart:

**Comment by justinclift** [comment]
Thanks @progh2. :smile:

Should I take screenshots again, or just merge this in?

**Comment by justinclift** [comment]
Hmmm, I'm going to merge this now.

@progh2 If something else needs changing or adjusting, further PR's are very welcome. :smile:

**Pull request merged**
