### PR TITLE
Updated spanish translation

### PR DESCRIPTION
**Pull request by lulol**
There you go, Justin. Have checked the new translations and didn't find any obvious error, but may need to see the compiled result to be sure. :)

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @lulol, I'll go through it now. :smile:

**Comment by justinclift** [comment]
Excellent, this looks very complete. :smile:

Only two queries with it, though I'm being picky with them. :wink:

* For ImportCsvDialog.ui, there is an & in the text which I'm unsure of.
* With the 4th screenshot for the Preferences dialog, one of the lines doesn't start with a capital letter, unlike the rest.  It kind of looks strange (to me).  But if it's meant to be that way, then no worries. 😀 

- [x] AboutDialog.ui
screen shot 2016-08-10 at 19 20 04
- [x] CipherDialog.ui
screen shot 2016-08-10 at 19 27 10
- [x] ColumnDisplayFormatDialog.ui
screen shot 2016-08-10 at 19 27 59
- [x] CreateIndexDialog.ui
screen shot 2016-08-10 at 19 28 46
- [x] EditDialog.ui
screen shot 2016-08-10 at 19 31 28
screen shot 2016-08-10 at 19 31 33
screen shot 2016-08-10 at 19 31 42
- [x] EditTableDialog.ui
screen shot 2016-08-10 at 19 29 36
- [x] ExportCsvDialog.ui
screen shot 2016-08-10 at 19 33 20
- [x] ExportSqlDialog.ui
screen shot 2016-08-10 at 19 34 32
- [x] ImportCsvDialog.ui
screen shot 2016-08-10 at 19 38 22
- [x] MainWindow.ui
screen shot 2016-08-10 at 19 08 18
screen shot 2016-08-10 at 19 08 25
screen shot 2016-08-10 at 19 08 39
screen shot 2016-08-10 at 19 08 52
- [ ] PreferencesDialog.ui
screen shot 2016-08-10 at 19 21 16
screen shot 2016-08-10 at 19 21 25
screen shot 2016-08-10 at 19 21 33
screen shot 2016-08-10 at 19 21 39
screen shot 2016-08-10 at 19 21 55
- [x] VacuumDialog.ui
screen shot 2016-08-10 at 19 20 44

**Comment by justinclift** [comment]
Also noticed a slightly different problem, which I'm not sure how to fix.  It almost seems like a Qt bug, as it's not a dialog we have layout control over.
screen shot 2016-08-10 at 19 37 56
As an idea, is there a shorter alternative for the words that might fit instead?

**Comment by lulol** [comment]
Thanks @justinclift for reviewing it and showing the screenshots, have been very helpful!

You are correct about these errors. Have fixed them:
- ../ImportCsvDialog.ui" line="230" removed spurious & that you found.
- ../PreferencesDialog.ui" line="637" corrected the bad capitalization that you found.

Also fixed:
- ../EditDialog.cpp line="460" swapped the parameter %1 order to the correct one.
- ../EditDialog.cpp line="480" removed spurious parameter %1.
- ../MainWindow.ui" line="1782" changed translation to be consistent.

but can't locate where that broken dialog is in the .ts file.
There is no _"Ficheros de"_ string (or substrings of) that I can find anywhere in the file. :/ Do you know in which line is defined?

Also in that same dialog the _"New Folder"_ and _"Cancel"_ buttons are not translated but _"Abrir"_ is, but can't find the source _"New Folder"_ text either.

**Comment by justinclift** [comment]
Awesome, will double check them, then merge (assuming no problems seen here).  Going to have food first though. :smile:

With the  _"Ficheros de"_ problem (and the others in the same dialog), it sounds like it could be a problem in Qt4 then.

I'll rebuild this with Qt5 in a bit, and see if they still show up the same.  If they do... I'll file a bug with the Qt project, and see if something useful turns up there. :smile:

**Comment by lulol** [comment]
Should I close this pull request and open a new one with the fixes?

**Comment by innermous** [comment]
@lulol why would you do that?
Make changes and force push. Or just add another commit to branch (I hope Justin will do squash merge :smile: )

**Comment by justinclift** [comment]
Heh Heh Heh

Yeah, I'll squash these into one commit.  I've learned my lesson about that. 😁

**Comment by justinclift** [comment]
Excellent stuff @lulol.  It's all good here, so merging now: :smile:
screen shot 2016-08-10 at 21 33 03
screen shot 2016-08-10 at 21 34 20

**Comment by justinclift** [comment]
@innermous Hey look... squashed commit! 😋

**Comment by justinclift** [comment]
When built using Qt5, the dialog doesn't have the _"Ficheros de"_ problem:
screen shot 2016-08-10 at 21 47 31

However, the buttons are untranslated.  They might be using up the system language (still English) rather than the DB4S language.  I'll try changing my system-wide language to Spanish later, and see what happens.

**Comment by justinclift** [comment]
The text on the buttons seems to be set from the system language.  When OSX is set to use Spanish as it's primary/default language, they seem ok:
screen shot 2016-08-10 at 22 01 48
Looks like we're in good shape after all. :smile:

**Comment by justinclift** [comment]
By the way, yesterday we created a "[Translators](https://github.com/orgs/sqlitebrowser/teams/translators)" team for the sqlitebrowser org here on GitHub.

It doesn't give write access to anything, but shows you're a "member of the team" for anyone that looks. :smile:

Any interest in being added to that?

**Comment by lulol** [comment]
Thanks, not me. I'm not seeking any credit but appreciate the offer very much.

Have updated the Spanish translation to fix some incoherences, hopefully all of them. Will be glad to review it before the new version is released to check for any new changes if needed.

Have not been able to find where to fix these shown in the screenshots:

Found these untranslated tooltips but can't locate where are the sources to translate them:
portapapeles01

Are the **Delete Table**, **Delete View** and **Delete Trigger** tooltips configured independently? Seems that all show the same tooltip set for Delete Table. Don't know if it's meant to be this way.
portapapeles02

**Comment by justinclift** [comment]
@lulol No worries at all about the Translators team thing.  Some people care about it, some don't.  And it doesn't hurt the project to give people the option. 😁 

With the untranslated tooltip problems, I'll take a look over the next few hours.  At a guess, they're probably strings embedded in our .ui files.  If that's the case... investigation for a fix will be needed.

The Delete table tooltip is hopefully something simpler.  Will find out too. :smile:

For the release itself, technically it could be done right now.  The code is in a decent state, and apart from the stuff you've just pointed out above :wink:, the translations seem in an ok place too.

People have been pointing out a few times recently, that having our releases "unsigned" throws up warnings for people downloading on Windows, and for people installing on OSX.  So, I submitted paperwork yesterday to get signing certificates.  As soon as they arrive (hopefully Monday/Tuesday), then we'll make the release.  With signed binaries. 😁

**Comment by lulol** [comment]
Cool! Good luck @justinclift with the certificates. Looking forward for it.

Guess that I wil need to generate a new pull request when these fixes are completed (and then translated)?

**Comment by justinclift** [comment]
Yeah. :smile:

**Comment by justinclift** [comment]
Oh, if possible, do the PR against the `v3.9.x` branch. The code in that will be used for the release.

**Comment by lulol** [comment]
Hmmm. Ok, I'll be sure of that, think that then I better start a new clone because the github webgui is a pain in the neck to sync branches and don't know how to rebase it.

**Comment by justinclift** [comment]
Sure.  It might be better timing though to wait until we know for sure why those bits aren't being translated.  It's fairly likely some of the code will need updating before you do a new PR.

So, forking after the code has been adjusted is probably the easiest approach. :smile:

**Comment by justinclift** [comment]
@lulol Sorry, I didn't get around to investigating this stuff today.  I got learning how to sign our builds on OSX, then updating our build system scripting to do it.

I'll try to get this done tomorrow instead. :smile:

**Comment by revolter** [comment]
@lulol, I often went back to [this answer] to sync a fork. I finally learned how to do it, but after 20-30 visits on that page.

  [1]: http://stackoverflow.com/a/7244456/865175

**Comment by justinclift** [comment]
@lulol Looking at this now.

> Are the Delete Table, Delete View and Delete Trigger tooltips configured independently? Seems that all show the same tooltip set for Delete Table. Don't know if it's meant to be this way.

Yeah, that doesn't sound good.

The `Delete Table` tooltip is defined here:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/v3.9.x/src/MainWindow.ui#L1556

And yeah, it looks like that doesn't get updated even when something other than a table is selected.  The corresponding (non-tooltip) text which **does** change, seems to be this:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/v3.9.x/src/MainWindow.cpp#L1212-L1219

That can be updated to change the tooltip text at the same time.  They should allow translation for those ones. :smile:

--

The "Close Tab" one is proving to be more tricky.  I'm not finding the source of those words either... still looking though.

**Comment by justinclift** [comment]
The `Delete Table` tooltip problem should be fixed in this: https://github.com/sqlitebrowser/sqlitebrowser/commit/7c5f8743199137af594c685de6b7b860155b474c

The `Execute current line` one, I think it my fault.  I changed the tooltip a few days ago... but forgot to generate a new.ts file. 😦 

* https://github.com/sqlitebrowser/sqlitebrowser/blob/7c5f8743199137af594c685de6b7b860155b474c/src/MainWindow.ui#L1737

I'm still looking for the cause of the `Close Tab` one.

**Comment by justinclift** [comment]
While we're at it, there are a few other tooltips which need updating anyway: #721

I was going to put that off until the 3.10.0 release, but it might be better to make that change right away.

Thoughts?

**Comment by lulol** [comment]
@justinclift I'll be glad to provide the Spanish translations for 3.9.0 as soon as needed if there is some hurry to release.

Now it shouldn't take me more than 10 minutes once the new .ts are ready if you let me know. I will just fork the new v3.9.x branch, update and generate the pull request including these.

If the other translations are also complete and the release won't get delayed updating them then why not fix all them? On the other hand, a cosmetic fix like this for just one translation probably won't justify much a long delay if new features are available with this release.

About the "Close Tab", if can't be found in the sources then may be is a Qt tooltip? There are also some other untranslated "Cancel" buttons (i.e. in the import/export dialogs) that seems to be the case.

**Comment by lulol** [comment]
@revolter yeah, with a local copy is fine, but I was using the github webgui that apparently doesn't supoort it and the known way is generating a "reverse" pull request, that even if it works and gets the code in sync it makes a mess with the timelines for future pull requests.

**Comment by justinclift** [comment]
@lulol Thanks. :smile:

For the 3.9.0 release, I'm mostly waiting on the security certificate to come through from StartCom.  Was kind of expecting it to arrive this morning... but haven't heard from there.  (have sent messages, no response)

In the meantime, it makes sense to do some extra "polishing" through small-ish tasks that should break anything. :wink:

With the "Close Tab" string... yeah, it's definitely not in our source code.  Looking through the Qt5 source code, this seems to be it:

* https://github.com/qt/qtbase/blob/0b9acb3e320b39f159c7638cb89f92017b4e91da/src/widgets/widgets/qtabbar.cpp#L2587

It's enclosed with `tr()`, so it should be translatable.  As a complete wild guess, it might be the Spanish translation hasn't been submitted to upstream Qt for that.

**Comment by justinclift** [comment]
Looking here, there doesn't seem to be a Spanish translation file for "qtbase" (the base Qt5 widgets):

* https://github.com/qt/qttranslations/tree/dev/translations

This seems to be the Qt4 equivalent:

* https://github.com/qt/qttranslations/blob/dev/translations/qt_es.ts#L60-L67

`Close Tab`isn't translated in this one either. 😦 

Technically it would be possible for us to compile Qt5 ourselves, including updated Spanish translation for those missing pieces.  Compiling Qt5 isn't something I've personally tried though (it has a reputation for being painful)... so... I'm thinking lets skip this for now. :wink:

If you have the time + interest to translate the missing terms in Qt itself, they'd likely welcome it.  And our future releases wouldn't have this particular problem. 😁

**Comment by lulol** [comment]
I'm not sure to be prepared to deal with the responsability of translating the Qt5 widgets being such a high impact project and not being a heavy user to understand the exact right context for them. :fearful:

I'll take a look at the 644 unfinished terms of Qt4 to see if are straightforward to translate but not sure if it's going to be a bit of wasted work to translate an old version.

Anyway seems that sqlitebrowser is very minimally affected by them to justify compiling Qt5. :wink:

**Comment by justinclift** [comment]
Yeah, apparently there aren't going to be any more new Qt4 point releases, so that would probably not be a productive use of time. :wink:

**Comment by revolter** [comment]
@lulol, Probably it will be better for a Spanish translation for Qt to exist, even if not perfect, than not exist at all. I say you can help them translate if you want, without any fear.

**Comment by justinclift** [comment]
@lulol Just now pushed a new commit to the `v3.9.x` branch, containing regenerated .ts file for all languages: https://github.com/sqlitebrowser/sqlitebrowser/blob/v3.9.x/src/translations/sqlb_es_ES.ts

If you want to adjust the last few things, the updated file might be useful to grab.

Btw, in theory I should be able to sign the Windows executables tomorrow.  Once I've figured the process out properly, I'll do the final `3.9.0` release with whatever translations are ready at the time. :smile:

**Comment by lulol** [comment]
Cool! Looking forward to it.

Just issued a pull request completing the missing translations. :smile:

**Comment by justinclift** [comment]
Fantastic @lulol, thank you. :smile:

**Comment by lulol** [comment]
@revolter well, not sure of that, literal translations of short terms lacking the proper context can be very confusing and become even annoying.

Let me check this weekend the ts source files for how many lines actually need to be translated for Qt5.
Seems that a lot since all but qt_es.ts are missing their Spanish translation. It may take me weeks and a few iterations to complete these, and I'm not sure what I'm getting into.

**Comment by justinclift** [comment]
@lulol Yeah, it's one of those tasks that sounds big enough to be literally worrying.

Possibly a weird question, but if you know any other people who do Spanish translation, maybe it's a thing for discussion and spreading the effort out among a few people?

**Comment by justinclift** [comment]
@lulol Found this while waiting for some stuff to compile:

&nbsp; &nbsp; https://wiki.qt.io/Qt_Localization

They have .ts files generated daily, available for download here:

&nbsp; &nbsp; http://l10n-files.qt.io/l10n-files/

Maybe the correct approach is to only do the strings you're sure of, and let someone else do the one's you're not sure of?

**Comment by lulol** [comment]
Have been checking those Qt links, the documentation and all the Spanish .ts files.
Seems that most of the current translations are already imported from the old Qt4 version but tagged "unfinished" even if also half of them are new terms still untranslated.

So for Qt5 is more about first enabling each term than translating them. And that would requiere to be able to verify the proper context uses for each one. It's difficult to be sure otherwise and will be more work later to fix.

Not developing with Qt to see the results and getting feedback unfortunately I'll be unable to do that. :(

**Comment by justinclift** [comment]
No worries @lulol.  Thank you for taking the time to investigate this deeply. :smile:

**Comment by lulol** [comment]
@justinclift for some reason there are a couple of already translated terms that previouly were displayed correctly in the Nightly builds that in Nightly build 20160828_0218 are untranslated as shown in the capture below. Have checked both v3.9.x and master branches and seems to be correctly translated though.

Don't know if that affected the v3.9.0 release as I couldn't check it.

nightly build 3 9 99_20160828_0218

**Comment by justinclift** [comment]
Interesting.  I can check 3.9.0 on Windows pretty quickly, as I have that VM already running.

Looking now.

**Comment by justinclift** [comment]
The 3.9.0 release seems ok, which is a relief. :smile:

3 9 0 spanish translation check

The problem can likely be mostly ignored for now then, as it'll just be in the nightly builds.  When we're closer to the next release, we can update the translations to 100% again in time for that. :smile:

That being said... if you do feel like translation strings which are on the `master` branch, then we'll definitely accept them. 😀

**Comment by lulol** [comment]
Awesome! I'm glad that all went well with the release! :smile: 

Have translated the unfinished terms from the master branch but only could find 4 of them.

Does it worth to make a pull request now for such a minimal update or better wait for something more substantial?

**Comment by justinclift** [comment]
Hmmm, we can do it now.  It's simple to merge in after all.

That'll mean the nightly builds are more accurate until the next release anyway. :smile:

**Comment by lulol** [comment]
Done. :smile:

**Comment by justinclift** [comment]
Thanks @lulol, that's great. :smile:

As soon as Travis gives it the green light, I'll merge it in.

**Comment by lulol** [comment]
Hmm. It failed. Seems that didn't like the &oacute; html entity in the html text. Using utf-8 directly that worked for other terms.

**Pull request merged**
