### PR TITLE
Updated Turkish Translation for 3.9.1

### PR DESCRIPTION
**Pull request by firateski**

### CODE REVIEW

**Comment by justinclift** [comment]
Awesome @firateski. :smile:

Do you want me to take screenshots, so you can verify things before it gets merged?

**Comment by firateski** [comment]
Yes of course. I'm waiting for screenshot 😄  @justinclift

**Comment by justinclift** [comment]
Ok, give me a few minutes. :smile:

**Comment by justinclift** [comment]
Here's the output of the `--help` option:

```bash
$ DB\ Browser\ for\ SQLite --help
DB Browser for SQLite [options] [db] 
Muhtemel komut satırı argümanları: 
  -h, --help		Komut satırı seçeneklerini göster 
  -s, --sql [file]	Veri tabanını açtıktan sonra bu SQL dosyasını işle 
  -t, --table [table]	Veri tabanını açtıktan sonra bu tabloyu görüntüle 
  -q, --quit		Scriptleri çalıştırdıktan sonra programı kapat 
  [file]		SQLite veritabanını aç
```
Screenshots (ordered similar to the changes in this PR):

screen shot 2016-10-06 at 16 27 27
screen shot 2016-10-06 at 16 27 40
screen shot 2016-10-06 at 16 29 02
screen shot 2016-10-06 at 16 29 06
screen shot 2016-10-06 at 16 30 00
screen shot 2016-10-06 at 16 30 18
screen shot 2016-10-06 at 16 30 43
screen shot 2016-10-06 at 16 31 32
screen shot 2016-10-06 at 16 35 50
screen shot 2016-10-06 at 16 36 45
screen shot 2016-10-06 at 16 37 17
screen shot 2016-10-06 at 16 37 39
screen shot 2016-10-06 at 16 39 15
screen shot 2016-10-06 at 16 40 42
screen shot 2016-10-06 at 16 41 24
screen shot 2016-10-06 at 16 42 14
screen shot 2016-10-06 at 16 42 59
screen shot 2016-10-06 at 16 43 40
screen shot 2016-10-06 at 16 50 49
screen shot 2016-10-06 at 16 51 07
screen shot 2016-10-06 at 16 51 27
screen shot 2016-10-06 at 16 51 34
screen shot 2016-10-06 at 16 51 56
screen shot 2016-10-06 at 16 52 02
screen shot 2016-10-06 at 16 54 27
screen shot 2016-10-06 at 16 55 13
screen shot 2016-10-06 at 16 55 53
screen shot 2016-10-06 at 16 56 15
screen shot 2016-10-06 at 16 56 28
screen shot 2016-10-06 at 16 57 20
screen shot 2016-10-06 at 16 58 09
screen shot 2016-10-06 at 16 58 25
screen shot 2016-10-06 at 16 58 40
screen shot 2016-10-06 at 16 58 55
screen shot 2016-10-06 at 16 59 48

I **think** all of the main changes are there. :smile:

**Comment by justinclift** [comment]
Cool.  More screenshots needed, or should this be merged, or ? :smile:

**Comment by firateski** [comment]
Thanks for screenshots 😄 They were very helpful to find problems and fix them. @justinclift 

I think should be merged 😄

**Comment by justinclift** [comment]
Thanks @firateski, merged.

And yeah, screenshots do seem to be useful.  Easily worth the time/effort needed for me to take them. :smile:

**Pull request merged**
