### PR TITLE
Updated Italian translation

### PR DESCRIPTION
**Pull request by GortiZ6**
Hello, I've updated the Italian translation to master

### CODE REVIEW

**Comment by GortiZ6** [comment]
I don't understand the conflicts... If I diff the two files they differ only for the new-line style and the translations 🫨 Let me know if you need me to do something to fix it.

**Comment by lucydodo** [comment]
Thank you for contribution. Don't worry, I'll take a look at it. :)

**Comment by lucydodo** [comment]
I've resolved the conflict and merged them, thank you!

**Comment by justinclift** [comment]
Oh, it looks like at least some of our dependent libraries got translated by @GortiZ6 too?

Doing a super quick skim now, it's showing at least qscintilla strings have been translated as well.

Wonder if those would be useful to the upstream qscintilla project?

**Comment by mgrojo** [comment]
> Wonder if those would be useful to the upstream qscintilla project?

Indeed. There are some translation files in `libs/qscintilla/Qt4Qt5/qscintilla_*.ts` coming from upstream, and Italian is not among them.

**Comment by justinclift** [comment]
Ahhh yeah.  The QScintilla project, I remember that one.

Does anyone have time the spare time/interest to deal with them, to potentially contribute the updated translation files?

**Comment by GortiZ6** [comment]
Gh! I had a look at the qScintilla project 🤦‍♂️ Contribute to them seems quite more complicate...

**Pull request merged**
