### PR TITLE
Create watsap

### PR DESCRIPTION
**Pull request by questwire**

### CODE REVIEW

**Comment by justinclift** [comment]
Umm.... what does a `watsap` file do?

**Comment by lucydodo** [comment]
Thank you for your interest in the our project! But what is `watsap`? I've been googled, but I'm not sure. :-(

**Comment by scottfurry** [comment]
I think they mean "https://web.whatsapp.com/"
This sounds like spam. Recommend close.

**Comment by lucydodo** [comment]
OK. so, I will close this issue.
@questwire If you have any disagreements, you can reopen this request and leave a comment anytime.

**Pull request closed without merging**
