### PR TITLE
update Chinese translation

### PR DESCRIPTION
**Pull request by bssthu**
I haven't tested it because my qt crashed. Can you test it? Thank you!

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @bssthu.  Yep, I can do that.  It'll probably be tomorrow though. :smile:

**Comment by justinclift** [comment]
This looks really good @bssthu, thank you. :smile:

Do you want me to make screenshots of everything before merging this, so you can see the translated strings when running?

**Comment by bssthu** [comment]
That would be great, thank you.

**Comment by justinclift** [comment]
Awesome, I'll probably get started on it tomorrow morning. :smile:

**Comment by justinclift** [comment]
@bssthu Sorry, but I need to delay this until tonight.  Other higher urgency stuff has since come up which I need to get done first. :smile:

**Comment by justinclift** [comment]
**... in progress ...**

---

 * [x] Output for the `help` option:

```
用法: src/DB Browser for SQLite.app/Contents/MacOS/DB Browser for SQLite [选项] [数据库]

可用命令行参数:
  -h, --help		显示命令行选项
  -q, --quit		在运行脚本后退出应用程序
  -s, --sql [文件]	在打开数据库后执行此 SQL 文件
  -t, --table [表]	在打开数据库后浏览此表
  -v, --version		显示当前版本
  [文件]		打开这个 SQLite 数据库
```

## Screenshots

- [x] Menus

screen shot 2017-08-15 at 21 29 03
screen shot 2017-08-15 at 21 29 15
screen shot 2017-08-15 at 21 29 24
screen shot 2017-08-15 at 21 29 30
screen shot 2017-08-15 at 21 29 37
screen shot 2017-08-15 at 21 29 42
screen shot 2017-08-15 at 21 29 47

- [x] AboutDialog.ui
screen shot 2017-08-15 at 21 31 22
- [x] CipherDialog.ui
screen shot 2017-08-15 at 21 32 57
screen shot 2017-08-15 at 21 33 00
screen shot 2017-08-15 at 21 33 15
screen shot 2017-08-15 at 21 33 20


- [x] ColumnDisplayFormatDialog.ui
screen shot 2017-08-15 at 21 34 43
screen shot 2017-08-15 at 21 34 50


- [x] CreateIndexDialog.ui
screen shot 2017-08-15 at 21 37 02
screen shot 2017-08-15 at 21 36 25
screen shot 2017-08-15 at 21 36 51


- [ ] EditDialog.ui
screen shot 2017-08-15 at 21 38 29
screen shot 2017-08-15 at 21 38 43
screen shot 2017-08-15 at 21 38 51
screen shot 2017-08-15 at 21 38 56
screen shot 2017-08-15 at 21 39 01
screen shot 2017-08-15 at 21 39 05


- [x] EditTableDialog.ui
screen shot 2017-08-15 at 21 40 48
screen shot 2017-08-15 at 21 40 54
screen shot 2017-08-15 at 21 40 59
screen shot 2017-08-15 at 21 41 16


- [ ] ExportCsvDialog.ui

- [ ] ExportSqlDialog.ui

- [ ] Export JSON

- [ ] ImportCsvDialog.ui

- [ ] MainWindow.ui

  * [ ] Database structure

  * [ ] Browse Data

  * [ ] Edit Pragmas

  * [ ] Execute SQL

- [ ] Panels

  * [ ] SQL
  
  * [ ] Plot
  
  * [ ] Database Schema
  
  * [ ] Remote
  
- [ ] PreferencesDialog.ui

- [ ] VacuumDialog.ui

**Comment by justinclift** [comment]
I think that's screenshots for everything.  To me, it all looks good apart from the strings in the new "Push database" dialog still being in English.  That's not surprising though, as we only added it a few days ago.

If you're happy with this PR as it is, then I'm happy to merge it in.  Otherwise, just update the PR and tell me when to. :smile:

For the English strings in the "Push database" dialog, once this PR is merged I can update the strings into a new sqlb_zh.ts file, so you can get those done as well.  If that's ok? :smile:

**Comment by bssthu** [comment]
Thank you. I think this PR is ok. I'll edit the English texts later.😄

**Comment by justinclift** [comment]
Awesome, thanks @bssthu. :smile:

I've just updated the translation source files again, so the new strings in it are ready whenever you are.  There should only be around 10 of them to do. :smile:

**Pull request merged**
