### PR TITLE
Update Arabic Translation

### PR DESCRIPTION
**Pull request by SafaAlfulaij**
I've changed the language from `ar_SA` (which is wrong) to `ar`
I think we can leave the flag as it is for now.

### CODE REVIEW

**Comment by justinclift** [comment]
Awesome, I'll give this a try here now. :smile:

**Comment by justinclift** [comment]
Four strings on the main window seem untranslated:
screen shot 2016-08-05 at 18 46 01
It's most likely because I removed the "&amp;amp;" substring inside them just a few commits ago.  They didn't seem to be doing anything useful, instead making the lives of translators more difficult.

I can put them back (the "&amp;amp;") if that was an incorrect thing to do?

**Comment by justinclift** [comment]
Looking through the dialogs now:

- [x] AboutDialog.ui
screen shot 2016-08-05 at 18 51 48
- [x] CipherDialog.ui
screen shot 2016-08-05 at 18 52 21
- [x] ColumnDisplayFormatDialog.ui
screen shot 2016-08-05 at 18 53 54
- [x] CreateIndexDialog.ui
screen shot 2016-08-05 at 18 54 29

- [x] EditDialog.ui
screen shot 2016-08-05 at 18 55 08

- [x] EditTableDialog.ui
screen shot 2016-08-05 at 18 55 59
- [x] ExportCsvDialog.ui
screen shot 2016-08-05 at 18 57 52
- [x] ExportSqlDialog.ui
screen shot 2016-08-05 at 18 58 39
- [ ] ImportCsvDialog.ui - **Something seems incorrect here, as the filters are no longer working.  Needs investigation**
- [ ] MainWindow.ui
screen shot 2016-08-05 at 18 46 01
- [x] PreferencesDialog.ui
screen shot 2016-08-05 at 19 01 12
screen shot 2016-08-05 at 19 01 17
screen shot 2016-08-05 at 19 01 21
screen shot 2016-08-05 at 19 01 25
screen shot 2016-08-05 at 19 01 28
- [x] VacuumDialog.ui
screen shot 2016-08-05 at 19 02 20

**Comment by justinclift** [comment]
Trying it now. :smile:

**Comment by justinclift** [comment]
Thanks @SafaAlfulaij, that's perfect! 😁  👍

**Comment by chrisjlocke** [comment]
Don't forget the dialogs are just 10% of the translations.  The application throws up messages, etc, which also need to be translated, otherwise, its just a 'bodge job'.  It would be 'weird' having an application where you can select a language so the GUI changes, only for it to throw up a message ("Are you sure?") which you can't read...  and then the "Yes" and "No" are in the CORRECT languages..... argh!

**Comment by justinclift** [comment]
Sure, that's completely correct.  With Issue #643, we'll get the UI elements in each of the languages matched up to their existing translations.

Once we have 3.9.0 code frozen (should be soon - definitely next few days), we can then reach out to the individual translators for string updates.  That will solve the problem properly. :smile:

**Comment by justinclift** [comment]
@SafaAlfulaij The newest commit has added two new lines of text, both of which could be seen fairly often by users.  Would you be ok to translate them to Arabic?

* https://github.com/sqlitebrowser/sqlitebrowser/blob/a63da56a0d8a3bc4176ee8db063c6cdc5325e74d/src/EditDialog.cpp#L191
* https://github.com/sqlitebrowser/sqlitebrowser/blob/a63da56a0d8a3bc4176ee8db063c6cdc5325e74d/src/EditDialog.cpp#L219

**Pull request merged**
