### PR TITLE
Korean translation

### PR DESCRIPTION
**Pull request by progh2**
Thank you for waiting. =)

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @progh2, that's Awesome. :smile:

Looking through the diff now, it seems very complete.  Do you reckon it's ok to merge "as is" or should I take screenshots of everything first so you can look at them before it's merged? :smile:

**Comment by progh2** [comment]
Please take screenshots..
In this case, I need to take a look at the screenshots.  ;D

**Comment by justinclift** [comment]
Will do.  It will probably be several hours from now (late tonight UK time) as I'm focused on other stuff right at the moment.  Writing SQL queries and stuff at the moment... :smile:

**Comment by justinclift** [comment]
Sorry @progh2, haven't gotten this done yet.  Need sleep.

I'll get the screenshots done tomorrow. :smile:

**Comment by justinclift** [comment]
**... in progress ...**

---

 * [ ] Output for the `help` option:

```
```

## Screenshots

- [ ] Menus

- [ ] AboutDialog.ui

- [ ] CipherDialog.ui

- [ ] ColumnDisplayFormatDialog.ui

- [ ] CreateIndexDialog.ui

- [ ] EditDialog.ui

- [ ] EditTableDialog.ui

- [ ] ExportCsvDialog.ui

- [ ] ExportSqlDialog.ui

- [ ] Export JSON

- [ ] ImportCsvDialog.ui

- [ ] MainWindow.ui

  * [ ] Database structure

  * [ ] Browse Data

  * [ ] Edit Pragmas

  * [ ] Execute SQL

- [ ] Panels

- [ ] PreferencesDialog.ui

- [ ] VacuumDialog.ui

**Comment by progh2** [comment]
Okay.
I am editing now.

**Comment by progh2** [comment]
I fixed the bug (*.sql vs. *.cvs).
I also modified below things.

```
- "Pretty print" in the "Export JSON" dialog is still in English.
- Some items in the "Plot" panel seem to be English.
```
--> Many people often use it as an english word but translate it. 

```
- The upload/push dialog in the Remote panel is still in English.
  - We also changed that whole dialog again yesterday (sorry), so it will be out of date for all translations. It was an important change though, so needed to be done.
```
--> I can not find that phrase. Not yet applied to translation files? If I can see that, I'will translate it.

**Comment by justinclift** [comment]
> I can not find that phrase. Not yet applied to translation files? If I can see that, I'will translate it.

Oops.  Yep, my fault.  I'll merge this PR now, then update the sqlb_ko_KR.ts file again.  In theory, the only things which should change will be the bits for the Remote panel. :smile:

**Comment by justinclift** [comment]
I've just updated the source strings into a version [sqlb_ko_KR.ts](https://github.com/sqlitebrowser/sqlitebrowser/raw/master/src/translations/sqlb_ko_KR.ts) file.

These seem like the only real changes: :smile:

* https://github.com/sqlitebrowser/sqlitebrowser/blob/a8b62dd7684faac7e5b5f540b19be345862ac23e/src/translations/sqlb_ko_KR.ts#L2871-L2872
* https://github.com/sqlitebrowser/sqlitebrowser/blob/a8b62dd7684faac7e5b5f540b19be345862ac23e/src/translations/sqlb_ko_KR.ts#L3810-L3812
* https://github.com/sqlitebrowser/sqlitebrowser/blob/a8b62dd7684faac7e5b5f540b19be345862ac23e/src/translations/sqlb_ko_KR.ts#L3847-L3899

**Pull request merged**
