### PR TITLE
Revised CHANGELOG file

### PR DESCRIPTION
**Pull request by richb-hanover**
See the commit message and #3334

### CODE REVIEW

**Review by lucydodo — APPROVED** [review]

**Comment by lucydodo** [comment]
LGTM. Thank you for hard work, it has been merged. :)

**Comment by richb-hanover** [comment]
@lucydodo @justinclift Good news/bad news...

The good news is that the CHANGELOG has been updated.

The bad news is that the changes I included only went up to November 2023 or so... 

I wasn't sure which of the other commits (from November to date) have gone into 3.13, so those need to be incorporated.

**Comment by lucydodo** [comment]
@richb-hanover Don't worry, we'll take a look at it.
You can also check out the commits that are planned for inclusion in 3.13.x version with the command:
`$ git log v3.13.x --since=2023-12-01 --oneline`

**Comment by richb-hanover** [comment]
Thanks! For my own information (I don't use `git` from the command line a lot...), the command is:

```
git tag  # get a list of all tags
git log v3.13.0-rc3 --since=2023-12-01 --oneline
```

**Pull request merged**
