### PR TITLE
resize multiple (selected) cols in Browse Data tab

### PR DESCRIPTION
**Pull request by schdub**
#241

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @schdub. :smile:

@rp- What do you think?

**Comment by rp-** [comment]
it works, but it is pretty slow. I guess this is as you already commment from the emitting of signals.
guess we should block emitting here.

btw. you don't have to wait until we merged a pull request, you can do any number of different pull requests, just create a new branch, to separate the feature you are working on.

**Comment by schdub** [comment]
@rp-, just updated my commit, please check if you have time.

I've no idea what's wrong with Travis (connection timed out error):
https://travis-ci.org/sqlitebrowser/sqlitebrowser/jobs/59045641

**Comment by justinclift** [comment]
It looks like an infrastructure problem with the Travis CI servers.  Hopefully it's only a very temporary thing. :smile:

**Comment by rp-** [comment]
hm ok it only slightly improved, but i think its just slow because my test table has a few thousand entries.
I'm just wondering why it is super fast if I only resize 1 column its pretty fast, but if I resize 2 it gets sluggish and more than 2 gets slow to very slow.

I read a bit on the topic and it seems, QTableView is slow by itself on this regard, so not much we can do about that. So maybe we switch to you previous implementation which seemed a bit simpler?

sorry for the inconvience

**Comment by rp-** [comment]
I meant your previous implementation, without the signal blocking? or did you wipe it? then we will just go with this.

**Comment by justinclift** [comment]
It's still viewable [here](https://github.com/sqlitebrowser/sqlitebrowser/commit/d494979893978d4d8477a58914e7fa54e9a85392), if that helps.

**Comment by justinclift** [comment]
@schdub Are we ok to still use the original one you made? :smile:

**Comment by schdub** [comment]
@justinclift , sorry, but I haven't the original fix.
I'm sure that your community is able to solve this issue without my help.
Pull-request is closed.

**Comment by rp-** [comment]
merged anyway

**Comment by justinclift** [comment]
@schdub Thanks.  We still had your original fix, so we have used that. :smile:

**Pull request closed without merging**
