### PR TITLE
UPDATE Russian translation

### PR DESCRIPTION
**Pull request by schdub**

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @schdub, that looks good for the master branch. :smile:

Do you have time to do the translation for the v3.9.1 branch too?

**Comment by innermous** [comment]
Spaseebo!

**Comment by justinclift** [comment]
I guess that mean "Oops"? :smile:

**Comment by revolter** [comment]
No, it means "Thank you"

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by justinclift** [comment]
Just copied and pasted the changes to v3.9.x branch: https://github.com/sqlitebrowser/sqlitebrowser/commit/d95f9aa4095fa2d863f2d78b63db05858365c80f :smile:

**Pull request merged**
