### PR TITLE
Use dnf to install Fedora dependencies

### PR DESCRIPTION
**Pull request by FreedomBen**

### CODE REVIEW

**Comment by justinclift** [comment]
Ahhh, good thinking.  Merged. :smile:

**Comment by justinclift** [comment]
Hmmm, actually, thinking about it more this is probably wrong.  The heading for that section shows it's for both CentOS & Fedora.

CentOS doesn't use dnf, so now the command is wrong. 😦 

Thoughts?

**Comment by FreedomBen** [comment]
yeah that's a good point.  How about something like #587 ?

**Comment by justinclift** [comment]
Yep, that works.  Merged too. 😀 

Thank you.

**Pull request merged**
