### PR TITLE
Add Windows XP support

### PR DESCRIPTION
**Pull request by karim**
Change the default subsystem used by MSVC linker to allow DB4S to run on Windows XP (32-bit and 64-bit).

See issues #893, #986, and #1010.

### CODE REVIEW

**Comment by justinclift** [comment]
Looks good to me.  We should probably get someone with an actual XP box to verify it first, just to be on the safe side.

**Comment by justinclift** [comment]
Aha, found one of my old MSDN XP ISO's.  No idea if it'll work, but I'll try running it up on a box here and see what happens. :smile:

**Comment by karim** [comment]
Good luck. 😄

**Comment by justinclift** [comment]
Got stuck on the Product Key bit.  I have one (a sticker on real hardware locally), but don't want to blow it on just a temporary test thing.

The [comment by @h1618](https://github.com/sqlitebrowser/sqlitebrowser/issues/1010#issuecomment-301123558) makes this PR look good though, so I'll merge this now.  We'll just need to make sure our nightly builds for XP are on a system with Qt 5.6.x (maximum) on it.

**Comment by karim** [comment]
Thanks. 😄 

Yes, Qt 5.6 should work... at least until [March 2019](http://blog.qt.io/blog/2016/04/21/qt-5-7-beta-released/#comment-1197572).

**Pull request merged**
