### PR TITLE
Shadowed Variable Warnings

### PR DESCRIPTION
**Pull request by scottfurry**
Compile with ALL_WARNINGS using GCC 8.2.1.
Encountered approximately dozen warnings with this pattern:

    [path to sqlitebrowser root]/src/[somesourcefile]:line:cursor: warning: declaration
	of ‘data’ shadows a member of ‘ClassName’ [-Wshadow]
            OtherDataType data = ....line of code at line given above...
                                     ^~~~
    In file included from /usr/include/qt5/QtWidgets/qdialog.h:44,
                            from /usr/include/qt5/QtWidgets/QDialog:1,
                           ...other sources in project
    /usr/include/qt5/QtWidgets/qwidget.h:733:18: note: shadowed declaration is here
         QWidgetData *data;
                                 ^~~~

It appears there is a variable named 'data' within Qt global scope. Using 'data'
as a variable name, even one limited in scope to small lamda expressions, causes
compiler some grief and results in message similar to above.

Commit resolves the warnings in affected files. No problems apparent during execution.
Requires CSV stress-testing.

### CODE REVIEW

**Comment by scottfurry** [comment]
Warnings resolved w/ GCC 8.2.1 and Clang 7.0.0

**Comment by MKleusberg** [comment]
Thanks, @scottfurry! I will probably review this tomorrow or the day after tomorrow.

> It appears there is a variable named 'data' within Qt global scope.

I think the problem here is that many Qt classes have a member function called ```data()``` and it's this member function we're shadowing. So there's no global variable but since so much code is in classes derived from Qt classes, it's very likely to have a ```data()``` function around.

**Comment by scottfurry** [comment]
@MKleusberg 
There warnings all look like this...
```
[proj root]/src/EditDialog.cpp: In member function ‘void EditDialog::loadData(const QByteArray&)’:
[proj root]/src/EditDialog.cpp:114:49: warning: declaration of ‘data’ shadows a member of ‘EditDialog’ [-Wshadow]
 void EditDialog::loadData(const QByteArray& data)
                                                 ^
In file included from /usr/include/qt5/QtWidgets/qdialog.h:44,
                 from /usr/include/qt5/QtWidgets/QDialog:1,
                 from [proj root]/src/EditDialog.h:4,
                 from [proj root]/src/EditDialog.cpp:1:
/usr/include/qt5/QtWidgets/qwidget.h:733:18: note: shadowed declaration is here
     QWidgetData *data;
                  ^~~~
[proj root]/src/EditDialog.cpp: In member function ‘void EditDialog::setDataInBuffer(const QByteArray&, EditDialog::DataSources)’:
[proj root]/src/EditDialog.cpp:552:76: warning: declaration of ‘data’ shadows a member of ‘EditDialog’ [-Wshadow]
 void EditDialog::setDataInBuffer(const QByteArray& data, DataSources source)
                                                                            ^
In file included from /usr/include/qt5/QtWidgets/qdialog.h:44,
                 from /usr/include/qt5/QtWidgets/QDialog:1,
                 from [proj root]/src/EditDialog.h:4,
                 from [proj root]/src/EditDialog.cpp:1:
/usr/include/qt5/QtWidgets/qwidget.h:733:18: note: shadowed declaration is here
     QWidgetData *data;
                  ^~~~
```

All pointing back to a QWidgetData pointer named `data`.

**Comment by MKleusberg** [comment]
Huh. You're right. It's strange because the ```data``` member which Qt adds is private, so it can't be accessed anyway and therefore I don't yet see how it can be shadowed.

Anyway, I'll resolve the merge conflict in a second and merge your changes :smile:

**Pull request merged**
