### PR TITLE
Updated Spanish translation

### PR DESCRIPTION
**Pull request by lulol**
PR against master. Translated missing terms and adjusted some for consistency.

Also seems that there are some weirdness in the original english source that I don't understand:

- line="269"   <source>Find previous match with mapping</source> (wrapping?)
- line="2069" <source>Could not open find resource file: %1</source> (open/find)

The diff shows that there was a change at line="653" when the original was modified after the fact and needs fixing/merging.

### CODE REVIEW

**Comment by justinclift** [comment]
Weirdly, this .ts file is breaking the compile.  The error message seems to be about a missing closing tag:

https://travis-ci.org/sqlitebrowser/sqlitebrowser/jobs/650815012

**Comment by lulol** [comment]
Yes, my fault. There was some stray quotes left in the translation tags. Fixed now I hope.

**Comment by justinclift** [comment]
> Also seems that there are some weirdness in the original english source that I don't understand:
>
>    line="269" Find previous match with mapping (wrapping?)
>    line="2069" Could not open find resource file: %1 (open/find)

Do you remember what the weirdness was?

Looking at line [269 of src/TableBrowser.ui](https://github.com/sqlitebrowser/sqlitebrowser/blob/22a8cc051fa3d4bf977be5bcd804c7ef4fe06aca/src/TableBrowser.ui#L269), it seems ok:

https://github.com/sqlitebrowser/sqlitebrowser/blob/22a8cc051fa3d4bf977be5bcd804c7ef4fe06aca/src/TableBrowser.ui#L269

Looking at line [2069 of src/MainWindow.cpp](https://github.com/sqlitebrowser/sqlitebrowser/blob/22a8cc051fa3d4bf977be5bcd804c7ef4fe06aca/src/MainWindow.cpp#L2069), that one also seems ok:

https://github.com/sqlitebrowser/sqlitebrowser/blob/22a8cc051fa3d4bf977be5bcd804c7ef4fe06aca/src/MainWindow.cpp#L2069

It's completely possible I'm not seeing something obvious though. :wink:

**Comment by justinclift** [comment]
> The diff shows that there was a change at line="653" when the original was modified after the fact and needs fixing/merging.

Maybe the two spelling fixes in the english source earlier today:

* https://github.com/sqlitebrowser/sqlitebrowser/commit/1d1afaad218dfea9d9cdcf83821b3c5b33963ebb
* https://github.com/sqlitebrowser/sqlitebrowser/commit/fe88463cbad5476ca6555759eb70dee430d89f63#diff-1c0b64226a129d35f02dc0049484cd6b

**Comment by justinclift** [comment]
Gah.  Now I see what you mean with that line 2069 thing.  Yeah "open find" isn't proper wording of the source string. :wink:

**Comment by lulol** [comment]
> > Also seems that there are some weirdness in the original english source that I don't understand:
> > line="269" Find previous match with mapping (wrapping?)
> > line="2069" Could not open find resource file: %1 (open/find)

> Looking at line [269 of src/TableBrowser.ui](https://github.com/sqlitebrowser/sqlitebrowser/blob/22a8cc051fa3d4bf977be5bcd804c7ef4fe06aca/src/TableBrowser.ui#L269), it seems ok:
> 
> https://github.com/sqlitebrowser/sqlitebrowser/blob/22a8cc051fa3d4bf977be5bcd804c7ef4fe06aca/src/TableBrowser.ui#L269

Hmmm. Then I don't undestand what that "mapping" is referred to since the context from the adjacent terms seems to be about search with wrapping.

> https://github.com/sqlitebrowser/sqlitebrowser/blob/22a8cc051fa3d4bf977be5bcd804c7ef4fe06aca/src/TableBrowser.ui#L286

**Comment by justinclift** [comment]
> Hmmm. Then I don't undestand what that "mapping" is referred to since the context from the adjacent terms seems to be about search with wrapping.

Oh. Maybe it's supposed to be "wrapping" instead of "mapping"?

I wasn't thinking about it "in context". :wink:

**Comment by lulol** [comment]
It didn't like the 'iquest' entity for '&iquest;' in the html block. Will try the UTF-8 version directly and try again.

**Comment by justinclift** [comment]
Just pushed a fix for the "open find" wording problem too: https://github.com/sqlitebrowser/sqlitebrowser/commit/6683a9f53dec7a2e16d53758493fdb2543de108e

Which seems to have broken the automatic merge in this PR. :man_facepalming:

With this PR, is it ready for merging or are there more strings you want to do first?

**Comment by justinclift** [comment]
Thinking about the "mapping" thing more... yeah, it's almost definitely supposed to be "wrapping" instead.  Will push a fix in a sec. :wink:

**Comment by lulol** [comment]
> With this PR, is it ready for merging or are there more strings you want to do first?

I think that all should be resolved now except for the new source fixes.

But I'd like @mgrojo to review them just in case he spots some translation error or knows better ones.

**Comment by justinclift** [comment]
No worries.  I've just force pushed a single new commit to the `master` branch, fixing both of the source string typos you mentioned.  It means this PR will need to be manually applied instead of hitting the "Merge" button, but that's easily done so don't worry. :smile:

**Comment by lulol** [comment]
It seems that the translation for line="2069" was lost somehow and is generating a conflict.

**Comment by justinclift** [comment]
It'll probably just need manual adjustment in the file or something.  Shouldn't be too hard. :smile:

**Comment by mgrojo** [comment]
Hi @lulol, thanks for your translation!

I've merged your update after some minor adjustments:

 - I think it's [better not to use Title Case in Spanish](https://es.l10n.kde.org/normas_generales.php), it's not common style and looks strange when the translation becomes longer than the original. The previous release was already following that approach, so we had now a mixed style. 
- Some references to GUI elements in Preferences were inconsistent with the actual translation
- I had to revert the translations of shortcuts (not in tooltips, only as independent strings). Otherwise, the shortcut stops working, at least using my Qt library version. It is automatically translated, though, if we reference the shortcut using its identification in some message.
- I had to change some XML entities for letter with accents to the actual letter (`&aacute;` to á) because it failed to build. Did you use something different to Qt Linguist?

I've made a squad of all the changes when merging from the command line and now github doesn't detect that the pull request is merged, but it is in fact done, as you can see in 721ace49820d955c3752db7b7be1216d5729d6e3

**Comment by justinclift** [comment]
> I had to change some XML entities for letter with accents to the actual letter (&aacute; to á) because it failed to build. Did you use something different to Qt Linguist?

Sounds like the same problem the Polish translation initially had too.  That was done with KDE's [Lokalize](https://kde.org/applications/office/org.kde.lokalize).

The workaround was to simply put the updated .ts file into my local source tree, and run (Qt5) `lupdate` program again.  That seems to convert things back to the "standard" approach Qt5 likes, keeping all the other pieces correct. :smile:

**Comment by mgrojo** [comment]
> The workaround was to simply put the updated .ts file into my local source tree, and run (Qt5) `lupdate` program again. That seems to convert things back to the "standard" approach Qt5 likes, keeping all the other pieces correct. smile

Good to know. I only had to replace 4 entities for Spanish, but in Polish, for example, it would be a nightmare with so many non-ASCII characters.

**Pull request closed without merging**
