### PR TITLE
Working on Polish Translation

### PR DESCRIPTION
**Pull request by bartlomiej-przymus**
Can I carry on updating this file?

### CODE REVIEW

**Comment by karim** [comment]
Yes. Keep pushing updates/commits to your branch and notify us when you are done. All commits will be [squashed and merged](https://help.github.com/articles/about-pull-request-merges/#squash-and-merge-your-pull-request-commits) in the end.

Thanks a lot for your contribution. :smiley:

**Comment by bartlomiej-przymus** [comment]
I have committed translation file to wrong file path of my branch 3 days ago by accident so that delete https://github.com/sqlitebrowser/sqlitebrowser/pull/1582/commits/5a05aefd95d8139e2973651c778bc1dee1fea13f request is for that file.

**Comment by justinclift** [comment]
@bartlomiej-przymus How's this going?  We'll likely create our next beta release later on today, so wondering if these strings are ok to be merged in for that? :smile:

**Comment by bartlomiej-przymus** [comment]
Hi @justinclift ,
Im sorry I am terribly busy getting things in order (trying to land my first web dev job after i quit from my last job) so pressure is on translation is not finished i think it is 50% - 60%  complete only 30% checked to be 100% correct.

**Comment by bartlomiej-przymus** [comment]
It is ok merge it as majority of old translated text works just fragments need translating from scratch. I was going over the top with my translation by going over the text references on the internet to make it as close toaccepted standard as possible.

**Comment by bartlomiej-przymus** [comment]
I can always pick up from beta release and continue where I left off.
Once my life situation stabilizes.

**Comment by justinclift** [comment]
No worries at all @bartlomiej-przymus.  We all have weird periods in our life occasionally. :wink:

We'll merge this in for beta2 and our nightly builds.  You can pick it up later whenever life things are back in good shape again. :smile:

**Pull request merged**
