### PR TITLE
Improve the size policy (and more and better icons)

### PR DESCRIPTION
**Pull request by mgrojo**
These changes improve the size policy for translations having long texts
in some buttons by:

* Converting the text buttons in the Edit Database Cell to icons
* Making the "Type of data" label wrappable and expandable
* Converting the text buttons in the Browse Data tab to icons
* Allowing the Plot combo-boxes to shrunk

All this allows both the Browse Data and the docks to grow and shrink with
more freedom.

New icons for buttons are reused when appropriate in context menus.

Added icon for filter and improved icon for docks (has been mirrored so it
matches the actual dock position).

Added Print icon in Edit Database Cell using the extra free space, so the
print action there is more visible.

This continues the effort started in #1678.

### CODE REVIEW

**Comment by mgrojo** [comment]
@zvova7890 You might also like to review the result.

**Comment by justinclift** [comment]
Visually, this looks good to me. :smile:

Haven't taken a look at the code nor tried it out in operation though. :wink:

**Comment by zvova7890** [comment]
Now it very nice! Also Mode combo restrict minimum size like this(again translation is a little bigger than EN original)
image

**Comment by justinclift** [comment]
Sounds like it'd be useful to try out. :smile:

**Comment by mgrojo** [comment]
I've converted the buttons in Browse Data tab and the Edit Database Cell into toolbars.

This is how it looks if there is not enough horizontal space:

imagen

I think it's useful to allow customizing the style of all our toolbars, so we give a default that it's useful for low and medium resolutions, but the user with higher resolutions can set the icon with text styles in order to have bigger buttons:

imagen

This is how it looks with the text beside icons in all the toolbars:

imagen

imagen

**Comment by zvova7890** [comment]
Look's good! I like it. I will test this tomorrow

**Comment by mgrojo** [comment]
Some feedback about these changes? It doesn't need a complete review or test, only opinions about whether these new toolbars is the way to go.

**Comment by justinclift** [comment]
Creating once-off builds for this at the moment, so people can try it out and give hands on feedback. :smile:

Noticed one minor warning in the macOS build output which sounds like it might be important - probably not from this PR's `size_icons` branch, probably from code in `master`:

```
In file included from MainWindow.cpp:2:
In file included from .ui/ui_MainWindow.h:40:
./ExtendedTableWidget.h:59:10: warning: 'selectAll' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
    void selectAll();
         ^
/Users/jc/Qt/5.11.3/clang_64/lib/QtWidgets.framework/Headers/qabstractitemview.h:236:18: note: overridden virtual function is here
    virtual void selectAll();
                 ^
```

Not sure if that means the `selectAll()` call will be calling the right function from here or not.  Figured it's better to mention than not though. :wink:

**Comment by justinclift** [comment]
macOS builds:

* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-size_iconsv1-20190119.dmg
* https://nightlies.sqlitebrowser.org/osx-onceoffs/DB%20Browser%20for%20SQLite-sqlcipher-size_iconsv1-20190119.dmg

**Comment by justinclift** [comment]
Uh oh.  From watching the build logs, it turns out the last few nightly builds for both osx and win have been getting mucked with the merge of an older commit (61596adbce8b6be880e6bcc80f76bed2d82ab85e).

Not sure how well the builds since then have really been representing the changes (!).

Well, it's fixed now, so the nightlies should again be using a not-muddled-up version of master.

I'll redo the nightlies for today after these once-off builds too, just for good measure. :smile:

**Comment by justinclift** [comment]
Wind32 builds:

* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-size_iconsv1-2019-01-19-win64.msi
* https://nightlies.sqlitebrowser.org/win64-onceoffs/DB.Browser.for.SQLite-size_iconsv1-2019-01-19-win64.zip

**Comment by justinclift** [comment]
This morning's nightly builds have been regenerated for macOS and windows now too.

**Comment by mgrojo** [comment]
Any feedback about this change? If nobody is opposed, I think I'll merge this in the following days. It shouldn't be a problem, if there is some issue, we can fix it later or even revert some of the changes if they aren't welcome (I don't think they will, but someone might prefer the previous approach in some aspect).

**Comment by MKleusberg** [comment]
I haven't looked though all the changes (especially in the ui files) but this looks pretty good to me. So no objections from my side to merge this :smile: The only thing I noticed is that I got a warning that the ```static void addShortcutsTooltip(QWidget* widget, const QList<QKeySequence>& keys)``` function overload isn't used anywhere and can be deleted.

**Comment by MKleusberg** [comment]
Oh nevermind, that warning is unrelated to this PR :smile:

**Comment by mgrojo** [comment]
Thanks for reviewing, @MKleusberg. I've deleted the obsolete function and merged this.

**Pull request merged**
