### PR TITLE
Fix Windows build after PR #3068

### PR DESCRIPTION
**Pull request by mgrojo**

### CODE REVIEW

**Comment by mgrojo** [comment]
@justinclift, this is my blind attempt to fix the Windows build after looking at PR #3068 and the SQLCipher repository. Would you mind running the Windows nightly scripts and see what happens?

**Comment by justinclift** [comment]
@mgrojo Thanks.  I can try it in a few hours, after I get some sleep.  Have been setting up a new Windows build server, so this is good timing. :smile:

**Comment by justinclift** [comment]
Oh wow, that worked first go.  Awesome!  Really well done @mgrojo! :smile:

**Comment by justinclift** [comment]
Although the macOS build VM no longer works (it's being replaced over next few days), we can just leave the Windows builds still running as they should work for now.

I'll update some other things on the VM, then generate new Win32/64 builds.

Thanks heaps for figuring this out @mgrojo! :smile:

**Comment by chrisjlocke** [comment]
Zip it up and email me the Windows disk image.... ;)  Should only be 50 GB or so... ;)

**Comment by mgrojo** [comment]
Oh, nice, I should buy lottery this week :smile:

**Comment by justinclift** [comment]
Definitely. :grin:

**Pull request merged**
