### PR TITLE
Update Polish translation

### PR DESCRIPTION
**Pull request by wojnilowicz**

### CODE REVIEW

**Comment by mgrojo** [comment]
@bartlomiej-przymus, would you like to review this as previous translator? It's good when translations have a peer review process.

**Comment by bartlomiej-przymus** [comment]
@mgrojo, It is quite some time ago I have attempted this translation and nowadays it will be hard for me to spare some time to do proper review however...  I have gone briefly through the proposed changes and it is definitely more complete attempt. I don't have full testing environment set up so I cannot properly test this especially around placeholders within text. I saw some worrying bits that might not look the way they should so I will add my comment on a bit I think needs rethink from @wojnilowicz.

**Comment by justinclift** [comment]
@bartlomiej-przymus Sounds good. :smile:

**Comment by MKleusberg** [comment]
Thank you so much for your work here, @wojnilowicz! :+1:  I'll merge your changes - and sorry for not doing this earlier :wink:

**Pull request merged**
