### PR TITLE
Avoid attaching the plot when the signal is notifying the row count

### PR DESCRIPTION
**Pull request by mgrojo**
since the data wouldn't be available yet.

See issue #2286

### CODE REVIEW

**Comment by mgrojo** [comment]
I open this pull request, because there could be a better solution, which might imply refactoring in the signals emitted by the SqliteTableModel class.

**Comment by justinclift** [comment]
Cool.  This seems like it would have been super annoying to track down. :smile:

**Comment by MKleusberg** [comment]
Thanks, @mgrojo! As Justin says, this must have been awful to track down. I think this solution is the best for now. We could think about moving the ```if``` statement into ```SqliteTableModel::handleFinishedFetch()``` and don't emit the ```finishedFetch``` signal at all when only the row count is available and make use of the ```finishedRowCount``` signal for the Execute SQL code. But honestly I don't know if any other part of the code relies on these signals as they work now. So especially for a point release this is definitely better :smile:

**Comment by justinclift** [comment]
@mgrojo @MKleusberg Should this be merged into 3.12.1 as well?

**Comment by MKleusberg** [comment]
Yes, good point! This bug was introduced in 1f9101ae2a564121ba2843b68c1d7d3f8cff93ad so it is present in 3.12.0.

**Comment by mgrojo** [comment]
> Thanks, @mgrojo! As Justin says, this must have been awful to track down. I think this solution is the best for now. We could think about moving the `if` statement into `SqliteTableModel::handleFinishedFetch()` and don't emit the `finishedFetch` signal at all when only the row count is available and make use of the `finishedRowCount` signal for the Execute SQL code. But honestly I don't know if any other part of the code relies on these signals as they work now. So especially for a point release this is definitely better :smile:

Thanks. I tried some changes in the connection or emission of signals (not sure about that specific case though), and they either gave other problems, or did not solve the issue). We should take a look again when we have to change something related to that code.

**Comment by MKleusberg** [comment]
> We should take a look again when we have to change something related to that code.

Yeah, I agree :+1:

**Pull request merged**
