### PR TITLE
Prevent data loss when editing table with foreign keys enabled

### PR DESCRIPTION
**Pull request by mgrojo**
Our procedure for editing tables may involve a drop of the old table
definition. This will trigger the "ON DELETE CASCADE" clauses of the
child tables, leading to unexpected and silent data loss.

Following the procedure described in:
https://www.sqlite.org/lang_altertable.html
we can guarantee that no data is deleted, but at the cost of opening a
new transaction specific for the table modification. The possible pending
changes must be saved before. This is only done when the foreign_keys
pragma is enabled.

See issue #1481

### CODE REVIEW

**Comment by MKleusberg** [comment]
Just an idea for discussion here: for all tables with no ```ON DELETE``` or ```ON UPDATE``` references to it from other tables this shouldn't be necessary, right? Assuming this applies to most of the tables in most of the databases out there, we could check for that and don't show the message or commit the transaction for most tables. We'd just have to loop through all tables and all their foreign keys and check if any has a somehow matching clause (just checking if the table name is in their should be enough here). Without having put too much thought into it, I'd say it's worth the extra effort. Any opinions here? :smile:

**Comment by justinclift** [comment]
Pretty much "whatever works" and avoids the data loss potential is good by me.  Simpler and more reliable probably wins over added complexity, if that helps.

**Comment by mgrojo** [comment]
> Just an idea for discussion here: for all tables with no ON DELETE or ON UPDATE references to it from other tables this shouldn't be necessary, right? 

Not sure, because the SQLite documentation only suggest this procedure in general, without describing what the issues might be. I had a look to older issues and I've found this: #1398.  I haven't understood the problem, but in this case the error is in the copy, not the table drop.

**Comment by MKleusberg** [comment]
If I remember correctly we added the ```defer_foreign_keys``` bit for the copy procedure. So maybe the error in #1398 is already fixed - I haven't tried it though.

I'm pretty sure we can keep the current transaction when there are no ON UPDATE or ON DELETE clauses. But it's more difficult than I initially thought: if there are no such references and the user edits the table adding a self-reference with an ON DELETE clause, we need to check that too and maybe commit or abort. But that would mean committing or aborting in the middle of the table editing which doesn't seem right either. So yeah, let's not do that for now :wink:

I'll merge this as-is for now and if too many people complain that they want to edit their table without committing first we can always try to come up with something similar to what I was thinking of. And in the meantime no data gets deleted anymore :wink:

**Comment by mgrojo** [comment]
Thanks for reviewing and merging.

> If I remember correctly we added the defer_foreign_keys bit for the copy procedure. So maybe the error in #1398 is already fixed - I haven't tried it though.

It seems that change is previous to the version used in #1398 (3.10.99):
627ed4c56b64212ba93303530d3a61f6600fbfca was released in v3.10.1

By the way, the defer_foreign_keys is somewhat redundant now, but I've kept it just in case the alter table is called in other circumstances.

**Comment by MKleusberg** [comment]
Good thinking :smile: It shouldn't hurt to have in there.

**Pull request merged**
