### PR TITLE
updated readme to mention homebrew install

### PR DESCRIPTION
**Pull request by timbroder**

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks, good thinking. :smile:

**Comment by timbroder** [comment]
No merge? Is there something I can adjust?

:raised_hands:

**Comment by justinclift** [comment]
Nope, I just hit the wrong button is all.  \*sigh\*

Sorry for the confusion. 😦

**Comment by timbroder** [comment]
haha no prob. :+1:

**Comment by justinclift** [comment]
I just tweaked it anyway, adding some padding space to the top and bottom to match the other similar lines in the README.md.

As a thought, any interest in tweaking the index.html for the website?  (it's in this repo too, in the `gh-pages` branch)

**Comment by timbroder** [comment]
Sure. I'll take a look tomorrow or over the weekend

**Comment by justinclift** [comment]
Cool. :smile:

**Pull request merged**
