### PR TITLE
Fix Returning support

### LINKED ISSUE #2720: RETURNING keyword not implemented?
Details for the issue
--------------------

#### What did you do?

Inserting data into a table using the `RETURNING` keyword in the tab 'Execute SQL'.

```sql
CREATE TABLE t0(
  a INTEGER PRIMARY KEY,
  b DATE DEFAULT CURRENT_TIMESTAMP,
  c INTEGER
);
INSERT INTO t0(c) VALUES(random()) RETURNING *;
```

See [here](https://www.sqlite.org/lang_returning.html) for more information and above example query.

#### What did you expect to see?

The returned data in the output window element.

_Note: The data is correctly returned as expected when manually executed via command line._

#### What did you see instead?

Empty table with correct header, in this case:

|  a  |  b  |  c  |
| --- | --- | --- |

Useful extra information
-------------------------

The info below often helps, please fill it out if you're able to. :)

#### What operating system are you using?

- [ ] Windows: ( _version:_ ___ )
- [x] Linux: Arch Linux
- [ ] macOS: ( _version:_ ___ )
- [ ] Other: ___

#### What is your DB4S version?

- [ ] 3.12.2
- [x] 3.12.1
- [ ] 3.12.0
- [ ] 3.11.x
- [ ] Other: ___

#### Did you also

- [ ] Try out the latest nightly version: https://github.com/sqlitebrowser/sqlitebrowser#nightly-builds
- [x] Search for an existing similar issue: https://github.com/sqlitebrowser/sqlitebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20

### PR DESCRIPTION
**Pull request by bmalrat**
Hello 

This will fix #2720 
I tested it with the sample https://www.sqlite.org/lang_returning.html

```
CREATE TABLE t0(
  a INTEGER PRIMARY KEY,
  b DATE DEFAULT CURRENT_TIMESTAMP,
  c INTEGER
);
INSERT INTO t0(c) VALUES(random()) RETURNING *;
```

and with row:
```
INSERT INTO t0(c) VALUES(random()),(random()),(random()),(random()),(random()) RETURNING *;
```

The bug was in the row loader that try to append "LIMIT 49999 OFFSET 0" but it's not a SELECT

### CODE REVIEW

**Comment by bmalrat** [comment]
I spotted some other bug with DELETE that didn't commit the change and the change buttons are not affected.  
I will try to rework it.

**Comment by bmalrat** [comment]
My rework fixed the
`DELETE FROM t0 RETURNING *;`

**Comment by justinclift** [comment]
@MKleusberg Should this be merged? :smile:

**Comment by mgrojo** [comment]
I've finally included this in 299666d, but it hasn't been detected by GitHub as a merge of this pull request, because it was cherry-picked, squashed and modified to remove compilation problems due to incompatibility to current code. I'll close this as finished, then. Thanks, @bmalrat.

**Pull request closed without merging**
