### PR TITLE
Update Simplified Chinese translation

### PR DESCRIPTION
**Pull request by bssthu**
translate and fix

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @bssthu, I'll get the screenshots done in a bit, so you can double check before we merge this. :smile:

**Comment by justinclift** [comment]
This is every screenshot I could think of doing. :wink:

To me, this looks very good.  If you feel it is ready, I'm happy to merge this.  Just let me know. :smile:

screen shot 2016-10-19 at 18 56 54
screen shot 2016-10-19 at 18 57 00
screen shot 2016-10-19 at 18 57 15
screen shot 2016-10-19 at 18 57 20
screen shot 2016-10-19 at 18 57 27
screen shot 2016-10-19 at 18 57 34
screen shot 2016-10-19 at 18 57 39
screen shot 2016-10-19 at 18 57 46
screen shot 2016-10-19 at 18 57 52
screen shot 2016-10-19 at 18 57 58
screen shot 2016-10-19 at 18 58 04
screen shot 2016-10-19 at 18 58 09
screen shot 2016-10-19 at 18 58 34
screen shot 2016-10-19 at 18 58 56
screen shot 2016-10-19 at 18 59 03
screen shot 2016-10-19 at 18 59 11
screen shot 2016-10-19 at 18 59 16
screen shot 2016-10-19 at 18 59 39
screen shot 2016-10-19 at 18 59 55
screen shot 2016-10-19 at 18 59 59
screen shot 2016-10-19 at 19 00 05
screen shot 2016-10-19 at 19 00 10
screen shot 2016-10-19 at 19 00 16
screen shot 2016-10-19 at 19 00 25
screen shot 2016-10-19 at 19 00 36
screen shot 2016-10-19 at 19 00 42
screen shot 2016-10-19 at 19 00 49
screen shot 2016-10-19 at 19 00 57
screen shot 2016-10-19 at 19 01 04
screen shot 2016-10-19 at 19 01 11
screen shot 2016-10-19 at 19 01 34
screen shot 2016-10-19 at 19 01 43
screen shot 2016-10-19 at 19 01 49
screen shot 2016-10-19 at 19 01 55
screen shot 2016-10-19 at 19 02 02
screen shot 2016-10-19 at 19 02 06
screen shot 2016-10-19 at 19 02 10
screen shot 2016-10-19 at 19 02 57
screen shot 2016-10-19 at 19 07 23
screen shot 2016-10-19 at 19 07 35
screen shot 2016-10-19 at 19 07 42
screen shot 2016-10-19 at 19 07 58
screen shot 2016-10-19 at 19 08 02
screen shot 2016-10-19 at 19 08 20
screen shot 2016-10-19 at 19 09 53
screen shot 2016-10-19 at 19 10 02
screen shot 2016-10-19 at 19 10 10
screen shot 2016-10-19 at 19 10 16
screen shot 2016-10-19 at 19 10 22

**Comment by justinclift** [comment]
Hmmm, I'll merge this in now instead.

That will mean the nightly build in a few hours will have the updated translation, so you can test them directly if you want. :smile:

If there are further adjustments to make, just put them in a new PR. :smile:

**Comment by bssthu** [comment]
Thanks for your screenshots. Looks like I missed a few lines. I'll try later.

**Pull request merged**
