### PR TITLE
Fixed a typo.

### PR DESCRIPTION
**Pull request by mafagafogigante**
Found this one while translating. Not sure where else I should change it. (The pt_BR translation already accounts for it).

### CODE REVIEW

**Comment by MKleusberg** [comment]
Thanks for spotting this! :) 
I've just noticed another typo in the same line: 'encrpytion'. Do you mind changing that as well and put it into the same commit? Either way I'll be happy to merge this :)

**Comment by mafagafogigante** [comment]
Will do.

**Comment by mafagafogigante** [comment]
Got other 2!

**Comment by mafagafogigante** [comment]
Wait! @MKleusberg What do you think about csvparser.h line 13? "provde"?

**Comment by justinclift** [comment]
I'm happy to merge this now, but can leave it alone for a while if you want to keep looking for more.

Let me know what you want. :smile:

**Comment by mafagafogigante** [comment]
@justinclift Mind issuing a ``cat src/csvparser.h | grep provde``? Not sure exactly what is that.

**Comment by MKleusberg** [comment]
Wow, this has grown to quite an amount of typos by now :open_mouth: 
I think the 'provde' can be deleted entirely. But probably the entire sentence should be rewritten to something like 'This is an abstract class, an implementation of which you can pass to the CSVParser to get progress updates.' or so.

**Comment by mafagafogigante** [comment]
@MKleusberg Agreed. It makes sense now. I am not squashing these commits as it would break their atomicity.

**Comment by MKleusberg** [comment]
Again, thanks a lot for looking for all these typos :) In case you should find any more you're always welcome to open a new pull request :smiley:

**Comment by mafagafogigante** [comment]
I don't believe there are any other typos left. At least not in comments or strings.

Glad to know that.

-----Original Message-----

**Pull request merged**
