### PR TITLE
Make the application shortcuts configurable on Windows

### PR DESCRIPTION
**Pull request by karim**

### CODE REVIEW

**Comment by karim** [comment]
db

**Comment by justinclift** [comment]
You seem to have these in hand pretty well.  Maybe just push them directly to the repo instead? :smile:

**Comment by karim** [comment]
Okay, will do. :smiley: 

I thought maybe I should wait a little bit till the build is running smoothly. I saw earlier you got another problem with the build again.

**Comment by justinclift** [comment]
Ahhh yeah, I'm tracking that issue down now.  It doesn't seem to be a problem with the stuff you're doing here.

The winbuild.bat creates the .msi files fine when launched manually.  But when it's launched via the Task Scheduler on Win7 (as the **exact same user**), the .msi files don't get created.

I suspect it's something to do with PATH and/or environment problems.  Am in the process of adding output logging to winbuild.bat atm to see if I can capture some kind of error message. :smile:

**Comment by justinclift** [comment]
Just merged this, so it's in the nightly .msi's I'm rebuilding now. :smile:

**Pull request merged**
