### PR TITLE
attempt at adding decimal

### PR DESCRIPTION
**Pull request by jungle-boogie**
hopefully a passable attempt to add decimal support per
https://github.com/sqlitebrowser/sqlitebrowser/issues/373#issuecomment-211025161

I re-organized the conversion list, too.

### CODE REVIEW

**Comment by justinclift** [comment]
Hmmm, that's breaking the build.  Are you ok to click on "Details" to check the error, and attempt to fix it? :smile:

**Comment by justinclift** [comment]
@jungle-boogie Sorry, didn't notice you've pushed a fix.  Just tested it quickly here, and it (mostly) works.

There is one bit I'm unsure of though.  For decimal display, it's using "0x" as the prefix.  eg "0x10".

Isn't "0x" normally used to indicate a hexadecimal number?

**Comment by jungle-boogie** [comment]
%d is decimal!

**Comment by justinclift** [comment]
Awesome!  Testing now. :smile:

**Comment by justinclift** [comment]
Yep, that looks good now.  Thanks @jungle-boogie. :smile:

**Comment by MKleusberg** [comment]
Yes, this is looking fine :smile: Thanks for your contribution!
It's also nice to see somebody working on the display format feature - I wasn't really sure whether somebody is actually using it :wink:

**Comment by justinclift** [comment]
@MKleusberg - just as a heads up while on the topic... the format definition box itself doesn't seem to be editable for the "custom" type.  eg people can't type in their own format and have it stick.  Is that supposed to work? :smile:

**Comment by MKleusberg** [comment]
I'm not sure to be honest ^^ But the code looks like this was never supposed to work. Allowing to type in one's own display formats isn't as easy as it sounds either, because we'd had to add some extra error checking. With the current code I see two problems:
1) If the user types in some invalid code we'd get a syntax error. Not sure how we'd react there but we definitely don't display a proper error message.
2) The user could type in some code that generates more than one column. This one is tricky because it doesn't produce a syntax error but would cause a lot of confusion throughout the application. So by some means we'd have to detect this case and prohibit it.

So, yes, we can get this done. But it's a bit trickier than expected. I'll just open a new issue for now so we can keep this in mind :smile:

**Comment by justinclift** [comment]
Cool. :smile:

**Pull request merged**
