### PR TITLE
Rename variable 'errno' as Windows appears to object to it

### PR DESCRIPTION
**Pull request by apjarvis**
I think it was just the variable name so I have changed it but to not have a Windows machine to test it on.

### CODE REVIEW

**Comment by justinclift** [comment]
Yeah, that new commit should probably be in a PR based on the latest `master` branch. :smile:

**Comment by apjarvis** [comment]
Did a re-base and think the code is now correctly merged.

**Comment by justinclift** [comment]
Things were a bit messy, so I've just manually added your errno fixing commit to our `master` branch, instead of doing via the GitHub UI. :smile:

**Comment by justinclift** [comment]
Yep, that seems to have fixed the problem with MSVC 2015.  Good stuff @apjarvis. :smile:

**Comment by justinclift** [comment]
k, this is compiling ok on both win32 (MSVC2015) and win64 (MSVC2017), and our installers now bundle the resulting .dll as well.

One problem though... the extension doesn't seem to load.  At least, in trying just now with the win32 build, by manually adding the new `formats.dll` in our Preferences dialog, then restarting DB4S.

This dialog shows up immediately on the restart (of DB4S):

DB4S-PR_1827-screenshot1

Not sure how to go about debugging this just yet.  Probably need to get the compile happening in a development VM, and maybe trace through the extension loading code using Qt Creator or something.

Not a today thing, for me at least.  @apjarvis (or anyone)... ideas/suggestions for solving this are welcome. :smile:

**Comment by justinclift** [comment]
Same thing on macOS:

DB4S-PR_1827-screenshot2

**Comment by justinclift** [comment]
Follow up note - this was fixed by @karim in d9812186908ce96bb825dfd6f6f0e1362d691f68.

Conversation continued in: https://github.com/sqlitebrowser/sqlitebrowser/issues/1831#issuecomment-479570253

**Pull request closed without merging**
