### PR TITLE
Improve the build of tests

### PR DESCRIPTION
**Pull request by pinotree**
Improve the build and run of tests:
- allow the build of tests within the main build, so there's no need for a separate build for them, and ctest works with them
- split the `sqlb-unittests` in two separate (and different) tests

### CODE REVIEW

**Comment by justinclift** [comment]
This is failing in Travis CI btw.  Are you ok to look into it?

**Comment by pinotree** [comment]
> This is failing in Travis CI btw.

I guess that's because the build instructions still do the old build way. Is it something I can fix, or you need to adjust something in travis?

**Comment by justinclift** [comment]
I'm not 100% sure, as I've not personally done anything with Travis before.

Looking at this:

&nbsp; &nbsp; https://travis-ci.org/sqlitebrowser/sqlitebrowser/jobs/60943535

It seems like the errors are more of a build problem than a compiling problem:

```
The command "cd tests/build" exited with 0.
0.04s$ cmake ..
CMake Error: The source directory "/home/travis/build/sqlitebrowser/sqlitebrowser/tests" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
The command "cmake .." exited with 1.
0.01s$ make
make: *** No targets specified and no makefile found.  Stop.
The command "make" exited with 2.
0.01s$ ./sqlb-unittests
/home/travis/build.sh: line 41: ./sqlb-unittests: No such file or directory
The command "./sqlb-unittests" exited with 127.
0.01s$ cd ../../build
```

I'm not sure of the right approach here, so will defer to the main coders. :wink:

**Comment by MKleusberg** [comment]
Hi Pino!
Sorry, I only took a closer look at your commit now, after I've changed the cmake files a bit... Can you maybe rabase them and add the FileDialog.cpp/FileDialog.h files to the src/tests/CMakeLists.txt file, so the tests build again? As soon as that's done I'll merge the commits.
Nice work by the way :smiley: Thanks for the nice commit structure and documentation, too :+1:

**Comment by pinotree** [comment]
> Can you maybe rabase them

Yep, done.

**Comment by MKleusberg** [comment]
Awesome! Again, thanks a lot for this PR :smiley:

**Pull request merged**
