### PR TITLE
Suggestion: 'Tab' indents multiline selection in SQL editor

### PR DESCRIPTION
**Pull request by schdub**
#255

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @schdub, that's awesome. :grinning:

Just tried it here, and it's working fine for me.

**Comment by rp-** [comment]
sorry but there are some problems with this.

1. we have no option if we want to insert tabs or spaces, nor how much of them
2. tabbing in works nice, but shift-tab doesn't
3. also the amount of work for a such a "small" feature in that widget, makes me think if we shouldn't move to a different text control like qscintilla or something similar.

**Comment by justinclift** [comment]
Ahhh.  What should we do then?

**Comment by schdub** [comment]
@rp-, what shift + tab combination should to do?

I can add option into Preferences -> SQL, checkbox "Using spaces for indentation" (not checked by default?) and spinbox next to it with amount of spaces for one tab.

**Comment by justinclift** [comment]
"shift + tab" would un-indent.   eg make the code go back towards the left by the indent amount

The preferences bits you mention sound good too.  As a default value, my preference is 4 spaces... but I don't strongly care about that, if other people want something different instead. :wink:

**Comment by rp-** [comment]
I just rembembered that I recently added a option for the tab size, but none for inserten tabs or spaces.

**Comment by MKleusberg** [comment]
I've pushed a new branch called qscintilla yesterday which replaces our code editor widget by QScintilla. So I'm quite glad @rp- is mentioning it :wink: 
It's still not perfect but Tab indentation and Shift+Tab Unindentation works out of the box there and we get many other nice features like code folding for free if we decide to. I'm currently absuing Travis to get the Qt4 build running and hope to have time to fix the remaining issues so we can switch in the near future :)

**Comment by MKleusberg** [comment]
Any tests for the new branch are definitely welcomed, by the way :wink:

**Comment by justinclift** [comment]
Ahhh cool, I hadn't seen that.

Should we make a nightly build for that branch, so people can test it out?

**Comment by justinclift** [comment]
@MKleusberg The QtScintilla license doesn't seem to be compatible with our project?

**Comment by MKleusberg** [comment]
@justinclift Yeah, we could make a nightly build but I'm not sure if it's worth the effort (don't know how much work is needed for an extra nightly build, though). I hope we can merge this relatively quickly into the master branch anyways to avoid a lot of rebasing.
The license should be fine - it's MIT for Scintilla and GPL for the Qt wrapper. MIT isn't very restrictive at all and the GPL is already used in our project by the QCustomPlot library. Because it's only a library anyway there really should be no problem - it's basically a separate project under a separate license and not really a part of our project. It just happens to be in the same Git repository for easier compilation. If static linking is a problem for e.g. the Apple Store we can always link the libraries dynamically like we do for SQLite (except for the Windows build) and Qt.

I'll open a new pull request for the branch in a second. Not to have it merged right now but to have a place for further discussion :)

**Comment by justinclift** [comment]
Thanks @MKleusberg.  For OSX, a nightly build is pretty easy to add.  It's just a few more lines to the script. :wink:

I am concerned about the GPL for the Qt Scintilla wrapper, but yeah, lets discuss this in the PR you put up. :smile:

**Comment by rp-** [comment]
BTW. I don't think we are allowed to relicense the qcustomplot to apache2
license

@MKleusberg <https://github.com/MKleusberg> The QtScintilla license doesn't
seem to be compatible with our project?

—
Reply to this email directly or view it on GitHub
<https://github.com/sqlitebrowser/sqlitebrowser/pull/258#issuecomment-93474440>
.

**Pull request merged**
