### PR TITLE
Update Polish translation

### PR DESCRIPTION
**Pull request by wojnilowicz**

### CODE REVIEW

**Comment by justinclift** [comment]
Awesome @wojnilowicz, this looks like it updates lots!

@bartlomiej-przymus How does this look to you? :smile:

**Comment by wojnilowicz** [comment]
@justinclift 
There is no response in over 15 days. What's the sensible time we should wait?

**Comment by justinclift** [comment]
Good reminder.  Lets just merge it. :smile:

**Comment by justinclift** [comment]
Merged.  Thanks for putting the time into improving this @wojnilowicz. :smile:

**Pull request merged**
