### PR TITLE
Silence SQLITE_HAS_CODEC Redefinition Warnings

### PR DESCRIPTION
**Pull request by scottfurry**
During compiling of source, compiler will issue numerous warnings stating that `SQLITE_HAS_CODEC` is being redefined. Commit resolves this warning by placing a `#ifndef` pragma around declaration in header.

Also, minor format editing done to ensure good spacing to improve readability of pre-processor declarations.

### CODE REVIEW

**Review by lucydodo — APPROVED** [review]

**Comment by lucydodo** [comment]
LGTM, and if there's nothing special about it, why not merge it? 😄

**Comment by justinclift** [comment]
@lucydodo Are those CI failures due to GitHub flakiness, or are they something that needs looking at? :smile:

**Comment by lucydodo** [comment]
@justinclift It looks like there was some kind of **force push** on the 'homebrew-core' tab.
So the `brew update` command doesn't work properly. To fix this, run `brew update` twice and it should work fine.
(Or untap and tap 'homebrew-core' again) I can temporaily fix the CI workflow if needed. 😄

**Comment by justinclift** [comment]
k, doing it now...

**Comment by justinclift** [comment]
Oh hang on, this isn't with our build infrastructure, it's with the GitHub Actions builders.

**Comment by lucydodo** [comment]
According to Homebrew team, it looks like a GitHub issue: https://github.com/orgs/Homebrew/discussions/4612

**Comment by justinclift** [comment]
Scrolling to [the bottom of that GitHub issue](https://github.com/orgs/Homebrew/discussions/4612#discussioncomment-6323675), they seem to think it's fixed.

Maybe we should let them know it's started up again?

**Comment by lucydodo** [comment]
I thought about that for a second, but then I saw below comment.
> We continue to monitor in conjunction with GitHub.
so I figured they probably already knew that, and I didn't leave it. 😄

**Comment by lucydodo** [comment]
Additionally, I just created a branch with a commit that might fix this: https://github.com/sqlitebrowser/sqlitebrowser/tree/avoid-homebrew_issue
You can always merge it into the `master` branch if you need to.

**Comment by justinclift** [comment]
> You can always merge it into the master branch if you need to.

If you make a PR with it, then CI should automatically run with it for that PR.  So we can see if it works... :smile:

**Comment by lucydodo** [comment]
Even if I create a PR, will it not work based on the workflow in existing source tree?

**Comment by lucydodo** [comment]
Well, it looks like I was wrong. My apologies. Here's the PR: https://github.com/sqlitebrowser/sqlitebrowser/pull/3394

**Comment by lucydodo** [comment]
Screenshot 2023-07-02 at 21 16 50

**Good news**: The 'Install dependencies' job was successful as you can see. 😄

**Comment by justinclift** [comment]
Cool.  Lets see it run to completion, just in case.  If it works fine, then we can merge that PR and rebase this one onto the updated `master`.  That should then get the CI working for this PR too. :smile:

**Comment by justinclift** [comment]
Damn.  It's still not happy. :frowning:

**Comment by justinclift** [comment]
@lucydodo  Hmmm, I'm going to leave this to you as I'm doing other stuff. :wink:

**Comment by lucydodo** [comment]
Don't worry, Let me see if I can figure it out :)

**Comment by lucydodo** [comment]
@justinclift It seems to be working fine now :)

**Comment by scottfurry** [comment]
Original pull request doesn't appear to have been pulled into master.

**Comment by scottfurry** [comment]
Commit merged into master. This was a little painful with CI issues confusing things. Hard for me to focus on one issue when unrelated things get piled on. A *Me* problem.

**Comment by lucydodo** [comment]
@scottfurry Did I do something wrong?

**Comment by scottfurry** [comment]
> @scottfurry Did I do something wrong?

The original commit was not pulled into master. Was it wrong? No. Just an oversight. I think everyone got *hyper-focused* on the CI problems that in fixing *that* the change for resolving the codec warning got *lost* somehow.

Not to get *Too Philosophical* on people, it's easy to lose sight of the hierarchy and orderliness of multiple git repositories/branches. I think that's what happened here. There was the master branch and the codec changes were in another branch. All the CI fixes got push from the changes branch into master. The original fix got left behind.

Easy fix. @lucydodo Don't beat yourself up.

**Comment by lucydodo** [comment]
Thanks for your kindness. 'Git' seems to be difficult no matter how much I learn and use it. 😄 😄

**Comment by scottfurry** [comment]
*Ah, grasshopper...when you can snatch the commit from my hand, then you will be ready.*

**Pull request merged**
