### PR TITLE
TestImport: fix unicode handling

### PR DESCRIPTION
**Pull request by pinotree**
The small patch series improves the handling/testing of unicode (non-ASCII) data in the `TestImport` test.

### CODE REVIEW

**Comment by justinclift** [comment]
Would you be ok to squash these two commits into a single one?

**Comment by pinotree** [comment]
That's ok for me.

**Comment by MKleusberg** [comment]
Looks good! :+1: Thanks a lot :)

**Comment by justinclift** [comment]
@pinotree Awesome.  Thanks for squashing them into one commit too.  It helps keeps the repo history neat. :smile:

**Pull request merged**
