### PR TITLE
Update Chinese (Simplified) translations

### PR DESCRIPTION
**Pull request by yfdyh000**

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @yfdyh000, that looks very helpful. :smile:

@bssthu @mercury233 Do either of you have time to look this over quickly?

**Comment by mercury233** [comment]
nice work, but some texts translated by me seem not be used as base (我对此倒是没有意见，只是觉得奇怪), @justinclift the translation files in the master branch didn't get updated with the v3.12.x branch?

**Comment by justinclift** [comment]
@mercury233 Oops, you're right.  The PR from #2421 was only merged into the `v3.12.x` branch... and not merged into `master`.

Hmmm, I guess the best approach here will be to merge that translations from #2421 into `master` first, then see what needs applying from this PR here (#2454) to it.

Does that sound reasonable?

**Comment by mgrojo** [comment]
I cherry-picked recently some of the missing translations in the `master` branch, but it seems I missed this one (unintentionally). We could solve it ourselves by merging first  #2421 and then this PR, resolving the conflicts blindly in favour of the first translation. But ideally, it should be done by a Chinese speaker, so the best regarded translation can be chosen for each conflict.

**Comment by mercury233** [comment]
@yfdyh000 is an expert in translation so I prefer his choice

**Comment by mgrojo** [comment]
Perfect, then let's not delay it more. I'll merge it now. Could someone confirm with [tomorrow's nightly build ](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds)that shortcuts are working fine? A user reported problems when the shortcut was translated (even in this case, where the text are equal) and we are a bit suspicious since then.

**Comment by yfdyh000** [comment]
> Perfect, then let's not delay it more. I'll merge it now. Could someone confirm with [tomorrow's nightly build ](https://github.com/sqlitebrowser/sqlitebrowser/wiki/Nightly-Builds)that shortcuts are working fine? A user reported problems when the shortcut was translated (even in this case, where the text are equal) and we are a bit suspicious since then.

Check the https://nightlies.sqlitebrowser.org/latest/ page, no windows builds were updated.

In addition, I have tried repeatedly but failed to building this software on Windows or https://ci.appveyor.com/. This may needs updated build instructions, clearer processing steps, and CI for Windows os.

**Comment by chrisjlocke** [comment]
nudges @justinclift - Are the Windows nightlies OK?  (last built 27 Nov).

**Comment by justinclift** [comment]
> nudges @justinclift - Are the Windows nightlies OK? (last built 27 Nov).

Looking now.  Ugh.  The build server ran out of space, so suspended the VM's.  I've been putting off upgrading it's storage to something bigger, but I'd better get it done.  That build server only has a ~250GB SSD which everything is running off, and the macOS VM grows over time without reclaiming disk space.

I'll clear off some space now, get the VM's running again, and order a bigger SSD for it. :wink:

**Comment by justinclift** [comment]
Have now ordered a new SSD (~500GB) for the build server, which will turn up in the next few days.  The VMs themselves are still copying around... :wink:

**Comment by chrisjlocke** [comment]
What's the OS?  Plain Windows, or server version?  I'd recommend Macrium Reflect to clone it - there is a free version. I don't know what toy's you've got in a box, but these are damn useful for doing stuff like this: https://www.amazon.co.uk/USB-SATA-Adapter-Cable-Drives-en-GB-SATA-USB-3-0-converter/dp/B01N2JIQR7 - can simply image the drive while Windows is ticking along.

**Comment by justinclift** [comment]
> What's the OS?

macOS.  Cloning to a new drive on macOS is pretty straight forward.  Have done it a few times before. :smile:

**Comment by chrisjlocke** [comment]
Oooooh.  Well, there is CloneZilla then, but you'd need a storage area for the image (network, etc).  😃

**Comment by justinclift** [comment]
Storage area for the image isn't a problem.  Have a [NAS](https://www.freenas.org). :smile:

**Comment by justinclift** [comment]
Btw, new Win32 and Win64 "latest nightly" builds are now online.  They're using SQLite 3.34.0, which was released a few days ago.  Hopefully they work ok.

Next step, copy the macOS VM image back onto the build server...

**Pull request merged**
