### PR TITLE
Update project links to HTTPS

### PR DESCRIPTION
**Pull request by karim**

### CODE REVIEW

**Comment by justinclift** [comment]
Good thinking @karim. :smile:

**Comment by karim** [comment]
You might want to change the link in the project description too. :smiley:

**Comment by justinclift** [comment]
Heh Heh Heh.  Pretty sure you have the right permissions to do that as well. :wink:

**Comment by karim** [comment]
I don't see `settings` on top of the project page, and trying to access https://github.com/sqlitebrowser/sqlitebrowser/settings gives me a 404 error.

**Comment by justinclift** [comment]
Ugh.  That's weird.  I could have sworn I gave everyone permissions.  1 min... :wink:

**Comment by justinclift** [comment]
Ahhh.  It was set to write access instead of Admin in the team perms.  Now fixed.  Try again. :grin:

**Comment by karim** [comment]
Worked now! Thanks. :smile:

**Pull request merged**
