### PR TITLE
Replace `http` with `https` in the About window

### LINKED ISSUE #3571: [Bug]: Some links in About window have http protocol rather than https
### What did you do?

I opened the About window.

### What did you expect to see?

All the links use https 😊

### What did you see instead?

Some of the links use http:

image

### DB4S Version

3.12.2

### What OS are you seeing the problem on?

MacOS

### OS version

_No response_

### Relevant log output

_No response_

### Prevention against duplicate issues

- [X] I have searched for similar issues

### PR DESCRIPTION
**Pull request by rafrafek**
Fixes #3571

### CODE REVIEW

**Comment by justinclift** [comment]
Heh Heh Heh

I forgot about all the .ts files too.  Thanks for including them in the change. :smile:

**Comment by justinclift** [comment]
Please ping me when you feel this is ready, as I'm not sure if GitHub will alert me otherwise. :smile:

**Comment by rafrafek** [comment]
@justinclift, I think it's ready!

**Review by justinclift — APPROVED** [review]
Looks good to me. :smile:

**Comment by justinclift** [comment]
Thanks heaps for this @rafrafek, just merged it. :smile:

**Comment by justinclift** [comment]
Awww crap.  I was supposed to squash the commits into one before merging this and didn't notice.

Oh well, it's done now. :facepalm:

**Comment by justinclift** [comment]
I'm going to manually merge the commits on the `master` branch.

**Comment by justinclift** [comment]
I've manually merged the commits in this PR into a single one (https://github.com/sqlitebrowser/sqlitebrowser/commit/b4c46caa401f771aeeeb54826479c5c99e2e20f7) and force pushed it to the `master` branch.  Cleaner commit history that way. :smile:

**Pull request merged**
