### PR TITLE
Add commandline argument for version output

### PR DESCRIPTION
**Pull request by FriedrichFroebel**
See https://github.com/sqlitebrowser/sqlitebrowser/issues/1064.

Additionally fixed a tabulator error inside the translation discovered while testing.

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @FriedrichFroebel Wow, that's pretty awesome.  I'll try it out here in a few minutes just to make sure, then probably merge it right away. :smile:

**Comment by justinclift** [comment]
Yep, it compiles perfectly fine.  One small thing though... would you be ok to update it so the "-v" option is shown in alphabetical order for the help list?  (and yeah, that probably means moving "-q" too, which is also out of order)

**Comment by chrisjlocke** [comment]
Just a thought.  If someone runs this on the nightly, then its pretty pointless, as it'll always show 3.9.99.  Could the application date also be added?  So '3.9.99 (2 Jul 2017)'.  Obviously the date format would be whatever you wanted (I'm used to the dd MMM yyyy format)...
I was also going to suggest checking to see if there was an update available ("v3.9.99 (2 Jul 2017).  v3.10.Beta1 is available") but for a command that would get little exposure, its just code bloat.

**Comment by FriedrichFroebel** [comment]
Did not think of this, but will have a look at the time stamp.

**Comment by justinclift** [comment]
Thanks for re-ordering it @FriedrichFroebel. :smile:

Should this be merged-as is, or would it be better to wait for the time stamp bit too?

**Comment by FriedrichFroebel** [comment]
I thought it would be much easier to create such a time stamp, but as I only have a basic knowledge of C++ I think it would be better to merge this code as is now and let someone with more experience add the time stamp later.

**Comment by justinclift** [comment]
No worries at all.  Now merged. :smile:

**Comment by MKleusberg** [comment]
I've just added the build date to the ```-v``` command line output, but only for nightlies and beta releases (see the comments for that). The date format is currently ```MMM dd yyyy``` because that's the format C++ uses to tell you the build date. We could reformat it to a different format, even depending on the user's locale, but I'm not sure it's worth the effort :smiley:

**Pull request merged**
