### PR TITLE
Adds more Windows install options

### PR DESCRIPTION
**Pull request by tesar-tech**

### CODE REVIEW

**Comment by chrisjlocke** [comment]
> choco install sqlitestudio

Thats a different software product.  DB4S is either 'choco install sqlitebrowser', 'choco install sqlitebrowser.portable' or 'choco install sqlitebrowser.install'

https://community.chocolatey.org/packages?q=db+browser+for+sqlite

**Comment by justinclift** [comment]
@chrisjlocke Do you reckon this should be merged as-is?  (will need squashing to one commit first though)

**Comment by rasa** [comment]
FYI, both
`scoop bucket add extras & scoop install sqlitebrowser` and
`scoop bucket add versions & scoop install sqlitebrowser-nightly` 
work

**Comment by mgrojo** [comment]
Thanks @rasa.

**Pull request merged**
