### PR TITLE
consistent naming of DB Browser for SQLite

### PR DESCRIPTION
**Pull request by horst-p-w-neubauer**
done:
* change all DB4S to DB Browser for SQLite
* change "Click the button to create a DB4S certificate" to "Click the button to 'Generate client certificate'"

### CODE REVIEW

**Comment by horst-p-w-neubauer** [comment]
Before merging the .ts files should be updated - I'm just waiting for approval of the text changes.

**Comment by justinclift** [comment]
Yep, the text changes here are good. :smile:

**Comment by horst-p-w-neubauer** [comment]
When I update the .ts files I get some more changes than those I've initiated, I'd push them too. The alternative would be to extract them manually - that might be dangerous.

**Comment by horst-p-w-neubauer** [comment]
@justinclift, What about the libs\qscintilla\Qt4Qt5\*.ts files? Should I commit the changes or ignore?

**Comment by scottfurry** [comment]
I would suggest leaving the libs folder alone. Those are, for
      the most part, upstream source files.
    
    On 2020-04-30 7:44 a.m.,
      horst-p-w-neubauer wrote:
    
    
      
      @justinclift,
        What about the libs\qscintilla\Qt4Qt5*.ts files? Should I commit
        the changes or ignore?
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/sqlitebrowser/sqlitebrowser/pull/2224#issuecomment-621861759",
"url": "https://github.com/sqlitebrowser/sqlitebrowser/pull/2224#issuecomment-621861759",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by horst-p-w-neubauer** [comment]
translating itself is probably a different commit / pr cycle

**Comment by justinclift** [comment]
Yep, the translating itself is a different PR, as that'll need to be done by a bunch of different people.

Sounds like this PR is ready to merge now though.  Yes? :smile:

**Comment by horst-p-w-neubauer** [comment]
Yes!

**Comment by justinclift** [comment]
Awesome!  Thanks heaps for taking care of this stuff @horst-p-w-neubauer. :smile:

**Comment by justinclift** [comment]
I've just applied this PR to the `v3.12.x` branch too, for good measure. :smile:

**Pull request merged**
