### PR TITLE
Indicate when display strings are being truncated

### PR DESCRIPTION
**Pull request by justinclift**
Also reduce the minimum length to 1, just in case it's useful for
people.

For #761.

### CODE REVIEW

**Comment by justinclift** [comment]
Making this a PR instead of just committing it in case there's a better way. :smile:

**Comment by justinclift** [comment]
Note, I'm not sure if the "..." should be wrapped by `tr()` or not.

**Comment by chrisjlocke** [comment]
Does tr() simply translate it?  Wouldn't that cause unnecessary delay?

**Comment by justinclift** [comment]
Merged it.  The code is pretty simple, and seems to work without side effects.

**Pull request merged**
