### PR TITLE
Updating French translation for DB4S 3.10.0-beta1

### PR DESCRIPTION
**Pull request by justinclift**

### CODE REVIEW

**Comment by justinclift** [comment]
@mvt91 Thanks for emailing the initial translation update through.  I'll go through and get screenshots done for all of the major bits soon, then add them here. :smile:

**Comment by justinclift** [comment]
Note - screenshot taking is still in progress. :wink:

---

Here's the output for the `help` option:

```
Usage: src/DB Browser for SQLite.app/Contents/MacOS/DB Browser for SQLite [options] [db]>
Arguments utilisables en ligne de commande :
  -h, --help		Affiche les options en mode ligne de commande
  -q, --quit		Quitte l'application après l'exécution du script
  -s, --sql  [fichier], Exécute ce fichier de commande SQL après l'ouverture de la base de données
  -t, --table [table]	Parcourir cette table après l'ouverture de la base de données
  -v, --version		Display the current version
  [fichier]		Ouvre cette base de données SQLite
```

The `-v` line is untranslated, as it's a new thing added yesterday so isn't in the .ts file yet.  We'll need to update the .ts file to include that and the other changes from the last few days. :wink:

## Screenshots

- [x] Menus
screen shot 2017-07-28 at 13 53 16
screen shot 2017-07-28 at 13 53 25
screen shot 2017-07-28 at 13 53 43
screen shot 2017-07-28 at 13 53 54
screen shot 2017-07-28 at 13 54 04
screen shot 2017-07-28 at 13 54 14
screen shot 2017-07-28 at 13 54 24
screen shot 2017-07-28 at 13 54 32

- [x] AboutDialog.ui
screen shot 2017-07-28 at 13 56 34

- [x] CipherDialog.ui
screen shot 2017-07-28 at 13 58 17

- [x] ColumnDisplayFormatDialog.ui
screen shot 2017-07-28 at 14 24 55
screen shot 2017-07-28 at 14 24 59

- [x] CreateIndexDialog.ui
screen shot 2017-07-28 at 14 00 21

- [ ] EditDialog.ui

- [ ] EditTableDialog.ui

- [ ] ExportCsvDialog.ui

- [ ] ExportSqlDialog.ui

- [ ] ImportCsvDialog.ui

- [ ] MainWindow.ui
  * [x] Database Structure
screen shot 2017-07-28 at 14 01 40
screen shot 2017-07-28 at 14 02 07
screen shot 2017-07-28 at 14 02 16
screen shot 2017-07-28 at 14 02 25
screen shot 2017-07-28 at 14 02 31
screen shot 2017-07-28 at 14 02 44
screen shot 2017-07-28 at 14 02 55
screen shot 2017-07-28 at 14 03 00
screen shot 2017-07-28 at 14 03 07

  * [x] Browse Data

screen shot 2017-07-28 at 14 03 42
screen shot 2017-07-28 at 14 03 54
screen shot 2017-07-28 at 14 04 01
screen shot 2017-07-28 at 14 04 07
screen shot 2017-07-28 at 14 04 16
screen shot 2017-07-28 at 14 04 23
screen shot 2017-07-28 at 14 04 32
screen shot 2017-07-28 at 14 04 39
screen shot 2017-07-28 at 14 04 45
screen shot 2017-07-28 at 14 04 53
screen shot 2017-07-28 at 14 05 01
screen shot 2017-07-28 at 14 05 11
screen shot 2017-07-28 at 14 23 12
screen shot 2017-07-28 at 14 23 20

  * [x] Edit Pragmas
screen shot 2017-07-28 at 14 05 26
screen shot 2017-07-28 at 14 05 31
screen shot 2017-07-28 at 14 05 38
screen shot 2017-07-28 at 14 05 46
screen shot 2017-07-28 at 14 05 53
screen shot 2017-07-28 at 14 06 05

  * [x] Execute SQL
screen shot 2017-07-28 at 14 06 39
screen shot 2017-07-28 at 14 06 43
screen shot 2017-07-28 at 14 06 48
screen shot 2017-07-28 at 14 06 54
screen shot 2017-07-28 at 14 07 04
screen shot 2017-07-28 at 14 07 25
screen shot 2017-07-28 at 14 07 31
screen shot 2017-07-28 at 14 08 13
screen shot 2017-07-28 at 14 16 39
screen shot 2017-07-28 at 14 09 35
screen shot 2017-07-28 at 14 10 21

- [ ] PreferencesDialog.ui

- [ ] Remote dock

- [ ] VacuumDialog.ui

**Comment by chrisjlocke** [comment]
Just making a point thats probably not worth making .... Is the program called 'DB Browser for SQLite' or 'DB Browser pour SQLite' ?  The about page/caption has 'pour', while the main program caption/menus say 'for'.

image

For consistency, one of them ideally needs changing...  but its such a minor point, no-one else in the Universe would probably give a stuff.... ;)

**Comment by justinclift** [comment]
@mvt91 ping?

**Comment by mvt91** [comment]
Pong ;)

Hi Justin,

I'll have a look before next sunday.
It was a little hard in my company last days...

Best regards

Michel


Le 03/08/2017 13:50, Justin Clift a écrit :

**Comment by justinclift** [comment]
No worries, I was just feeling a bit nervous. :smile:

**Comment by mvt91** [comment]
Hi Justin,

I can't find the help texts (using under a shell).

Ok, well done. I download the last file release, but...
In some (many) texts, the translation is lost ?

Remarks :

CipherDialog

For :
Passphrase (Phrase Secrète) the button width must be enlarged.
Raw Key : idem (Clé de Chiffrement)

EditIndexDialog
For
Table Column, the column width must enlarged (Colonne de table) or it is 
possible to have a reduced text : Colonne, I suppose it is always a 
table column.

Main Dialog
You can export to a Json file, you can't Import from a Json file ? 
(except from a specific option)

View :
in QtLinguist, I can't see all the options of the View item such as your 
pictures...

EditTableDialog
I can't see the translated text in QtLinguist : Warning, There is 
something with this table definition that our parser doesn't fully 
understand, etc. (bottom of the window)
Some text are not translatable directly. For example Not Null is 
translated to Non Null but, if I leave the cursor on the field, the text 
shown is "Not Null" (corresponding to the Sql directive) This "span 
text" is not in that ui dialog.
For "ergonomic purpose" (readability) , I've replaced U by Unique, AI by 
Incrément Auto., PK by Clé primaire. (In french  U IA CP => to...)


... And here is the NEW file

Best regards

Feel free to show me (with something hard and heavy ;) all my errors.

Cheers

Michel


Le 03/08/2017 14:40, Justin Clift a écrit :

**Comment by justinclift** [comment]
Ahhh, that's a bit confusing for me.

When you say:

```
I can't find the help texts (using under a shell).
Ok, well done. I download the last file release, but...
In some (many) texts, the translation is lost ?
```

What are you meaning?  I'm having trouble understanding that. :smile:

If you've grabbed the newest sql_fr.ts file, that won't work (yet) as it doesn't yet have the string you've done added to it.  We'll need to merge those in first, then regenerate it so the changes in our main source code from the last few days are added.

Hmmm... does that make sense? :smile:

**Comment by mvt91** [comment]
Sorry for the delay, I didn't receive the message.

I didn't find --version in my file (with an editor too).
I supposed I've a wrong file.
I came here and found a new translation file (4 days ago at the date of my visit) so I got it and use QtLinguist again...

I can try to make a diff on the file you sent me and I translated and the last one I sent you.
If this can help ?

What are the conflicts ? I saw some difference (new texts or some texts with less options)...

**Comment by justinclift** [comment]
Ahhh.... that new file is missing a lot of stuff.  Hmmm... I know... I'll merge the sqlb_fr.ts file from this Pull Request into our source, then I'll regenerate it again so it has the new strings (eg `--version`).

Guessing it wouldn't be too hard for you to cut-n-paste the updates you've done to that new file (from 4 days ago) to it.

Hmm... not 100% sure this will work, but lets try it out and see how it looks. :smile:

**Comment by justinclift** [comment]
@mvt91 Well, that seemed to go ok from my point of view.  I've just merged in the French translation file you emailed a while back, which I made this Pull Request from.

Then I regenerated the sqlb_fr.ts file, so it added the new source strings (eg `--version`):

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/translations/sqlb_fr.ts

I think we're about 99% done. :smile:

**Comment by mvt91** [comment]
Hi Justin,

I'll check it.

I always save files with version number on my computeur.
So, after a big update, I can roll-back

Le 07/08/2017 16:09, Justin Clift a écrit :

**Comment by justinclift** [comment]
Cool. :smile:

**Comment by mvt91** [comment]
Hi Justin,

I corrected a few texts. I'll send the file by email (can't attach the file here).

Please, indicate me if everything is correct.
I saw you don't like my translation of --version ;)

**Comment by mvt91** [comment]
Hi Justin,

The new file

Le 07/08/2017 16:09, Justin Clift a écrit :

**Comment by justinclift** [comment]
Ahhh, yeah.  You'll need to email it to my private email address, as emailed files don't work for GitHub issues. :smile:

**Comment by mvt91** [comment]
Done

Le 08/08/2017 13:53, Justin Clift a écrit :

**Comment by justinclift** [comment]
Thanks @mvt91, that's awesome. :smile:

Just committed it in 44d64f2a8f9eba7cc1f9308b454e3900641691b5.

**Comment by mvt91** [comment]
:)

**Pull request closed without merging**
