### PR TITLE
Turkish translation

### PR DESCRIPTION
**Pull request by firateski**
- Turkish translation
- Added Turkish flag

Also, thank you for this project.

### CODE REVIEW

**Comment by justinclift** [comment]
Thank you, that's awesome. :grimacing:

One thing though, would you be ok to combine all of these commits into a single one?  If you're not sure how to do that, just let me know and I can do it (no problem). :smile:

**Comment by firateski** [comment]
I'm new on Git yet. It would be great if you help me :grimacing:

**Comment by justinclift** [comment]
Sure.  I've just tried this out, and it doesn't seem to have put the flag file into the correct location (for OSX at least):

screen shot 2016-03-20 at 13 21 33

It looks like this is close though, so please keep going. :smile:

**Comment by firateski** [comment]
I think the problem was solved. If the problem persists, just let me know. :grin:

**Comment by glawrence** [comment]
If you need help merging commits then please see https://github.com/sqlitebrowser/sqlitebrowser/wiki/Merging-Commits which should help, if it does not then please let us know

**Comment by firateski** [comment]
There was a problem about flag location. I tried to fix it. If there isn't any problem now. You can merge commits for me :grin:

**Comment by justinclift** [comment]
Cool.  Will take a look soon. :smile:

**Comment by justinclift** [comment]
Yep, that fixed it:

screen shot 2016-03-20 at 18 15 39

screen shot 2016-03-20 at 18 19 17

I've combined all of the commits into a single one, and push that to our master branch.  So, your code is now live and will be in the nightly updates, plus the future releases.

Thank you @firateski. :smile:

**Comment by firateski** [comment]
Thanks a lot for your help :smile:

**Comment by justinclift** [comment]
You're welcome.  If you want to update the translation at any stage, or add further strings which are not yet translated, please do. :smile:

**Comment by firateski** [comment]
Of course, I will continue to improve. :+1:

**Pull request closed without merging**
