### PR TITLE
update German translation

### PR DESCRIPTION
**Pull request by horst-p-w-neubauer**
update German translation
done
* all unfinished
* 'push*' to 'übertragen'
translation decisions documented on [https://github.com/sqlitebrowser/sqlitebrowser/wiki/Translations]

### CODE REVIEW

**Comment by horst-p-w-neubauer** [comment]
What about the 'vanished' items - is it common to remove them before you commit?

**Comment by justinclift** [comment]
AFAIK we just leave the vanished stuff alone.  It doesn't hurt anything. :smile:

**Comment by justinclift** [comment]
With the "done" bit, is that meaning this is ready to merge too? :smile:

**Comment by horst-p-w-neubauer** [comment]
Yes!

**Comment by justinclift** [comment]
Awesome. :smile:

**Pull request merged**
