### PR TITLE
Arabic translation

### PR DESCRIPTION
**Pull request by 0xbsec**
Added Arabic translation.

### CODE REVIEW

**Comment by justinclift** [comment]
Excellent, this seems like a good start. :smile:

One small problem with it is showing up... the flag seems to be missing in the drop down list:

screen shot 2016-07-11 at 06 26 04

Are you ok to investigate and fix that?

**Comment by innermous** [comment]
@justinclift  @0xbsec I already did that. 
```diff
 src/translations/flags/flags.qrc | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/src/translations/flags/flags.qrc b/src/translations/flags/flags.qrc
index 4d240dc..8b7615d 100644
--- a/src/translations/flags/flags.qrc
+++ b/src/translations/flags/flags.qrc
@@ -1,6 +1,6 @@
 <RCC>
     <qresource prefix="/flags">
-        <file alias="ar_AR">ar.png</file>
+        <file alias="ar_EG">ar.png</file>
         <file alias="de_DE">de.png</file>
         <file alias="es_ES">es.png</file>
         <file alias="en_US">us.png</file>
-- 
2.9.0
```

**Comment by 0xbsec** [comment]
@justinclift Thanks.
@innermous Nice catch, it's truer to be 'ar_SA' instead of 'ar_EG'.

**Comment by justinclift** [comment]
@0xbsec Yep, the flag is showing up in the drop down list now:

screen shot 2016-07-11 at 19 06 48

Guessing you'll keep adding more translated strings to this issue?  If that's the case, just let us know when you're happy with things, and we'll merge it. :smile:

**Comment by 0xbsec** [comment]
@justinclift `sqlb_ar.ts` is done. You can merge it.

**Comment by justinclift** [comment]
Thanks @0xbsec, done. :smile:

(Btw, sorry team.  I forgot to choose the "squash commit" option for the merge. 😦 )

@0xbsec As a thought, some of the main strings in the user interface still seem to be in English for me.  Is that how it should be?

screen shot 2016-07-11 at 19 36 49

**Comment by 0xbsec** [comment]
@justinclift Most welcome. No they should be translated. Same thing happening with French translation ( and maybe others ), example: `Revert Changes` should be translated ( [here ](https://github.com/sqlitebrowser/sqlitebrowser/blob/master/src/translations/sqlb_fr.ts#L1069)), but it isn't translated in the GUI either.

**Comment by justinclift** [comment]
Thanks @0xbsec.  Didn't know that was happening.  I've just created issue #643 about it, so we can investigate it properly. :smile:

**Comment by justinclift** [comment]
Yeah, soory @innermous.  I was tempted to manually merge them and force push a single commit onto our main repo... but that's generally bad practise.  So I've resisted. 😧

**Comment by innermous** [comment]
@justinclift just imo, but in this special case it would be better than a pyle of commits with similar commit messages. Especially if you brought force push immediately before anyone ever fetched changes.
But what 's done that's done :smile:

**Comment by justinclift** [comment]
Yeah, next time one of us forgets, it probably would be better to manually merge then force push. :smile:

**Comment by innermous** [comment]
@justinclift I always check log via *tig* three times before push :laughing:

**Pull request merged**
