### PR TITLE
Update some Simplified Chinese text

### PR DESCRIPTION
**Pull request by bssthu**
Update some obsolete translations. These translations used to work in previous version.

### CODE REVIEW

**Comment by justinclift** [comment]
@bssthu Thanks, I'll get to this in a few hours, and take screenshots so you can double check things are ok. :smile:

**Comment by justinclift** [comment]
Lots of screenshots, with your updated translation included. :smile:

There are still a few places with English strings showing.  Are you interested in getting those done too?

screen shot 2016-10-18 at 23 54 34
screen shot 2016-10-18 at 23 53 59
screen shot 2016-10-18 at 23 53 51
screen shot 2016-10-18 at 23 53 44
screen shot 2016-10-18 at 23 53 40
screen shot 2016-10-18 at 23 53 27
screen shot 2016-10-18 at 23 53 17
screen shot 2016-10-18 at 23 52 40
screen shot 2016-10-18 at 23 52 35
screen shot 2016-10-18 at 23 52 30
screen shot 2016-10-18 at 23 52 25
screen shot 2016-10-18 at 23 52 20
screen shot 2016-10-18 at 23 52 12
screen shot 2016-10-18 at 23 52 07
screen shot 2016-10-18 at 23 52 01
screen shot 2016-10-18 at 23 51 55
screen shot 2016-10-18 at 23 51 49
screen shot 2016-10-18 at 23 51 28
screen shot 2016-10-18 at 23 51 22
screen shot 2016-10-18 at 23 51 15
screen shot 2016-10-18 at 23 51 08
screen shot 2016-10-18 at 23 51 02
screen shot 2016-10-18 at 23 50 57
screen shot 2016-10-18 at 23 50 47
screen shot 2016-10-18 at 23 50 43
screen shot 2016-10-18 at 23 49 58
screen shot 2016-10-18 at 23 49 52
screen shot 2016-10-18 at 23 49 45
screen shot 2016-10-18 at 23 49 37
screen shot 2016-10-18 at 23 49 31
screen shot 2016-10-18 at 23 49 27
screen shot 2016-10-18 at 23 48 54
screen shot 2016-10-18 at 23 48 48
screen shot 2016-10-18 at 23 48 41
screen shot 2016-10-18 at 23 48 32
screen shot 2016-10-18 at 23 48 22
screen shot 2016-10-18 at 23 48 11
screen shot 2016-10-18 at 23 48 08
screen shot 2016-10-18 at 23 47 50
screen shot 2016-10-18 at 23 46 58
screen shot 2016-10-18 at 23 46 52
screen shot 2016-10-18 at 23 46 47
screen shot 2016-10-18 at 23 46 41
screen shot 2016-10-18 at 23 46 34
screen shot 2016-10-18 at 23 46 25
screen shot 2016-10-18 at 23 45 55
screen shot 2016-10-18 at 23 45 44
screen shot 2016-10-18 at 23 44 25

**Comment by bssthu** [comment]
No problem, I'll translate them soon.

**Comment by bssthu** [comment]
I created a new PR here: #840

**Pull request closed without merging**
