### PR TITLE
Updating Travis build to Ubuntu 18.04

### PR DESCRIPTION
**Pull request by MKleusberg**
Don't mind this. I'm just using this PR to make Travis run the new file.

### CODE REVIEW

**Comment by MKleusberg** [comment]
@deepsidhu1313 Any idea how we can fix this issue with the AppImage creation?
```
$ ./linuxdeployqt-6-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage
linuxdeployqt 5 (commit 37631e5), build 631 built on 2019-01-25 22:47:58 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
still-supported mainstream distribution, which currently is glibc 2.20.
This is so that the resulting bundle will work on most still-supported Linux distributions.
For more information, please see
https://github.com/probonopd/linuxdeployqt/issues/340
The command "./linuxdeployqt-6-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage" exited with 1.
```

I updated the Ubuntu release for the Travis build from 16.04 to 18.04 and it's "too new" now :smile:

**Comment by chrisjlocke** [comment]
"Edit" and "Undo" 😉😁😁

**Comment by mgrojo** [comment]
This is the second time I stumble upon this. It's all explained in the linked issue, but summarizing: the author of linuxdeployqt promotes using the oldest supported distribution from generating AppImages, since those images will be compatible with all the next distribution releases. This is convenient, but he has made that into a requirement and many people complain in the issue

**Comment by deepsidhu1313** [comment]
Let me see if we can fork his code and create binary for ourselves.

**Comment by deepsidhu1313** [comment]
@MKleusberg can you try passing this argument. `-unsupported-allow-new-glibc` so that will make 

```
./linuxdeployqt-6-x86_64.AppImage appdir/usr/share/applications/*.desktop -appimage -unsupported-allow-new-glibc
```

**Comment by justinclift** [comment]
@MKleusberg Is this PR still needed? :smile:

**Comment by MKleusberg** [comment]
> @MKleusberg Is this PR still needed? smile

Yes! I just forgot about it and didn't have much time lately anyway. It might actually work better now too because Ubuntu 16.04 reached the end of its general support in the meantime. However, Travis-CI.org stopped working too in June and we have to migrate to Travis-CI.com before continuing here. I'm currently trying their migration wizard which is still in beta though.

**Comment by MKleusberg** [comment]
The Travis integration is working again. I'll run another test or two and then have another go at this branch.

**Comment by MKleusberg** [comment]
I have finally merged this :tada: We're now building for Ubuntu bionic beaver and newer. The new Travis config is a bit easier to read now in my opinion and the build seems a tiny bit faster too.

**Comment by justinclift** [comment]
Awesome! :smile:

**Comment by mgrojo** [comment]
I'm getting a very funny window when executing latest AppImage :smile:
image

**Comment by justinclift** [comment]
Heh Heh Heh.  Font size seems a little bit off there... :wink:

**Comment by MKleusberg** [comment]
Looks like this for me:
Screenshot_20210811_190258
As you can see the theme is a bit off and all the icons are missing. I have no idea how it looked before because the previous version of the AppImage wouldn't start on my system because of some missing library or such. Maybe the stylesheet and the icons aren't included in the file or aren't loaded correctly?

**Comment by sandman7920** [comment]
>As you can see the theme is a bit off and all the icons are missing

Is qt5-svg plugin installed?

**Comment by MKleusberg** [comment]
Just had the same idea :smile: With [this patch](https://github.com/sqlitebrowser/sqlitebrowser/commit/254df474e104c14434bc359757addd77c0947140) the icons are working now.

**Pull request closed without merging**
