### PR TITLE
update Spanish translation

### PR DESCRIPTION
**Pull request by lulol**
update Spanish translation

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @lulol, that was pretty quick. :smile:

Should it be merged as is, or would it be better to make a bunch of screenshots showing the strings at runtime first?

**Comment by lulol** [comment]
I think that is not necessary to take screenshots. The translation was mostly straightforward.

The only thing that may worth to check is if the resulting text formatting looks right for the key cypher dialog and the Plot load button tooltip, since in both there were too long lines I did split them in the translation.

**Comment by justinclift** [comment]
The Plot loading tooltip seems fine (bottom right corner):
plot_load_tooltip

The key cypher dialog I'll check later, when I switch to my OSX desktop later on tonight. :smile:

**Comment by justinclift** [comment]
They SQLCipher dialog seems ok too, so this does look good to merge as-is:
screen shot 2017-07-24 at 12 58 26

Thanks heaps @lulol. :smile:

**Pull request merged**
