### PR TITLE
Update Portuguese translation for v3.11.x

### PR DESCRIPTION
**Pull request by bernardosulzbach**
This should cover it.

The "Sources and Forms" pane is empty for Portuguese, but apparently it works in other languages. Can anyone who knows about Linguist give some insight?

screenshot from 2019-01-10 05-28-59

### CODE REVIEW

**Comment by justinclift** [comment]
Hmmm, that's weird.  It was due to my using an older version of the Qt `lupdate` program instead of the most recent?

I'll merge this as is, then generate the pt_BR strings in the `v3.11.x` branch using the latest Qt version of `lupdate`.  Lets see if that makes a difference. :smile:

**Comment by justinclift** [comment]
Downloading the newest Qt again now.  It's going slow, so might be a later on tonight thing (or even tomorrow). :smile:

**Comment by justinclift** [comment]
Trying stuff out now.  Like yourself, the "Sources and forms" panel isn't working when I try the pt_BR .ts file.  This time around I'm using Qt Linguist that comes with Qt 5.12.0.

It's working ok with the [de .ts file](ebrowser/blob/a3658de532d308c2c8d836f9d635742e05122792/src/translations/sqlb_de.ts) though.

qt_linguist-sources_and_forms

Not sure how useful that is, but maybe loading the de one for guidance when needed would work?

**Comment by mgrojo** [comment]
For some reason the Portuguese translation file lacks source code locations and then linguist doesn't show the widgets or source code quotes. Probably the file was created with this command line:

`lupdate -locations none sqlitebrowser.pro`

And then lupdate continues respecting how the file was created. I've been able to fix it executing this:

`lupdate -locations absolute sqlitebrowser.pro `

I've not commited the result, because it is probably better that you do it yourself in your branch, so there are no conflicts later, @bernardosulzbach.

There is an advantage in lacking source code locations: the translation file is then not changing only because the surrounding code has changed. But all the other languages have them, and lacking the context while translating is worse than having trivial changes in the files related to line numbers. I guess you'll prefer to ammend the file.

**Comment by mgrojo** [comment]
> I've not commited the result, because it is probably better that you do it yourself in your branch, so there are no conflicts later, @bernardosulzbach.

Forget about this, I see now that the pull request is already merged. But I leave it to you nevertheless, unless you want me to commit it.

**Comment by bernardosulzbach** [comment]
> But all the other languages have them, and lacking the context while translating is worse than having trivial changes in the files related to line numbers.

I agree. In Portuguese and many other languages, we must know how a verb is being used to translate it correctly, so context is even more crucial than for English.

> Forget about this, I see now that the pull request is already merged. But I leave it to you nevertheless, unless you want me to commit it.

It would be very kind of you @mgrojo to do it for me.

**Comment by mgrojo** [comment]
> Are you able to check if the new Persian language file has the same problem? It was created recently, but I'm not sure what command I used to create it. :smile:

The Persian file is OK. The TS files have the problem when they are explicitly created with `lupdate -locations none file.pro`. The default value for `-locations` in the creation is `absolute` (what we want). And then, while updating the file, the default is respecting whatever format the file currently has.

**Comment by justinclift** [comment]
Thanks @mgrojo. :smile:

**Pull request merged**
