### PR TITLE
Execute SQL tab: Add search bar for SQL code #191

### PR DESCRIPTION
**Pull request by mgrojo**
The find operations in QScintilla are used for implementing a find frame in the SQL Editor of the main window. A checkable tool button is added in the SQL Editor toolbar for showing and hiding this frame.

There are check boxes for Whole Words, Case Sensitive and Regular Expressions. The QScintilla facilities in the findFirst method are used for the implementation.

Possible improvements: there shouldn't be a splitter handle between SQL Editor and Find Frame. The find icon in the toolbar should be magnifying glass or binoculars, but we lack those in the resources. I'd need help for implementing these changes.

Further development: there is a replace function in QScintilla that could be used in a new Find/Replace dialog.

Please, review for possible code or UI improvements. If there are no comments, I will merge it in the following days.

### CODE REVIEW

**Comment by chrisjlocke** [comment]
Haven't tested this (I tend to only run the nightlies) but well done for implementing this - looks a handy feature.  My SQL queries are usually quite small though, so would probably more use the 'replace' than 'find' feature - but its still a good feature to have, especially if the editor has the 'tools' already.
👍

**Comment by MKleusberg** [comment]
Thanks, @mgrojo. This looks really good 👍 Despite the points you've already mentioned I noticed some more minor things:
* The search backwards button only ever selects the last occurrence but doesn't seem to move backwards from there like
* When you have multiple SQL tabs opened, open the find toolbar for one of them, and then toggle between them, the find toolbar is only shown for the original tab but the check button stays checked the entire time.

I'll add a new icon for the button in a second from the same icon package like the other icons. I'll also see what I can do about the splitter :smile:

**Comment by MKleusberg** [comment]
Hmm, I have to correct my second point. It only happens if the text you're searching for is repeated multiple times with nothing in between, like this:
```
testtesttesttest
```
Now search backwards for ```test```. It will only find every second occurrence of the string. But this seems to be a QScintilla problem...

**Comment by MKleusberg** [comment]
Ok I think I have fixed the issues mentioned by you (icon and splitter) and the issue mentioned by me (multiple tabs). The other issue seems to be in QScintilla and I think we can ignore it for this PR.

So I think we can just merge this now :smile: If we feel like implementing the replace feature or something else (maybe Escape for hiding the search bar) we can always add this later.

Thanks again for adding this 😃 This feature was missing for such a long time now and I'm glad it has finally made it :wink:

**Comment by mgrojo** [comment]
@MKleusberg, thanks for the improvements and comments. I had already noticed that the QScintilla API for finding is not well thought. I think it should be something like setFindOptions and then findForward or findBackwards. 

By the way, where is that icon package we use, just in case I'd need to add one more?

**Comment by MKleusberg** [comment]
So far we're using this icon theme: http://www.famfamfam.com/lab/icons/silk/ :smile:

**Comment by pamtbaau** [comment]
Version 3.10.99 (Nov 16 2017)

Just found the search&replace option. Nice...

Found a bit odd behaviour when typing the search term: For each character typed the highlight advances to the next hit. 

In the attached example, typing 'w' will highlight the first 'w' on line 1. Typing 'wh' wil advance the hightlight to 'wh' on line 2... etc. Typing 'when' will highlight 'when' on line 4. Deleting a char will also advance to the next hit. Searching will loop when necessary.

search-replace

**Comment by justinclift** [comment]
Cool, good catch @pamtbaau.  Guessing it won't be too hard to fix. :smile:

**Comment by mgrojo** [comment]
This would be due to the odd API that Scintilla has. I suppose that it is
not very difficult to solve.

**Comment by mgrojo** [comment]
@pamtbaau Thank you for the precised report. That should be fixed now. Could you please try again the search in the next nightly build?

**Comment by pamtbaau** [comment]
Version 3.10.99 (Nov 17 2017)

Fixed: Search does not advance any more. 
search1

Issues:
- When deleting the search term char by char, the last hightlighed char remains highlighted. 
search2

- When selecting entire search term and delete all at once, entire hightlighted text remains highlighed.
search3

**Comment by chrisjlocke** [comment]
Is the [...] button needed?

image

As far as I can tell, this just closes the search window again, which the button in the main toolbar does?

**Comment by mgrojo** [comment]
That button is supossed to have a close icon. I selected an icon from the
theme option. Is that only working in Linux? Some users would expect that
icon for closing the search bar, just like other applications have. It must
show a proper icon, though. I will use one from our resources.

**Comment by mgrojo** [comment]
@chrisjlocke I've added a resource icon for close and added to the find bar in 24a573dc688a0b48313baeebb06636eb341d436d

About the previous/next buttons: I've modelled the find bar like the one in Firefox. In LibreOffice is similar, at least concerning the order of these buttons.  The one in qtcreator has the same order. I think they just follow the natural order for the concepts previous/next. But if you want quick access to next, just press Return or F3. Shift+F3 searches for previous.

**Pull request merged**
