### PR TITLE
Updated French translation

### PR DESCRIPTION
**Pull request by justinclift**

### CODE REVIEW

**Comment by justinclift** [comment]
@mvt91 I'll go through this in detail soon, making screenshots to verify things, and look into the Plot view too. :smile:

(the other bits I'll answer via email :wink:)

**Comment by justinclift** [comment]
Thanks Michel, this also looks very complete. :smile:

There are a few strings I'm not sure of though:

* AboutDialog.ui - Missing space on the end of two strings?

* EditDialog.ui - Unsure about this.  The `:` seems to be in the wrong position, but both the .ts file and .cpp files seem to have it correct.  So I'm not sure what is going wrong. 😕 

 `tr("Type of data currently in cell: %1 Image")`

 ```
 <message>
     <location filename="../EditDialog.ui" line="187"/>
     <source>Type of data currently in cell</source>
     <translation>Type des données actuellement dans la cellule</translation>
 </message>
 ```

* ExportSqlDialog.ui - Is the dialog heading correct?

The screenshots below might help.  I'll look into the plot settings shortly as well.  It's not an area of our code I have investigated before, but now is a good time to start. :smile:

- [ ] AboutDialog.ui
screen shot 2016-08-13 at 12 51 53
- [x] CipherDialog.ui
screen shot 2016-08-13 at 12 54 50
- [x] ColumnDisplayFormatDialog.ui
screen shot 2016-08-13 at 12 55 52
- [x] CreateIndexDialog.ui
screen shot 2016-08-13 at 12 57 14
- [ ] EditDialog.ui
screen shot 2016-08-13 at 13 05 16
screen shot 2016-08-13 at 13 05 23
screen shot 2016-08-13 at 13 05 44
- [x] EditTableDialog.ui
screen shot 2016-08-13 at 13 35 40
- [x] ExportCsvDialog.ui
screen shot 2016-08-13 at 13 37 18

- [ ] ExportSqlDialog.ui
screen shot 2016-08-13 at 13 38 24

- [x] ImportCsvDialog.ui
screen shot 2016-08-13 at 13 41 46
- [x] MainWindow.ui
screen shot 2016-08-13 at 12 37 49
screen shot 2016-08-13 at 12 38 00
screen shot 2016-08-13 at 12 38 08
screen shot 2016-08-13 at 12 38 53
- [x] PreferencesDialog.ui
screen shot 2016-08-13 at 12 41 10
screen shot 2016-08-13 at 12 41 13
screen shot 2016-08-13 at 12 41 37
screen shot 2016-08-13 at 12 41 48
screen shot 2016-08-13 at 12 42 02
screen shot 2016-08-13 at 12 42 18
- [x] VacuumDialog.ui
screen shot 2016-08-13 at 12 47 52

**Comment by mvt91** [comment]
Hi Justin,

I finished it early this morning ;)

I'll have a look during this WE.

Do you have a dead line for a new release (4.0.00 ? - first picture, 
from 3.9.99).

Some words are defined once but used in different contexts.
In that case I choose an infinitive verb e.g. Autoriser to avoid 
autorisé, autorisée or autorisées.

Thanks for all these pictures. Very useful.

How to compile the program under Mint ?
Qt is OK but it is the 5.x release...

For the view with SQLCipher, is the hight of the window variable ?
I'll add some CR (or <br>, I don't have the file right now).

**Comment by justinclift** [comment]
Ahhh, yeah.  We're creating the release packages for our new "3.9.0 beta 1" release right now.  That should be released later on today.  If no serious bugs show up, then "3.9.0" full release will probably be next weekend. 😁 

Btw, a  separate branch ("[v3.9.x](https://github.com/sqlitebrowser/sqlitebrowser/blob/v3.9.x/src/translations/sqlb_fr.ts)") was created in git for this new 3.9.x series just a few days ago.

I should have applied your .ts file to that branch for the screenshots, but it's not important because there are no English string differences yet.  Between 3.9.x branch, and our current main development branch "master" for 3.10.x that is.

For compiling the program under Mint, in theory it should be the same as for Qt4:

&nbsp; &nbsp; https://github.com/sqlitebrowser/sqlitebrowser/blob/master/BUILDING.md#ubuntu-linux

Just... see if there is a Qt5 version `libqt5-dev` (?) of the development files instead.  DB4S __should__ compile with either Qt4, or Qt5.

But having both `libqt4-dev` & `libqt5-dev` on the same system at the same time might confuse it.  One way to find out. :smile:

**Comment by justinclift** [comment]
With the height of the SQLCipher window, we should be able to make it variable.  It does look too wide at the moment for almost every language.

So, feel free to put in some line breaks, and we can adjust the sizing of that window before the proper 3.9.0 release next weekend. :smile:

**Comment by justinclift** [comment]
This is looking Awesome now @mvt91! Thank you heaps! 😁 

With the Plot dock... I haven't looked at it yet.  It will need to be a task for tomorrow instead of today, as myy brain is fairly melted from looking at the computer too long atm. :wink:

- [x] AboutDialog.ui
screen shot 2016-08-14 at 19 35 04
- [x] CipherDialog.ui
screen shot 2016-08-14 at 19 35 58
- [x] ColumnDisplayFormatDialog.ui
screen shot 2016-08-14 at 19 37 56
- [x] CreateIndexDialog.ui
screen shot 2016-08-14 at 19 40 15
- [x] EditDialog.ui
screen shot 2016-08-14 at 20 11 54
screen shot 2016-08-14 at 20 11 59
screen shot 2016-08-14 at 20 12 18
screen shot 2016-08-14 at 20 12 28
- [x] EditTableDialog.ui
screen shot 2016-08-14 at 20 14 44
- [x] ExportCsvDialog.ui
screen shot 2016-08-14 at 20 15 39
screen shot 2016-08-14 at 20 15 45

- [x] ExportSqlDialog.ui

screen shot 2016-08-14 at 20 17 32
- [x] ImportCsvDialog.ui
screen shot 2016-08-14 at 20 18 41
- [x] MainWindow.ui
screen shot 2016-08-14 at 19 41 03
screen shot 2016-08-14 at 19 41 15
screen shot 2016-08-14 at 19 41 48
screen shot 2016-08-14 at 19 42 00
screen shot 2016-08-14 at 20 02 36
screen shot 2016-08-14 at 20 03 02
screen shot 2016-08-14 at 20 03 22
screen shot 2016-08-14 at 20 03 45
screen shot 2016-08-14 at 20 04 50
- [x] PreferencesDialog.ui
screen shot 2016-08-14 at 20 07 47
screen shot 2016-08-14 at 20 07 52
screen shot 2016-08-14 at 20 08 09
screen shot 2016-08-14 at 20 08 15
screen shot 2016-08-14 at 20 08 32
screen shot 2016-08-14 at 20 08 37
- [x] VacuumDialog.ui
screen shot 2016-08-14 at 20 10 45

**Comment by mvt91** [comment]
Hi Justin,

That looks good.
I'll change Cipher again.

What's about ExportCSVDialog. It seems the list box (field separator) KO. Have
to replace Tabulation bu Tab. ?

In main dialog, I have to change from "masculin" to éféminin" in synchronization
: Arrêtée, Normale, Complète", if these texts are used here only.

I'll send you the file later...


Quoting Justin Clift <notifications@github.com>:

> This is looking Awesome now @mvt91! Thank you heaps! ðŸ˜
>
> With the Plot dock... I haven't looked at it yet.  It will need to be a task
> for tomorrow instead of today, as myy brain is fairly melted from looking at
> the computer too long atm. :wink:
>
> - [x] AboutDialog.ui
> screen shot 2016-08-14 at 19 35
>
04
> - [x] CipherDialog.ui
> screen shot 2016-08-14 at 19 35
>
58
> - [x] ColumnDisplayFormatDialog.ui
> screen shot 2016-08-14 at 19 37
>
56
> - [x] CreateIndexDialog.ui
> screen shot 2016-08-14 at 19 40
>
15
> - [x] EditDialog.ui
> screen shot 2016-08-14 at 20 11
>
54
> screen shot 2016-08-14 at 20 11
>
59
> screen shot 2016-08-14 at 20 12
>
18
> screen shot 2016-08-14 at 20 12
>
28
> - [x] EditTableDialog.ui
> screen shot 2016-08-14 at 20 14
>
44
> - [x] ExportCsvDialog.ui
> screen shot 2016-08-14 at 20 15
>
39
> screen shot 2016-08-14 at 20 15
>
45
>
> - [x] ExportSqlDialog.ui
>
> screen shot 2016-08-14 at 20 17
>
32
> - [x] ImportCsvDialog.ui
> screen shot 2016-08-14 at 20 18
>
41
> - [x] MainWindow.ui
> screen shot 2016-08-14 at 19 41
>
03
> screen shot 2016-08-14 at 19 41
>
15
> screen shot 2016-08-14 at 19 41
>
48
> screen shot 2016-08-14 at 19 42
>
00
> screen shot 2016-08-14 at 20 02
>
36
> screen shot 2016-08-14 at 20 03
>
02
> screen shot 2016-08-14 at 20 03
>
22
> screen shot 2016-08-14 at 20 03
>
45
> screen shot 2016-08-14 at 20 04
>
50
> - [x] PreferencesDialog.ui
> screen shot 2016-08-14 at 20 07
>
47
> screen shot 2016-08-14 at 20 07
>
52
> screen shot 2016-08-14 at 20 08
>
09
> screen shot 2016-08-14 at 20 08
>
15
> screen shot 2016-08-14 at 20 08
>
32
> screen shot 2016-08-14 at 20 08
>
37
> - [x] VacuumDialog.ui
> screen shot 2016-08-14 at 20 10
>
45

**Comment by mvt91** [comment]
Done.

I saw "Supprimer la table" I've changed to "Supprimer une table" to harmonize
with the others texts.

Have a good "end of day"... Tomorow; I've to work (again :) )

Quoting Justin Clift <notifications@github.com>:

> This is looking Awesome now @mvt91! Thank you heaps! 😁
>
> With the Plot dock... I haven't looked at it yet.  It will need to be a task
> for tomorrow instead of today, as myy brain is fairly melted from looking at
> the computer too long atm. :wink:
>
> - [x] AboutDialog.ui
> screen shot 2016-08-14 at 19 35
>
04
> - [x] CipherDialog.ui
> screen shot 2016-08-14 at 19 35
>
58
> - [x] ColumnDisplayFormatDialog.ui
> screen shot 2016-08-14 at 19 37
>
56
> - [x] CreateIndexDialog.ui
> screen shot 2016-08-14 at 19 40
>
15
> - [x] EditDialog.ui
> screen shot 2016-08-14 at 20 11
>
54
> screen shot 2016-08-14 at 20 11
>
59
> screen shot 2016-08-14 at 20 12
>
18
> screen shot 2016-08-14 at 20 12
>
28
> - [x] EditTableDialog.ui
> screen shot 2016-08-14 at 20 14
>
44
> - [x] ExportCsvDialog.ui
> screen shot 2016-08-14 at 20 15
>
39
> screen shot 2016-08-14 at 20 15
>
45
>
> - [x] ExportSqlDialog.ui
>
> screen shot 2016-08-14 at 20 17
>
32
> - [x] ImportCsvDialog.ui
> screen shot 2016-08-14 at 20 18
>
41
> - [x] MainWindow.ui
> screen shot 2016-08-14 at 19 41
>
03
> screen shot 2016-08-14 at 19 41
>
15
> screen shot 2016-08-14 at 19 41
>
48
> screen shot 2016-08-14 at 19 42
>
00
> screen shot 2016-08-14 at 20 02
>
36
> screen shot 2016-08-14 at 20 03
>
02
> screen shot 2016-08-14 at 20 03
>
22
> screen shot 2016-08-14 at 20 03
>
45
> screen shot 2016-08-14 at 20 04
>
50
> - [x] PreferencesDialog.ui
> screen shot 2016-08-14 at 20 07
>
47
> screen shot 2016-08-14 at 20 07
>
52
> screen shot 2016-08-14 at 20 08
>
09
> screen shot 2016-08-14 at 20 08
>
15
> screen shot 2016-08-14 at 20 08
>
32
> screen shot 2016-08-14 at 20 08
>
37
> - [x] VacuumDialog.ui
> screen shot 2016-08-14 at 20 10
>
45

**Comment by justinclift** [comment]
Cool. :grin:

When you saw "Done", are you meaning "Justin, please check your email for the new .ts file?"

Asking because if you tried to attach the file to this GitHub Issue, that doesn't work.  The GitHub Issue system seems to ignore attachments.

**Comment by justinclift** [comment]
By the way, we created a "[Translators](https://github.com/orgs/sqlitebrowser/teams/translators)" team for the sqlitebrowser org here on GitHub.

It doesn't give write access to anything, but shows you're a "member of the team" for anyone that looks. :smile:

Any interest in being added to that?

**Comment by justinclift** [comment]
Adding these, just in case they're helpful. :smile:

screen shot 2016-08-15 at 17 02 57

screen shot 2016-08-15 at 17 03 08

screen shot 2016-08-15 at 17 03 16

screen shot 2016-08-15 at 17 03 20

screen shot 2016-08-15 at 17 03 24

**Comment by justinclift** [comment]
Looking at the ExportCsvDialog, it seems ok to me. :smile:

screen shot 2016-08-15 at 17 07 05
screen shot 2016-08-15 at 17 05 37
screen shot 2016-08-15 at 17 06 23
screen shot 2016-08-15 at 17 06 41

The `Field separator` drop down in English for comparison:

screen shot 2016-08-15 at 17 09 17

**Comment by justinclift** [comment]
@mvt91 Is this ok to merge as-is? :smile:

**Comment by mvt91** [comment]
Hi Justin

Yes

Selon Justin Clift <notifications@github.com>:

**Comment by justinclift** [comment]
Fantastic!  Thank you for putting the time into this @mvt91. :smile:

**Comment by mvt91** [comment]
Cool ;)
Selon Justin Clift <notifications@github.com>:

**Pull request merged**
