### PR TITLE
Correct CMake Warning Messages - QCustomPlot, QHexEdit

### PR DESCRIPTION
**Pull request by scottfurry**
Correct text case usage in local FindXXX.cmake and CMakeLists.txt files.
During usage, warning messages appear due to differences in file name/library name case.
    
Resolution is to match file name case with variable name case where it appears in all CMake files.
i.e. file name - QCustomPlot.cmake
     variable name QCustomPlot_{LIBRARIES, INCLUDE_DIRS, et al}
    
Affects CMakeLists.txt and cmake/FindXXX.cmake files.

### CODE REVIEW

**Comment by scottfurry** [comment]
CMake (local using version 3.17.0) would produce the following in build logs:
```
CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:272 (message):
  The package name passed to `find_package_handle_standard_args`
  (QCUSTOMPLOT) does not match the name of the calling package (QCustomPlot).
  This can lead to problems in calling code that expects `find_package`
  result variables (e.g., `_FOUND`) to follow a certain pattern.
```
Resolution is to correct case usage as detailed above.

**Comment by justinclift** [comment]
Is this ready to go?  If so, lets merge it and see if/what anything breaks in the next nightly builds. :smile:

**Comment by scottfurry** [comment]
Yup. Ready to 'rock and roll'

**Comment by scottfurry** [comment]
@justinclift - This PR wasn't pulled into v3.12.0.

**Comment by justinclift** [comment]
k.  Should we add it to the `v3.12.x` branch - so it's part of `3.12.1` - or should would it be better as part of our next major release series?

**Comment by scottfurry** [comment]
CMake is complaining _for now_. I would add it to v3.12.x branch as a prudent measure to head off future bug reports.

**Comment by justinclift** [comment]
No worries.  Are you ok to cherry-pick it across? :smile:

**Comment by scottfurry** [comment]
I'm comfortable making pull requests but I'm unsure of _exact_ process project uses to manage PR integration. Would you mind doing it for this one, please?
Then you and I can compare notes on gitter for future PR's.

**Comment by justinclift** [comment]
No worries. :smile:

The steps for cherry picking the commit from `master` to `v3.12.x` and pushing that to GitHub were:

```
$ git checkout v3.12.x
Switched to branch 'v3.12.x'
Your branch is up to date with 'origin/v3.12.x'.

$ git cherry-pick 4e7669bd0c6d9ca2c57b597f7d67df0e96bd12de
[v3.12.x 115aa00a] Correct CMake Warning Messages - QCustomPlot, QHexEdit
 Author: Scott Furry <scott.wl.furry@gmail.com>
 Date: Thu Apr 23 04:43:56 2020 -0600
 3 files changed, 43 insertions(+), 43 deletions(-)

$ git push origin v3.12.x
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 8 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 1.83 KiB | 1.83 MiB/s, done.
Total 6 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
To https://github.com/sqlitebrowser/sqlitebrowser
   0dbe9b5f..115aa00a  v3.12.x -> v3.12.x
```

**Pull request merged**
