### PR TITLE
update German translation

### PR DESCRIPTION
**Pull request by FriedrichFroebel**

### CODE REVIEW

**Comment by justinclift** [comment]
Thanks @FriedrichFroebel, that's excellent! :smile:

I'll go through this soon.

**Comment by justinclift** [comment]
Thanks @FriedrichFroebel, this looks really good. :smile:

The only bit I'm unsure of is the "Edit PRAGMAs" tab in MainWindow.ui.

The terms on the left are in English, however the drop down options for them are in German.

With the other translations, it's been either one or the other, so the mix is a bit strange.  If that's the best way however, it's fine here. :smile:

- [x] Menus

screen shot 2016-08-17 at 17 57 59
screen shot 2016-08-17 at 17 58 08
screen shot 2016-08-17 at 17 58 18
screen shot 2016-08-17 at 17 58 23
screen shot 2016-08-17 at 17 58 28
- [x] AboutDialog.ui
screen shot 2016-08-17 at 17 37 24
- [x] CipherDialog.ui
screen shot 2016-08-17 at 17 48 21
- [x] ColumnDisplayFormatDialog.ui
screen shot 2016-08-17 at 17 49 04
- [x] CreateIndexDialog.ui
screen shot 2016-08-17 at 17 50 18
- [x] EditDialog.ui
screen shot 2016-08-17 at 17 51 09
screen shot 2016-08-17 at 17 51 17
screen shot 2016-08-17 at 17 51 21
- [x] EditTableDialog.ui
screen shot 2016-08-17 at 17 52 20
- [x] ExportCsvDialog.ui
screen shot 2016-08-17 at 17 52 53
screen shot 2016-08-17 at 17 53 06
screen shot 2016-08-17 at 17 53 18
screen shot 2016-08-17 at 17 53 32
- [x] ExportSqlDialog.ui

screen shot 2016-08-17 at 17 54 45

- [x] ImportCsvDialog.ui
screen shot 2016-08-17 at 17 55 47
screen shot 2016-08-17 at 17 55 51
screen shot 2016-08-17 at 17 56 03
screen shot 2016-08-17 at 17 56 21
- [ ] MainWindow.ui
screen shot 2016-08-17 at 17 37 54
screen shot 2016-08-17 at 17 38 00
screen shot 2016-08-17 at 17 38 05
screen shot 2016-08-17 at 17 38 09
screen shot 2016-08-17 at 17 38 32
screen shot 2016-08-17 at 17 38 50
screen shot 2016-08-17 at 17 39 04
screen shot 2016-08-17 at 17 39 17
screen shot 2016-08-17 at 17 40 16
- [x] PreferencesDialog.ui
screen shot 2016-08-17 at 17 46 00
screen shot 2016-08-17 at 17 46 03
screen shot 2016-08-17 at 17 46 19
screen shot 2016-08-17 at 17 46 26
screen shot 2016-08-17 at 17 46 36
screen shot 2016-08-17 at 17 46 40
- [x] VacuumDialog.ui
screen shot 2016-08-17 at 17 47 18

**Comment by FriedrichFroebel** [comment]
Should be changed now.

**Comment by justinclift** [comment]
Thanks @FriedrichFroebel, that's really excellent. 😁 

screen shot 2016-08-18 at 11 26 17
screen shot 2016-08-18 at 11 22 06
screen shot 2016-08-18 at 11 22 10
screen shot 2016-08-18 at 11 22 25
screen shot 2016-08-18 at 11 22 50
screen shot 2016-08-18 at 11 23 09
screen shot 2016-08-18 at 11 23 32

Merging this in now. :smile:

**Pull request merged**
