### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by GortiZ6**
Completed and fixed italian translation started by @Feyn-Man.
I'd like to ask him if it's ok to use this new version or if he prefers to change something else, but I don't know how to contact him, I hope he reads this merge request :)

### CODE REVIEW

**Comment by justinclift** [comment]
> but I don't know how to contact him

As a tip, if you clone one of his personal repos (for example, [this one](https://github.com/Feyn-Man/FCS-Final-exam-project)), then change into it, you'll be able to view his email address using the `git log` command.

Does that help? :smile:

**Comment by Feyn-Man** [comment]
Hi @GortiZ6, it's fine for me, thank you for your help :smile:

**Comment by justinclift** [comment]
Hmmm, this build is failing due to the AppImage stuff (@deepsidhu1313, this might be of interest).

@GortiZ6 @Feyn-Man Should this be merged now, or is it still in progress? :smile:

**Comment by GortiZ6** [comment]
@justinclift: Yes it helps, I'll remember for next time.
@Feyn-Man: Ok, thanks so I guess if there're no other issue we can merge it. (the failure on travis-ci to me seems unrelated to this merge, but if I can do something to fix it let me know).

**Comment by GortiZ6** [comment]
> 
> 
> Hmmm, this build is failing due to the AppImage stuff (@deepsidhu1313, this might be of interest).
> 
> @GortiZ6 @Feyn-Man Should this be merged now, or is it still in progress? 😄

For me it can be merged, all strings have been translated up to master.

**Comment by justinclift** [comment]
Thanks @GortiZ6, just merged it.

As a thought, are the strings in the `v3.11.x` branch ok, or do they need some of the pieces from this applied there too?  That branch is the one we'll be making the 3.11.0 release from (soon). :smile:

**Comment by GortiZ6** [comment]
@justinclift I've tried to merge this ts file on v3.11.x and everything but one translation was automatically imported. To fix that missing one I've made a new TS file for v3.11.x that you can fin on my branch:
https://github.com/GortiZ6/sqlitebrowser/tree/v3.11.x
Should I do a merge request for it you can you just pull it from there?

**Comment by deepsidhu1313** [comment]
Hi ,

Sorry for late reply. Is it still failing , due to AppImage code ??

**Comment by GortiZ6** [comment]
> 
> Hi , Sorry for late reply. Is it still failing , due to AppImage code ??
> […](#)

I think so -> https://travis-ci.org/sqlitebrowser/sqlitebrowser/builds/476320839?utm_source=github_status&utm_medium=notification

**Comment by deepsidhu1313** [comment]
Sorry guys i dont have access to any machine right now. You can comment out
few lines from travis.yml file and i will try to release a fix this
weekend.

Thanks !!

**Comment by justinclift** [comment]
@GortiZ6 Thanks, I'll have a go at merging your branch now. :smile:

@deepsidhu1313 No worries.  I've just nuked the AppImage lines from the .travis config.  Feel free to add them back  / experiment / etc when you have some time and feel up for it. :smile:

**Comment by justinclift** [comment]
@GortiZ6 That turned out to be pretty easy.  I just cherry-picked the two commits from your `v3.11.x` branch across to ours, then push it to our repo.  All done. Cool! :smile:

**Comment by justinclift** [comment]
Tracking down a breaking in our Windows builds... it turns out to be caused by this. :wink:

Looks like the translation file was renamed to upper case for one part of it's name, with a soft link pointing to the new name.

Do you remember what that was for?  We'll need to change the name back to get things working, but it'd be useful to know the problem that the rename was meant to solve, just in case it's important for something else. :smile:

**Comment by GortiZ6** [comment]
Actually it was just to match the "it_IT" language code and leave space for an "it_CH" translation without eliminating the previous generic "it" definition... I forgot the Windows build and issues with the softlink, it was just to avoid to have two equal files for the translations and to maintain them both. For me it's ok also to keep only the generic "it" translation and to push this issue forward in case some one arise the need to have an it_CH translation (which I found quite improbable).

**Comment by justinclift** [comment]
Ahhh.  If we do need to rename the file around (eg to `it_IT` version), it should be doable.  We can rename it, and make sure the various files it's listed in get changed too.

I **think** (without testing it), that should work. :smile:

**Pull request merged**
