### PR TITLE
Updated Russian translation

### PR DESCRIPTION
**Pull request by schdub**

### CODE REVIEW

**Comment by justinclift** [comment]
Awesome @schdub, this looks very complete! 😀 

- [x] AboutDialog.ui
screen shot 2016-08-10 at 15 59 30
- [x] CipherDialog.ui
screen shot 2016-08-10 at 16 01 09
- [x] ColumnDisplayFormatDialog.ui
screen shot 2016-08-10 at 16 11 20
- [x] CreateIndexDialog.ui
screen shot 2016-08-10 at 16 12 31
- [x] EditDialog.ui
screen shot 2016-08-10 at 16 14 02
screen shot 2016-08-10 at 16 14 08
screen shot 2016-08-10 at 16 14 19
- [x] EditTableDialog.ui
screen shot 2016-08-10 at 16 16 29
- [x] ExportCsvDialog.ui
screen shot 2016-08-10 at 16 18 15
- [x] ExportSqlDialog.ui
screen shot 2016-08-10 at 16 19 17
- [x] ImportCsvDialog.ui
screen shot 2016-08-10 at 16 23 28
- [x] MainWindow.ui
screen shot 2016-08-10 at 16 02 52
screen shot 2016-08-10 at 16 02 59
screen shot 2016-08-10 at 16 03 23
screen shot 2016-08-10 at 16 03 45
- [x] PreferencesDialog.ui
screen shot 2016-08-10 at 16 05 50
screen shot 2016-08-10 at 16 05 56
screen shot 2016-08-10 at 16 06 04
screen shot 2016-08-10 at 16 06 11
screen shot 2016-08-10 at 16 06 18
- [x] VacuumDialog.ui
screen shot 2016-08-10 at 16 08 52

**Comment by justinclift** [comment]
One strange thing occur when making the screenshots above.  It seems like the "Import CSV" dialog doesn't display the contents correctly.

It could be a bug in our code, or it could just be my system.

Do you have a second to check if that dialog displays things correctly for you? :smile:

**Comment by schdub** [comment]
@justinclift ImportCsvDialog.ui in my system:
screenshot from 2016-08-10 184559

Do you mean empty preview at bottom of dialog?

**Comment by justinclift** [comment]
Thanks @schdub. :smile:

Yes, that's not supposed to happen. 😦 

I'll file a new bug about it.

**Comment by schdub** [comment]
@justinclift, I think that's because Export CSV dialog allows to export data with empty "Other" line separator value.

**Comment by justinclift** [comment]
Ahhh, that could be it.  I'll try that now.

It might not be a bug after all. 😀

**Comment by justinclift** [comment]
It was worth trying, but it doesn't seem to be that. :wink:

When testing with an empty "Other" line separator here (created by "Export CSV"), a preview is always shown for the import.  Even it it's just one very long line of header:
screen shot 2016-08-10 at 17 11 57
screen shot 2016-08-10 at 17 12 03

For now, created a new Issue #720 about it.  It can be investigated at a later date (after 3.9.0 release). :smile:

**Pull request merged**
