### PR TITLE
open a set of SQL-Files

### PR DESCRIPTION
**Pull request by horst-p-w-neubauer**
Implements open a set of SQL-Files #2207
Allows to select more than one File in the OpenDialog and opens them in new tabs.

analyze open translations
update German translation

### CODE REVIEW

**Comment by mgrojo** [comment]
Thank you, @horst-p-w-neubauer! 

The general feature of opening multiple files is great, though. But I have no time now to make the code review.

But I'm used to my editor of choice (emacs) that can open multiple "buffers" (tabs in our case) of the same underlying file. Is only one tab for file that what we really want? It seems to me arbitrarily limiting the options to the user.

**Comment by horst-p-w-neubauer** [comment]
Is there anything, I can do?

**Comment by horst-p-w-neubauer** [comment]
dumped al .ts files changes

**Comment by mgrojo** [comment]
Thanks @horst-p-w-neubauer. It's now merged!

**Pull request merged**
