### PR TITLE
Fixed issue #390 ("crash then correct table").

### PR DESCRIPTION
**Pull request by GeorgijK**
When function is called save(...) and instead of saving it releases savepoint - it seems a lit bit strange for me, so I have renamed some functions and fixed couple of logical errors (well, at least from my POV :D ).
Let's discuss

### CODE REVIEW

**Comment by justinclift** [comment]
@MKleusberg Would you be ok to review this? :smile:

**Comment by GeorgijK** [comment]
It is worth to check from flow perspective, I am not an SQLite expert and have been digging sqlitebrowser sources only for couple of hours.
Especially we should pay attention to places where former save() and saveAll() were used. 
Due to misleading name - I am not sure what was meant in particular points: either "I want to save" or "I want to release savepoint" :)

**Comment by justinclift** [comment]
We still need someone to review this before we can merge it.  @rp- do you have the time?

**Comment by MKleusberg** [comment]
Looks good for me and the renaming makes a lot of sense :smiley: There are two things though I'd like to point out:
1) There are two places where you execute COMMIT manually. The problem here is that this way the savepoint list doesn't get cleared. This will cause an error later when trying to revert to a savepoint which the application thinks exist but doesn't really. The other effect is that the database is still marked as dirty (see the ```DBBrowserDB::getDirty()``` method in file sqlitedb.cpp at line 81). This means the user thinks he still has the ability to save or revert when actually all the changes were already written to disk. So I think these two COMMIT calls should be replaced by releaseAllSavepoints(). We might want to run a COMMIT at the end of that function though, just to be safe.
2) Could you maybe squash those two commits into one so that we have a nice commit history? Like described here: https://github.com/sqlitebrowser/sqlitebrowser/wiki/Merging-Commits)

Other than that this looks good to merge :smiley: Thanks a lot for your effort, @GeorgijK, and sorry for the late reply....

**Comment by MKleusberg** [comment]
Just applied the changes myself because I think it's good to have this PR in there rather sooner than later :smiley: Thanks @GeorgijK for contributing them!

**Pull request closed without merging**
