### PR TITLE
Disabled bufferedDraw for smooth fonts on Retina and high DPI displays

### PR DESCRIPTION
**Pull request by nickberry17**
A proposed fix for this issue
https://github.com/sqlitebrowser/sqlitebrowser/issues/498#issuecomment-214718575

### CODE REVIEW

**Comment by justinclift** [comment]
Yep, that's the perfect way to do it. :smile:

This looks good to me, so I'll merge it now.  The nightly build tomorrow will have the change in it, which would be nifty for you to verify and report back success/failure. :smile:

**Comment by justinclift** [comment]
@MKleusberg You might want to cast your eye over this (one liner), just in case. :wink:

**Comment by nickberry17** [comment]
Can confirm that the nightly build works on OS X with Retina display.  I tested it on a Mac without retina display as well, no negative effects.

screenshot 2016-04-28 09 11 05

**Comment by justinclift** [comment]
Awesome.  Such a simple change, but so much effect.  Well done!

What're your next Pull Request going to be? :grinning:

**Comment by nickberry17** [comment]
😄 yeah, just an easy one liner. The process of finding out what to change gave me a chance to see how qt works, which I've never used before. It was pretty interesting, but not too complicated as the code, to my novice eye, is really clean and well organised (so is this app's).  As for what the future holds, I'm just gonna keep learning and programming, hey? 😀

**Comment by nickberry17** [comment]
But I did notice that my professor always has to make some changes to the font size in class (prefs aren't saved because the machine boots from a master OS image on every reboot) so I was thinking about adding a "Presenter" mode checkbox or something to the preferences pane.  Might be a nifty little project for me to dabble in C++.  I won't make any pull requests until that branch is rock solid though.

**Comment by justinclift** [comment]
Sure, a presenter mode would be a welcome addition.  Get it mostly right, and we can look over the code and possibly make some suggestions, or even make a few test builds for people to try it with. :smile:

**Comment by justinclift** [comment]
Hmmm, second thought.  With that master OS image... er... how about getting the font size changed there, so its "correct" at the source? :wink:

**Comment by MKleusberg** [comment]
One extra suggestion here: if this fix has no side-effects you should think about proposing it to the upstream QScintilla project. Otherwise your change won't be included in versions of DB4S which are compiled against an external QScintilla library (like on Linux distros) or might be overridden when we update the QScintilla source in our repository and forget about this...

**Comment by justinclift** [comment]
Good idea. :smile:

**Comment by revolter** [comment]
@nickberry17, Did you manage to propose the fix to `QScintilla`?

**Comment by nickberry17** [comment]
Regrettably, I have not.  I did research it, and found a commit stating a permanent fix had already been implemented in v2.8.1 that removes the need to disable bufferedDraw, though the compiled version does not seem to behave as such.  I think it should be brought to the maintainer's attention.

**Pull request merged**
