### PR TITLE
Updated French translation for 'MainWindow/Edit Pragmas' tab, ColumnDisplayFormatDialog …

### PR DESCRIPTION
**Pull request by hchiper**
…and other minor things

Hi,

Here are the translations for the Edit Pragmas tab of the Main window.

While working on that part, I also had a look at the strings in `ColumnDisplayFormatDialog.ui`. I found some original English strings ambiguous. So I looked at the code to understand their meaning more precisely and I think some of them can be made more explicit. Here are the corresponding code and suggestions.

#### ui->comboDisplayFormat->addItem(tr("Decimal number"), "decimal"); <br/> formatFunctions["decimal"] = "printf('%d', " + e_column_name + ")";
- The %d format in `printf` outputs an integer: `printf("%d %d", 2.718, -1.866) -> 2 -1 `.  
  It is a decimal number, as opposed to hexadecimal, but decimal is also synonymous of floating point.
- -> "Integer number (truncated)"

#### ui->comboDisplayFormat->addItem(tr("Round number"), "round"); <br/> formatFunctions["round"] = "round(" + e_column_name + ")";
- The result of `round()` is strange in SQLite: `round(2.718) -> 3.0` although the result should be `2.7` since one decimal digit is displayed.  
- -> "Rounded number (nearest integer)"

#### ui->comboDisplayFormat->addItem(tr("Apple NSDate to date"), "appleDate"); <br/>formatFunctions["appleDate"] = "datetime('2001-01-01', " + e_column_name + " || ' seconds')";
- datetime() returns date and time
- -> "Apple NSDate to date & time"

#### ui->comboDisplayFormat->addItem(tr("Java epoch (milliseconds) to date"), "javaEpoch"); <br/> formatFunctions["javaEpoch"] = "strftime('%Y-%m-%d %H:%M:%S.', " + e_column_name + "/1000, 'unixepoch') || (" + e_column_name + "%1000)";
- Doesn't this simpler code produce the same result (with 1000.0 instead of 1000):  
  "datetime(" + e_column_name + "/1000.0, 'unixepoch', 'subsec')"
  ex.: select datetime(1724069335155 / 1000.0, 'unixepoch', 'subsec'); -> 2024-08-19 12:08:55.155
- -> "Java epoch to date & time (millisecond)"

#### ui->comboDisplayFormat->addItem(tr(".NET DateTime.Ticks to date"), "dotNetTicks"); <br/> formatFunctions["dotNetTicks"] = "datetime(" + e_column_name + " / 10000000 - 62135596800, 'unixepoch')";
- datetime() returns date and time
- -> ".NET DateTime.Ticks to date & time"

#### ui->comboDisplayFormat->addItem(tr("Julian day to date"), "julian"); <br/> formatFunctions["julian"] = "datetime(" + e_column_name + ")";
- datetime() returns date and time
- -> "Julian day to date & time"

#### ui->comboDisplayFormat->addItem(tr("Unix epoch to date"), "epoch"); <br/> formatFunctions["epoch"] = "datetime(" + e_column_name + ", 'unixepoch')";
- datetime() returns date and time
- -> "Unix epoch to date & time"

#### ui->comboDisplayFormat->addItem(tr("Unix epoch to local time"), "epochLocalTime"); <br/> formatFunctions["epochLocalTime"] = "datetime(" + e_column_name + ", 'unixepoch', 'localtime')";
- datetime() returns date and time
- -> "Unix epoch to local date & time"

#### ui->comboDisplayFormat->addItem(tr("WebKit / Chromium epoch to date"), "webkitEpoch"); <br/> formatFunctions["webkitEpoch"] = "datetime(" + e_column_name + " / 1e6 - 11644473600, 'unixepoch')";
- datetime() returns date and time
- -> "Webkit / Chromium epoch to date & time"

#### ui->comboDisplayFormat->addItem(tr("WebKit / Chromium epoch to local time"), "webkitEpochLocalTime"); <br/> formatFunctions["webkitEpochLocalTime"] = "datetime(" + e_column_name + " / 1e6 - 11644473600, 'unixepoch', 'localtime')";
- datetime() returns date and time
- -> "Webkit / Chromium epoch to local date & time"

#### ui->comboDisplayFormat->addItem(tr("Windows DATE to date"), "winDate"); <br/> formatFunctions["winDate"] = "datetime('1899-12-30', " + e_column_name + " || ' days')";
- datetime() returns date and time
- -> "Windows epoch to date & time"

#### ui->comboDisplayFormat->addItem(tr("Binary GUID to text"), "guid");
- I've tested with "12bed35b-45f1-4ad6-a430-cec0aca74b03": it is displayed as "65623231-3364-6235-2D34-3566312D3461" which is not really text.

### CODE REVIEW

**Comment by mgrojo** [comment]
@mvt91 maybe you like to review these changes.

**Comment by mvt91** [comment]
Hi Manuel

If it's not urgent, I can do it sometime next week.
I've not my pc this week... 

Mail d'origine -----
De: Manuel ***@***.***>
À: sqlitebrowser/sqlitebrowser ***@***.***>
Cc: mvt91 ***@***.***>, Mention ***@***.***>
Envoyé: Thu, 29 Aug 2024 23:33:45 +0200 (CEST)
Objet: Re: [sqlitebrowser/sqlitebrowser] Updated French translation for 'MainWindow/Edit Pragmas' tab, ColumnDisplayFormatDialog … (PR #3710)

@mvt91 maybe you like to review these changes.

**Comment by mgrojo** [comment]
@mvt91 if you don't have time, we can merge it now. There's always time for any improvement until the next release.

**Comment by mvt91** [comment]
Hi Manuel
Do it. I'll try to help you for the next release 
Best regards
----- Mail d'origine -----
De: Manuel ***@***.***>
À: sqlitebrowser/sqlitebrowser ***@***.***>
Cc: mvt91 ***@***.***>, Mention ***@***.***>
Envoyé: Fri, 27 Sep 2024 23:56:37 +0200 (CEST)
Objet: Re: [sqlitebrowser/sqlitebrowser] Updated French translation for 'MainWindow/Edit Pragmas' tab, ColumnDisplayFormatDialog … (PR #3710)

@mvt91 if you don't have time, we can merge it now. There's always time for any improvement until the next release.

**Comment by justinclift** [comment]
No worries.  Just merged it. :smile:

Thanks for working on this @hchiper, it all helps. :smile:

**Pull request merged**
