### PR TITLE
Add Slack invite link in the README file

### PR DESCRIPTION
**Pull request by revolter**

### CODE REVIEW

**Comment by justinclift** [comment]
Just to double check, will that invite link work ok with multiple people using it?

They're not generating personalised ones (eg one per person) are they?

**Comment by revolter** [comment]
Yep, and for unlimited time also.

**Comment by justinclift** [comment]
Cool.  Sounds good to me then. :smile:

**Comment by justinclift** [comment]
Would you be ok to add a button to the index.html page (gh-pages branch) as well?

**Comment by chrisjlocke** [comment]
Just a nod that you may also want to add a link to contact the workspace administrator.  Following the link in the readme (db4s.slack.com) says, "Contact the workspace administrator for an invitation".  But there is no way to contact 'them' ?

**Comment by revolter** [comment]
@justinclift, Sure.
@chrisjlocke, I just added that to keep it similar to Gitter, but you can't get to that unless you view the source.

**Comment by revolter** [comment]
Actually, you're right, because that shows up if images are disabled or if you select and copy the image. I'll fix it in `master`.

**Pull request merged**
